package com.ttgis.recruit.domain;

import java.io.Serializable;
import java.util.Date;

public class ArticleReview implements Serializable
{

	private static final long serialVersionUID = -6023999736449737030L;

	private String plsj;

	public String getPlsj()
	{
		return plsj;
	}

	public void setPlsj(String plsj)
	{
		this.plsj = plsj;
	}

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column ARTICLE_REVIEW.ARTICLE_REVIEW_ID
	 * 
	 * @mbggenerated
	 */
	private String articleReviewId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column ARTICLE_REVIEW.ARTICLE_REVIEW_PLSJ
	 * 
	 * @mbggenerated
	 */
	private Date articleReviewPlsj;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column ARTICLE_REVIEW.ARTICLE_REVIEW_PLR
	 * 
	 * @mbggenerated
	 */
	private String articleReviewPlr;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column ARTICLE_REVIEW.ARTICLE_REVIEW_ADDTIME
	 * 
	 * @mbggenerated
	 */
	private Date articleReviewAddtime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column ARTICLE_REVIEW.ARTICLE_REVIEW_DELFLAG
	 * 
	 * @mbggenerated
	 */
	private Long articleReviewDelflag;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column ARTICLE_REVIEW.ARTICLE_ID
	 * 
	 * @mbggenerated
	 */
	private String articleId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column ARTICLE_REVIEW.ARTICLE_REVIEW_NR
	 * 
	 * @mbggenerated
	 */
	private String articleReviewNr;

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column ARTICLE_REVIEW.ARTICLE_REVIEW_ID
	 * 
	 * @return the value of ARTICLE_REVIEW.ARTICLE_REVIEW_ID
	 * 
	 * @mbggenerated
	 */
	public String getArticleReviewId()
	{
		return articleReviewId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column ARTICLE_REVIEW.ARTICLE_REVIEW_ID
	 * 
	 * @param articleReviewId
	 *            the value for ARTICLE_REVIEW.ARTICLE_REVIEW_ID
	 * 
	 * @mbggenerated
	 */
	public void setArticleReviewId(String articleReviewId)
	{
		this.articleReviewId = articleReviewId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column ARTICLE_REVIEW.ARTICLE_REVIEW_PLSJ
	 * 
	 * @return the value of ARTICLE_REVIEW.ARTICLE_REVIEW_PLSJ
	 * 
	 * @mbggenerated
	 */
	public Date getArticleReviewPlsj()
	{
		return articleReviewPlsj;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column ARTICLE_REVIEW.ARTICLE_REVIEW_PLSJ
	 * 
	 * @param articleReviewPlsj
	 *            the value for ARTICLE_REVIEW.ARTICLE_REVIEW_PLSJ
	 * 
	 * @mbggenerated
	 */
	public void setArticleReviewPlsj(Date articleReviewPlsj)
	{
		this.articleReviewPlsj = articleReviewPlsj;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column ARTICLE_REVIEW.ARTICLE_REVIEW_PLR
	 * 
	 * @return the value of ARTICLE_REVIEW.ARTICLE_REVIEW_PLR
	 * 
	 * @mbggenerated
	 */
	public String getArticleReviewPlr()
	{
		return articleReviewPlr;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column ARTICLE_REVIEW.ARTICLE_REVIEW_PLR
	 * 
	 * @param articleReviewPlr
	 *            the value for ARTICLE_REVIEW.ARTICLE_REVIEW_PLR
	 * 
	 * @mbggenerated
	 */
	public void setArticleReviewPlr(String articleReviewPlr)
	{
		this.articleReviewPlr = articleReviewPlr;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column ARTICLE_REVIEW.ARTICLE_REVIEW_ADDTIME
	 * 
	 * @return the value of ARTICLE_REVIEW.ARTICLE_REVIEW_ADDTIME
	 * 
	 * @mbggenerated
	 */
	public Date getArticleReviewAddtime()
	{
		return articleReviewAddtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column ARTICLE_REVIEW.ARTICLE_REVIEW_ADDTIME
	 * 
	 * @param articleReviewAddtime
	 *            the value for ARTICLE_REVIEW.ARTICLE_REVIEW_ADDTIME
	 * 
	 * @mbggenerated
	 */
	public void setArticleReviewAddtime(Date articleReviewAddtime)
	{
		this.articleReviewAddtime = articleReviewAddtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column ARTICLE_REVIEW.ARTICLE_REVIEW_DELFLAG
	 * 
	 * @return the value of ARTICLE_REVIEW.ARTICLE_REVIEW_DELFLAG
	 * 
	 * @mbggenerated
	 */
	public Long getArticleReviewDelflag()
	{
		return articleReviewDelflag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column ARTICLE_REVIEW.ARTICLE_REVIEW_DELFLAG
	 * 
	 * @param articleReviewDelflag
	 *            the value for ARTICLE_REVIEW.ARTICLE_REVIEW_DELFLAG
	 * 
	 * @mbggenerated
	 */
	public void setArticleReviewDelflag(Long articleReviewDelflag)
	{
		this.articleReviewDelflag = articleReviewDelflag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column ARTICLE_REVIEW.ARTICLE_ID
	 * 
	 * @return the value of ARTICLE_REVIEW.ARTICLE_ID
	 * 
	 * @mbggenerated
	 */
	public String getArticleId()
	{
		return articleId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column ARTICLE_REVIEW.ARTICLE_ID
	 * 
	 * @param articleId
	 *            the value for ARTICLE_REVIEW.ARTICLE_ID
	 * 
	 * @mbggenerated
	 */
	public void setArticleId(String articleId)
	{
		this.articleId = articleId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column ARTICLE_REVIEW.ARTICLE_REVIEW_NR
	 * 
	 * @return the value of ARTICLE_REVIEW.ARTICLE_REVIEW_NR
	 * 
	 * @mbggenerated
	 */
	public String getArticleReviewNr()
	{
		return articleReviewNr;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column ARTICLE_REVIEW.ARTICLE_REVIEW_NR
	 * 
	 * @param articleReviewNr
	 *            the value for ARTICLE_REVIEW.ARTICLE_REVIEW_NR
	 * 
	 * @mbggenerated
	 */
	public void setArticleReviewNr(String articleReviewNr)
	{
		this.articleReviewNr = articleReviewNr;
	}
}