package com.ttgis.recruit.domain;

import java.io.Serializable;
import java.util.Date;

public class Article implements Serializable
{

	private static final long serialVersionUID = 1374774931039193492L;
	private String pls;

	public String getPls()
	{
		return pls;
	}

	public void setPls(String pls)
	{
		this.pls = pls;
	}

	private String content;

	public String getContent()
	{
		return content;
	}

	public void setContent(String content)
	{
		this.content = content;
	}

	private String articleReason;

	public String getArticleReason()
	{
		return articleReason;
	}

	public void setArticleReason(String articleReason)
	{
		this.articleReason = articleReason;
	}

	private String addTime;

	public String getAddTime()
	{
		return addTime;
	}

	public void setAddTime(String addTime)
	{
		this.addTime = addTime;
	}

	private String fbsj;

	public String getFbsj()
	{
		return fbsj;
	}

	public void setFbsj(String fbsj)
	{
		this.fbsj = fbsj;
	}

	private String articleFbr;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column ARTICLE.ARTICLE_ID
	 * 
	 * @mbggenerated
	 */
	private String articleId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column ARTICLE.LTBQ_ID
	 * 
	 * @mbggenerated
	 */
	private String ltbqId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column ARTICLE.ARTICLE_AUTHOR
	 * 
	 * @mbggenerated
	 */
	private String articleAuthor;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column ARTICLE.ARTICLE_VIEWER
	 * 
	 * @mbggenerated
	 */
	private String articleViewer;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column ARTICLE.ARTICLE_FBSJ
	 * 
	 * @mbggenerated
	 */
	private Date articleFbsj;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column ARTICLE.ARTICLE_TYPE
	 * 
	 * @mbggenerated
	 */
	private String articleType;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column ARTICLE.ARTICLE_ADDTIME
	 * 
	 * @mbggenerated
	 */
	private Date articleAddtime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column ARTICLE.ARTICLE_DELFLAG
	 * 
	 * @mbggenerated
	 */
	private Long articleDelflag;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column ARTICLE.ARTICLE_TITLE
	 * 
	 * @mbggenerated
	 */
	private String articleTitle;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column ARTICLE.ARTICLE_CONTENT
	 * 
	 * @mbggenerated
	 */
	private String articleContent;

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column ARTICLE.ARTICLE_ID
	 * 
	 * @return the value of ARTICLE.ARTICLE_ID
	 * 
	 * @mbggenerated
	 */
	public String getArticleId()
	{
		return articleId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column ARTICLE.ARTICLE_ID
	 * 
	 * @param articleId
	 *            the value for ARTICLE.ARTICLE_ID
	 * 
	 * @mbggenerated
	 */
	public void setArticleId(String articleId)
	{
		this.articleId = articleId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column ARTICLE.LTBQ_ID
	 * 
	 * @return the value of ARTICLE.LTBQ_ID
	 * 
	 * @mbggenerated
	 */
	public String getLtbqId()
	{
		return ltbqId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column ARTICLE.LTBQ_ID
	 * 
	 * @param ltbqId
	 *            the value for ARTICLE.LTBQ_ID
	 * 
	 * @mbggenerated
	 */
	public void setLtbqId(String ltbqId)
	{
		this.ltbqId = ltbqId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column ARTICLE.ARTICLE_AUTHOR
	 * 
	 * @return the value of ARTICLE.ARTICLE_AUTHOR
	 * 
	 * @mbggenerated
	 */
	public String getArticleAuthor()
	{
		return articleAuthor;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column ARTICLE.ARTICLE_AUTHOR
	 * 
	 * @param articleAuthor
	 *            the value for ARTICLE.ARTICLE_AUTHOR
	 * 
	 * @mbggenerated
	 */
	public void setArticleAuthor(String articleAuthor)
	{
		this.articleAuthor = articleAuthor;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column ARTICLE.ARTICLE_VIEWER
	 * 
	 * @return the value of ARTICLE.ARTICLE_VIEWER
	 * 
	 * @mbggenerated
	 */
	public String getArticleViewer()
	{
		return articleViewer;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column ARTICLE.ARTICLE_VIEWER
	 * 
	 * @param articleViewer
	 *            the value for ARTICLE.ARTICLE_VIEWER
	 * 
	 * @mbggenerated
	 */
	public void setArticleViewer(String articleViewer)
	{
		this.articleViewer = articleViewer;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column ARTICLE.ARTICLE_FBSJ
	 * 
	 * @return the value of ARTICLE.ARTICLE_FBSJ
	 * 
	 * @mbggenerated
	 */
	public Date getArticleFbsj()
	{
		return articleFbsj;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column ARTICLE.ARTICLE_FBSJ
	 * 
	 * @param articleFbsj
	 *            the value for ARTICLE.ARTICLE_FBSJ
	 * 
	 * @mbggenerated
	 */
	public void setArticleFbsj(Date articleFbsj)
	{
		this.articleFbsj = articleFbsj;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column ARTICLE.ARTICLE_TYPE
	 * 
	 * @return the value of ARTICLE.ARTICLE_TYPE
	 * 
	 * @mbggenerated
	 */
	public String getArticleType()
	{
		return articleType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column ARTICLE.ARTICLE_TYPE
	 * 
	 * @param articleType
	 *            the value for ARTICLE.ARTICLE_TYPE
	 * 
	 * @mbggenerated
	 */
	public void setArticleType(String articleType)
	{
		this.articleType = articleType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column ARTICLE.ARTICLE_ADDTIME
	 * 
	 * @return the value of ARTICLE.ARTICLE_ADDTIME
	 * 
	 * @mbggenerated
	 */
	public Date getArticleAddtime()
	{
		return articleAddtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column ARTICLE.ARTICLE_ADDTIME
	 * 
	 * @param articleAddtime
	 *            the value for ARTICLE.ARTICLE_ADDTIME
	 * 
	 * @mbggenerated
	 */
	public void setArticleAddtime(Date articleAddtime)
	{
		this.articleAddtime = articleAddtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column ARTICLE.ARTICLE_DELFLAG
	 * 
	 * @return the value of ARTICLE.ARTICLE_DELFLAG
	 * 
	 * @mbggenerated
	 */
	public Long getArticleDelflag()
	{
		return articleDelflag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column ARTICLE.ARTICLE_DELFLAG
	 * 
	 * @param articleDelflag
	 *            the value for ARTICLE.ARTICLE_DELFLAG
	 * 
	 * @mbggenerated
	 */
	public void setArticleDelflag(Long articleDelflag)
	{
		this.articleDelflag = articleDelflag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column ARTICLE.ARTICLE_TITLE
	 * 
	 * @return the value of ARTICLE.ARTICLE_TITLE
	 * 
	 * @mbggenerated
	 */
	public String getArticleTitle()
	{
		return articleTitle;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column ARTICLE.ARTICLE_TITLE
	 * 
	 * @param articleTitle
	 *            the value for ARTICLE.ARTICLE_TITLE
	 * 
	 * @mbggenerated
	 */
	public void setArticleTitle(String articleTitle)
	{
		this.articleTitle = articleTitle;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column ARTICLE.ARTICLE_CONTENT
	 * 
	 * @return the value of ARTICLE.ARTICLE_CONTENT
	 * 
	 * @mbggenerated
	 */
	public String getArticleContent()
	{
		return articleContent;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column ARTICLE.ARTICLE_CONTENT
	 * 
	 * @param articleContent
	 *            the value for ARTICLE.ARTICLE_CONTENT
	 * 
	 * @mbggenerated
	 */
	public void setArticleContent(String articleContent)
	{
		this.articleContent = articleContent;
	}

	public String getArticleFbr()
	{
		return articleFbr;
	}

	public void setArticleFbr(String articleFbr)
	{
		this.articleFbr = articleFbr;
	}

}