package com.ttgis.recruit.domain;

import java.io.Serializable;
import java.util.Date;

public class Bbs implements Serializable
{

	private static final long serialVersionUID = 4953635557283855083L;

	private String ssbk;

	public String getSsbk()
	{
		return ssbk;
	}

	public void setSsbk(String ssbk)
	{
		this.ssbk = ssbk;
	}

	private String zan;

	public String getZan()
	{
		return zan;
	}

	public void setZan(String zan)
	{
		this.zan = zan;
	}

	private String bbsZan;

	public String getBbsZan()
	{
		return bbsZan;
	}

	public void setBbsZan(String bbsZan)
	{
		this.bbsZan = bbsZan;
	}

	private String rcount;

	public String getRcount()
	{
		return rcount;
	}

	public void setRcount(String rcount)
	{
		this.rcount = rcount;
	}

	private String ltbkId;

	public String getLtbkId()
	{
		return ltbkId;
	}

	public void setLtbkId(String ltbkId)
	{
		this.ltbkId = ltbkId;
	}

	private String bbsBqid;

	public String getBbsBqid()
	{
		return bbsBqid;
	}

	public void setBbsBqid(String bbsBqid)
	{
		this.bbsBqid = bbsBqid;
	}

	private String fbsj;

	public String getFbsj()
	{
		return fbsj;
	}

	public void setFbsj(String fbsj)
	{
		this.fbsj = fbsj;
	}

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column BBS.BBS_ID
	 * 
	 * @mbggenerated
	 */
	private String bbsId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column BBS.BBS_FBR
	 * 
	 * @mbggenerated
	 */
	private String bbsFbr;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column BBS.BBS_NR
	 * 
	 * @mbggenerated
	 */
	private String bbsNr;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column BBS.BBS_FBSJ
	 * 
	 * @mbggenerated
	 */
	private Date bbsFbsj;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column BBS.BBS_PLID
	 * 
	 * @mbggenerated
	 */
	private String bbsPlid;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column BBS.BBS_DELFLAG
	 * 
	 * @mbggenerated
	 */
	private Long bbsDelflag;

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column BBS.BBS_ID
	 * 
	 * @return the value of BBS.BBS_ID
	 * 
	 * @mbggenerated
	 */
	public String getBbsId()
	{
		return bbsId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column BBS.BBS_ID
	 * 
	 * @param bbsId
	 *            the value for BBS.BBS_ID
	 * 
	 * @mbggenerated
	 */
	public void setBbsId(String bbsId)
	{
		this.bbsId = bbsId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column BBS.BBS_FBR
	 * 
	 * @return the value of BBS.BBS_FBR
	 * 
	 * @mbggenerated
	 */
	public String getBbsFbr()
	{
		return bbsFbr;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column BBS.BBS_FBR
	 * 
	 * @param bbsFbr
	 *            the value for BBS.BBS_FBR
	 * 
	 * @mbggenerated
	 */
	public void setBbsFbr(String bbsFbr)
	{
		this.bbsFbr = bbsFbr;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column BBS.BBS_NR
	 * 
	 * @return the value of BBS.BBS_NR
	 * 
	 * @mbggenerated
	 */
	public String getBbsNr()
	{
		return bbsNr;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column BBS.BBS_NR
	 * 
	 * @param bbsNr
	 *            the value for BBS.BBS_NR
	 * 
	 * @mbggenerated
	 */
	public void setBbsNr(String bbsNr)
	{
		this.bbsNr = bbsNr;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column BBS.BBS_FBSJ
	 * 
	 * @return the value of BBS.BBS_FBSJ
	 * 
	 * @mbggenerated
	 */
	public Date getBbsFbsj()
	{
		return bbsFbsj;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column BBS.BBS_FBSJ
	 * 
	 * @param bbsFbsj
	 *            the value for BBS.BBS_FBSJ
	 * 
	 * @mbggenerated
	 */
	public void setBbsFbsj(Date bbsFbsj)
	{
		this.bbsFbsj = bbsFbsj;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column BBS.BBS_PLID
	 * 
	 * @return the value of BBS.BBS_PLID
	 * 
	 * @mbggenerated
	 */
	public String getBbsPlid()
	{
		return bbsPlid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column BBS.BBS_PLID
	 * 
	 * @param bbsPlid
	 *            the value for BBS.BBS_PLID
	 * 
	 * @mbggenerated
	 */
	public void setBbsPlid(String bbsPlid)
	{
		this.bbsPlid = bbsPlid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column BBS.BBS_DELFLAG
	 * 
	 * @return the value of BBS.BBS_DELFLAG
	 * 
	 * @mbggenerated
	 */
	public Long getBbsDelflag()
	{
		return bbsDelflag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column BBS.BBS_DELFLAG
	 * 
	 * @param bbsDelflag
	 *            the value for BBS.BBS_DELFLAG
	 * 
	 * @mbggenerated
	 */
	public void setBbsDelflag(Long bbsDelflag)
	{
		this.bbsDelflag = bbsDelflag;
	}
}