package com.ttgis.recruit.domain;

import java.io.Serializable;
import java.util.Date;

public class Bmgl implements Serializable
{
	/**
	 * 
	 */
	private static final long serialVersionUID = 5345878482003769489L;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column BMGL.BMGL_ID
	 * 
	 * @mbggenerated
	 */
	private String bmglId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column BMGL.BMGL_KCGL_ID
	 * 
	 * @mbggenerated
	 */
	private String bmglKcglId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column BMGL.BMGL_KSXM
	 * 
	 * @mbggenerated
	 */
	private String bmglKsxm;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column BMGL.BMGL_BKDW
	 * 
	 * @mbggenerated
	 */
	private String bmglBkdw;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column BMGL.BMGL_BKGW
	 * 
	 * @mbggenerated
	 */
	private String bmglBkgw;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column BMGL.BMGL_BYXX
	 * 
	 * @mbggenerated
	 */
	private String bmglByxx;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column BMGL.BMGL_KSRQ
	 * 
	 * @mbggenerated
	 */
	private Date bmglKsrq;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column BMGL.BMGL_KSSJ
	 * 
	 * @mbggenerated
	 */
	private String bmglKssj;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column BMGL.BMGL_SFQR
	 * 
	 * @mbggenerated
	 */
	private String bmglSfqr;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column BMGL.BMGL_LXDH
	 * 
	 * @mbggenerated
	 */
	private Long bmglLxdh;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column BMGL.BMGL_ADDTIME
	 * 
	 * @mbggenerated
	 */
	private Date bmglAddtime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column BMGL.BMGL_DELFLAG
	 * 
	 * @mbggenerated
	 */
	private Long bmglDelflag;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column BMGL.BMGL_KSCJ
	 * 
	 * @mbggenerated
	 */
	private String bmglKscj;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column BMGL.BMGL_TSZG
	 * 
	 * @mbggenerated
	 */
	private String bmglTszg;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column BMGL.BMGL_SFZH
	 * 
	 * @mbggenerated
	 */
	private String bmglSfzh;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column BMGL.BMGL_JTJLKID
	 * 
	 * @mbggenerated
	 */
	private String bmglJtjlkid;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column BMGL.BMGL_BKDWDM
	 * 
	 * @mbggenerated
	 */
	private String bmglBkdwdm;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column BMGL.BMGL_KSXB
	 * 
	 * @mbggenerated
	 */
	private String bmglKsxb;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column BMGL.BMGL_KSDD
	 * 
	 * @mbggenerated
	 */
	private String bmglKsdd;
	private Long bmglPrintflag;
	private String bmglKcmc;

	public Long getBmglPrintflag()
	{
		return bmglPrintflag;
	}

	public void setBmglPrintflag(Long bmglPrintflag)
	{
		this.bmglPrintflag = bmglPrintflag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column BMGL.BMGL_ID
	 * 
	 * @return the value of BMGL.BMGL_ID
	 * 
	 * @mbggenerated
	 */
	public String getBmglId()
	{
		return bmglId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column BMGL.BMGL_ID
	 * 
	 * @param bmglId
	 *            the value for BMGL.BMGL_ID
	 * 
	 * @mbggenerated
	 */
	public void setBmglId(String bmglId)
	{
		this.bmglId = bmglId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column BMGL.BMGL_KCGL_ID
	 * 
	 * @return the value of BMGL.BMGL_KCGL_ID
	 * 
	 * @mbggenerated
	 */
	public String getBmglKcglId()
	{
		return bmglKcglId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column BMGL.BMGL_KCGL_ID
	 * 
	 * @param bmglKcglId
	 *            the value for BMGL.BMGL_KCGL_ID
	 * 
	 * @mbggenerated
	 */
	public void setBmglKcglId(String bmglKcglId)
	{
		this.bmglKcglId = bmglKcglId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column BMGL.BMGL_KSXM
	 * 
	 * @return the value of BMGL.BMGL_KSXM
	 * 
	 * @mbggenerated
	 */
	public String getBmglKsxm()
	{
		return bmglKsxm;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column BMGL.BMGL_KSXM
	 * 
	 * @param bmglKsxm
	 *            the value for BMGL.BMGL_KSXM
	 * 
	 * @mbggenerated
	 */
	public void setBmglKsxm(String bmglKsxm)
	{
		this.bmglKsxm = bmglKsxm;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column BMGL.BMGL_BKDW
	 * 
	 * @return the value of BMGL.BMGL_BKDW
	 * 
	 * @mbggenerated
	 */
	public String getBmglBkdw()
	{
		return bmglBkdw;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column BMGL.BMGL_BKDW
	 * 
	 * @param bmglBkdw
	 *            the value for BMGL.BMGL_BKDW
	 * 
	 * @mbggenerated
	 */
	public void setBmglBkdw(String bmglBkdw)
	{
		this.bmglBkdw = bmglBkdw;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column BMGL.BMGL_BKGW
	 * 
	 * @return the value of BMGL.BMGL_BKGW
	 * 
	 * @mbggenerated
	 */
	public String getBmglBkgw()
	{
		return bmglBkgw;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column BMGL.BMGL_BKGW
	 * 
	 * @param bmglBkgw
	 *            the value for BMGL.BMGL_BKGW
	 * 
	 * @mbggenerated
	 */
	public void setBmglBkgw(String bmglBkgw)
	{
		this.bmglBkgw = bmglBkgw;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column BMGL.BMGL_BYXX
	 * 
	 * @return the value of BMGL.BMGL_BYXX
	 * 
	 * @mbggenerated
	 */
	public String getBmglByxx()
	{
		return bmglByxx;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column BMGL.BMGL_BYXX
	 * 
	 * @param bmglByxx
	 *            the value for BMGL.BMGL_BYXX
	 * 
	 * @mbggenerated
	 */
	public void setBmglByxx(String bmglByxx)
	{
		this.bmglByxx = bmglByxx;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column BMGL.BMGL_KSRQ
	 * 
	 * @return the value of BMGL.BMGL_KSRQ
	 * 
	 * @mbggenerated
	 */
	public Date getBmglKsrq()
	{
		return bmglKsrq;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column BMGL.BMGL_KSRQ
	 * 
	 * @param bmglKsrq
	 *            the value for BMGL.BMGL_KSRQ
	 * 
	 * @mbggenerated
	 */
	public void setBmglKsrq(Date bmglKsrq)
	{
		this.bmglKsrq = bmglKsrq;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column BMGL.BMGL_KSSJ
	 * 
	 * @return the value of BMGL.BMGL_KSSJ
	 * 
	 * @mbggenerated
	 */
	public String getBmglKssj()
	{
		return bmglKssj;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column BMGL.BMGL_KSSJ
	 * 
	 * @param bmglKssj
	 *            the value for BMGL.BMGL_KSSJ
	 * 
	 * @mbggenerated
	 */
	public void setBmglKssj(String bmglKssj)
	{
		this.bmglKssj = bmglKssj;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column BMGL.BMGL_SFQR
	 * 
	 * @return the value of BMGL.BMGL_SFQR
	 * 
	 * @mbggenerated
	 */
	public String getBmglSfqr()
	{
		return bmglSfqr;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column BMGL.BMGL_SFQR
	 * 
	 * @param bmglSfqr
	 *            the value for BMGL.BMGL_SFQR
	 * 
	 * @mbggenerated
	 */
	public void setBmglSfqr(String bmglSfqr)
	{
		this.bmglSfqr = bmglSfqr;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column BMGL.BMGL_LXDH
	 * 
	 * @return the value of BMGL.BMGL_LXDH
	 * 
	 * @mbggenerated
	 */
	public Long getBmglLxdh()
	{
		return bmglLxdh;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column BMGL.BMGL_LXDH
	 * 
	 * @param bmglLxdh
	 *            the value for BMGL.BMGL_LXDH
	 * 
	 * @mbggenerated
	 */
	public void setBmglLxdh(Long bmglLxdh)
	{
		this.bmglLxdh = bmglLxdh;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column BMGL.BMGL_ADDTIME
	 * 
	 * @return the value of BMGL.BMGL_ADDTIME
	 * 
	 * @mbggenerated
	 */
	public Date getBmglAddtime()
	{
		return bmglAddtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column BMGL.BMGL_ADDTIME
	 * 
	 * @param bmglAddtime
	 *            the value for BMGL.BMGL_ADDTIME
	 * 
	 * @mbggenerated
	 */
	public void setBmglAddtime(Date bmglAddtime)
	{
		this.bmglAddtime = bmglAddtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column BMGL.BMGL_DELFLAG
	 * 
	 * @return the value of BMGL.BMGL_DELFLAG
	 * 
	 * @mbggenerated
	 */
	public Long getBmglDelflag()
	{
		return bmglDelflag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column BMGL.BMGL_DELFLAG
	 * 
	 * @param bmglDelflag
	 *            the value for BMGL.BMGL_DELFLAG
	 * 
	 * @mbggenerated
	 */
	public void setBmglDelflag(Long bmglDelflag)
	{
		this.bmglDelflag = bmglDelflag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column BMGL.BMGL_KSCJ
	 * 
	 * @return the value of BMGL.BMGL_KSCJ
	 * 
	 * @mbggenerated
	 */
	public String getBmglKscj()
	{
		return bmglKscj;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column BMGL.BMGL_KSCJ
	 * 
	 * @param bmglKscj
	 *            the value for BMGL.BMGL_KSCJ
	 * 
	 * @mbggenerated
	 */
	public void setBmglKscj(String bmglKscj)
	{
		this.bmglKscj = bmglKscj;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column BMGL.BMGL_TSZG
	 * 
	 * @return the value of BMGL.BMGL_TSZG
	 * 
	 * @mbggenerated
	 */
	public String getBmglTszg()
	{
		return bmglTszg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column BMGL.BMGL_TSZG
	 * 
	 * @param bmglTszg
	 *            the value for BMGL.BMGL_TSZG
	 * 
	 * @mbggenerated
	 */
	public void setBmglTszg(String bmglTszg)
	{
		this.bmglTszg = bmglTszg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column BMGL.BMGL_SFZH
	 * 
	 * @return the value of BMGL.BMGL_SFZH
	 * 
	 * @mbggenerated
	 */
	public String getBmglSfzh()
	{
		return bmglSfzh;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column BMGL.BMGL_SFZH
	 * 
	 * @param bmglSfzh
	 *            the value for BMGL.BMGL_SFZH
	 * 
	 * @mbggenerated
	 */
	public void setBmglSfzh(String bmglSfzh)
	{
		this.bmglSfzh = bmglSfzh;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column BMGL.BMGL_JTJLKID
	 * 
	 * @return the value of BMGL.BMGL_JTJLKID
	 * 
	 * @mbggenerated
	 */
	public String getBmglJtjlkid()
	{
		return bmglJtjlkid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column BMGL.BMGL_JTJLKID
	 * 
	 * @param bmglJtjlkid
	 *            the value for BMGL.BMGL_JTJLKID
	 * 
	 * @mbggenerated
	 */
	public void setBmglJtjlkid(String bmglJtjlkid)
	{
		this.bmglJtjlkid = bmglJtjlkid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column BMGL.BMGL_BKDWDM
	 * 
	 * @return the value of BMGL.BMGL_BKDWDM
	 * 
	 * @mbggenerated
	 */
	public String getBmglBkdwdm()
	{
		return bmglBkdwdm;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column BMGL.BMGL_BKDWDM
	 * 
	 * @param bmglBkdwdm
	 *            the value for BMGL.BMGL_BKDWDM
	 * 
	 * @mbggenerated
	 */
	public void setBmglBkdwdm(String bmglBkdwdm)
	{
		this.bmglBkdwdm = bmglBkdwdm;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column BMGL.BMGL_KSXB
	 * 
	 * @return the value of BMGL.BMGL_KSXB
	 * 
	 * @mbggenerated
	 */
	public String getBmglKsxb()
	{
		return bmglKsxb;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column BMGL.BMGL_KSXB
	 * 
	 * @param bmglKsxb
	 *            the value for BMGL.BMGL_KSXB
	 * 
	 * @mbggenerated
	 */
	public void setBmglKsxb(String bmglKsxb)
	{
		this.bmglKsxb = bmglKsxb;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column BMGL.BMGL_KSDD
	 * 
	 * @return the value of BMGL.BMGL_KSDD
	 * 
	 * @mbggenerated
	 */
	public String getBmglKsdd()
	{
		return bmglKsdd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column BMGL.BMGL_KSDD
	 * 
	 * @param bmglKsdd
	 *            the value for BMGL.BMGL_KSDD
	 * 
	 * @mbggenerated
	 */
	public void setBmglKsdd(String bmglKsdd)
	{
		this.bmglKsdd = bmglKsdd;
	}

	public String getBmglKcmc()
	{
		return bmglKcmc;
	}

	public void setBmglKcmc(String bmglKcmc)
	{
		this.bmglKcmc = bmglKcmc;
	}
}