package com.ttgis.recruit.domain;

import java.io.Serializable;
import java.util.Date;

public class Cjtsgl implements Serializable
{
	/**
	 * 
	 */
	private static final long serialVersionUID = -8697837873828273833L;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column CJTSGL.CJTSGL_ID
	 * 
	 * @mbggenerated
	 */
	private String cjtsglId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column CJTSGL.CJTSGL_TSFS
	 * 
	 * @mbggenerated
	 */
	private String cjtsglTsfs;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column CJTSGL.CJTSGL_TSYSSJ
	 * 
	 * @mbggenerated
	 */
	private Integer cjtsglTsyssj;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column CJTSGL.CJTSGL_ADDTIME
	 * 
	 * @mbggenerated
	 */
	private Date cjtsglAddtime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column CJTSGL.CJTSGL_DELFLAG
	 * 
	 * @mbggenerated
	 */
	private Long cjtsglDelflag;

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column CJTSGL.CJTSGL_ID
	 * 
	 * @return the value of CJTSGL.CJTSGL_ID
	 * 
	 * @mbggenerated
	 */
	public String getCjtsglId()
	{
		return cjtsglId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column CJTSGL.CJTSGL_ID
	 * 
	 * @param cjtsglId
	 *            the value for CJTSGL.CJTSGL_ID
	 * 
	 * @mbggenerated
	 */
	public void setCjtsglId(String cjtsglId)
	{
		this.cjtsglId = cjtsglId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column CJTSGL.CJTSGL_TSFS
	 * 
	 * @return the value of CJTSGL.CJTSGL_TSFS
	 * 
	 * @mbggenerated
	 */
	public String getCjtsglTsfs()
	{
		return cjtsglTsfs;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column CJTSGL.CJTSGL_TSFS
	 * 
	 * @param cjtsglTsfs
	 *            the value for CJTSGL.CJTSGL_TSFS
	 * 
	 * @mbggenerated
	 */
	public void setCjtsglTsfs(String cjtsglTsfs)
	{
		this.cjtsglTsfs = cjtsglTsfs;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column CJTSGL.CJTSGL_TSYSSJ
	 * 
	 * @return the value of CJTSGL.CJTSGL_TSYSSJ
	 * 
	 * @mbggenerated
	 */
	public Integer getCjtsglTsyssj()
	{
		return cjtsglTsyssj;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column CJTSGL.CJTSGL_TSYSSJ
	 * 
	 * @param cjtsglTsyssj
	 *            the value for CJTSGL.CJTSGL_TSYSSJ
	 * 
	 * @mbggenerated
	 */
	public void setCjtsglTsyssj(Integer cjtsglTsyssj)
	{
		this.cjtsglTsyssj = cjtsglTsyssj;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column CJTSGL.CJTSGL_ADDTIME
	 * 
	 * @return the value of CJTSGL.CJTSGL_ADDTIME
	 * 
	 * @mbggenerated
	 */
	public Date getCjtsglAddtime()
	{
		return cjtsglAddtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column CJTSGL.CJTSGL_ADDTIME
	 * 
	 * @param cjtsglAddtime
	 *            the value for CJTSGL.CJTSGL_ADDTIME
	 * 
	 * @mbggenerated
	 */
	public void setCjtsglAddtime(Date cjtsglAddtime)
	{
		this.cjtsglAddtime = cjtsglAddtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column CJTSGL.CJTSGL_DELFLAG
	 * 
	 * @return the value of CJTSGL.CJTSGL_DELFLAG
	 * 
	 * @mbggenerated
	 */
	public Long getCjtsglDelflag()
	{
		return cjtsglDelflag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column CJTSGL.CJTSGL_DELFLAG
	 * 
	 * @param cjtsglDelflag
	 *            the value for CJTSGL.CJTSGL_DELFLAG
	 * 
	 * @mbggenerated
	 */
	public void setCjtsglDelflag(Long cjtsglDelflag)
	{
		this.cjtsglDelflag = cjtsglDelflag;
	}
}