package com.ttgis.recruit.domain;

import java.io.Serializable;
import java.util.Date;

public class Collect_position implements Serializable
{
	/**
	 * 
	 */
	private static final long serialVersionUID = -4963142478275697069L;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column COLLECT_POSITION.COLLECT_POSITION_ID
	 * 
	 * @mbggenerated
	 */
	private String collectPositionId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column COLLECT_POSITION.POSITION_ID
	 * 
	 * @mbggenerated
	 */
	private String positionId;
	private String positionName;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column COLLECT_POSITION.COLLECT_POSITION_USER_ID
	 * 
	 * @mbggenerated
	 */
	private String collectPositionUserId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column COLLECT_POSITION.COLLECT_POSITION_ADDTIME
	 * 
	 * @mbggenerated
	 */
	private Date collectPositionAddtime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column COLLECT_POSITION.COLLECT_POSITION_DELFLAG
	 * 
	 * @mbggenerated
	 */
	private Long collectPositionDelflag;

	public String getPositionName()
	{
		return positionName;
	}

	public void setPositionName(String positionName)
	{
		this.positionName = positionName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column COLLECT_POSITION.COLLECT_POSITION_ID
	 * 
	 * @return the value of COLLECT_POSITION.COLLECT_POSITION_ID
	 * 
	 * @mbggenerated
	 */
	public String getCollectPositionId()
	{
		return collectPositionId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column COLLECT_POSITION.COLLECT_POSITION_ID
	 * 
	 * @param collectPositionId
	 *            the value for COLLECT_POSITION.COLLECT_POSITION_ID
	 * 
	 * @mbggenerated
	 */
	public void setCollectPositionId(String collectPositionId)
	{
		this.collectPositionId = collectPositionId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column COLLECT_POSITION.POSITION_ID
	 * 
	 * @return the value of COLLECT_POSITION.POSITION_ID
	 * 
	 * @mbggenerated
	 */
	public String getPositionId()
	{
		return positionId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column COLLECT_POSITION.POSITION_ID
	 * 
	 * @param positionId
	 *            the value for COLLECT_POSITION.POSITION_ID
	 * 
	 * @mbggenerated
	 */
	public void setPositionId(String positionId)
	{
		this.positionId = positionId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column COLLECT_POSITION.COLLECT_POSITION_USER_ID
	 * 
	 * @return the value of COLLECT_POSITION.COLLECT_POSITION_USER_ID
	 * 
	 * @mbggenerated
	 */
	public String getCollectPositionUserId()
	{
		return collectPositionUserId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column COLLECT_POSITION.COLLECT_POSITION_USER_ID
	 * 
	 * @param collectPositionUserId
	 *            the value for COLLECT_POSITION.COLLECT_POSITION_USER_ID
	 * 
	 * @mbggenerated
	 */
	public void setCollectPositionUserId(String collectPositionUserId)
	{
		this.collectPositionUserId = collectPositionUserId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column COLLECT_POSITION.COLLECT_POSITION_ADDTIME
	 * 
	 * @return the value of COLLECT_POSITION.COLLECT_POSITION_ADDTIME
	 * 
	 * @mbggenerated
	 */
	public Date getCollectPositionAddtime()
	{
		return collectPositionAddtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column COLLECT_POSITION.COLLECT_POSITION_ADDTIME
	 * 
	 * @param collectPositionAddtime
	 *            the value for COLLECT_POSITION.COLLECT_POSITION_ADDTIME
	 * 
	 * @mbggenerated
	 */
	public void setCollectPositionAddtime(Date collectPositionAddtime)
	{
		this.collectPositionAddtime = collectPositionAddtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column COLLECT_POSITION.COLLECT_POSITION_DELFLAG
	 * 
	 * @return the value of COLLECT_POSITION.COLLECT_POSITION_DELFLAG
	 * 
	 * @mbggenerated
	 */
	public Long getCollectPositionDelflag()
	{
		return collectPositionDelflag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column COLLECT_POSITION.COLLECT_POSITION_DELFLAG
	 * 
	 * @param collectPositionDelflag
	 *            the value for COLLECT_POSITION.COLLECT_POSITION_DELFLAG
	 * 
	 * @mbggenerated
	 */
	public void setCollectPositionDelflag(Long collectPositionDelflag)
	{
		this.collectPositionDelflag = collectPositionDelflag;
	}
}