package com.ttgis.recruit.domain;

import java.io.Serializable;
import java.util.Date;

public class Cpfygl implements Serializable
{
	/**
	 * 
	 */
	private static final long serialVersionUID = 1375506722831041753L;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column CPFYGL.CPFYGL_ID
	 * 
	 * @mbggenerated
	 */
	private String cpfyglId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column CPFYGL.ZZJG_ID
	 * 
	 * @mbggenerated
	 */
	private String zzjgId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column CPFYGL.CPFYGL_ORG
	 * 
	 * @mbggenerated
	 */
	private String cpfyglOrg;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column CPFYGL.CPFYGL_DEP
	 * 
	 * @mbggenerated
	 */
	private String cpfyglDep;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column CPFYGL.CPFYGL_DWDM
	 * 
	 * @mbggenerated
	 */
	private String cpfyglDwdm;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column CPFYGL.CPFYGL_DWMC
	 * 
	 * @mbggenerated
	 */
	private String cpfyglDwmc;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column CPFYGL.CPFYGL_NDYFFZ
	 * 
	 * @mbggenerated
	 */
	private Long cpfyglNdyffz;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column CPFYGL.CPFYGL_SYCPCS
	 * 
	 * @mbggenerated
	 */
	private Long cpfyglSycpcs;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column CPFYGL.CPFYGL_ADDTIME
	 * 
	 * @mbggenerated
	 */
	private Date cpfyglAddtime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column CPFYGL.CPFYGL_DELFLAG
	 * 
	 * @mbggenerated
	 */
	private Long cpfyglDelflag;

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column CPFYGL.CPFYGL_ID
	 * 
	 * @return the value of CPFYGL.CPFYGL_ID
	 * 
	 * @mbggenerated
	 */
	public String getCpfyglId()
	{
		return cpfyglId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column CPFYGL.CPFYGL_ID
	 * 
	 * @param cpfyglId
	 *            the value for CPFYGL.CPFYGL_ID
	 * 
	 * @mbggenerated
	 */
	public void setCpfyglId(String cpfyglId)
	{
		this.cpfyglId = cpfyglId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column CPFYGL.ZZJG_ID
	 * 
	 * @return the value of CPFYGL.ZZJG_ID
	 * 
	 * @mbggenerated
	 */
	public String getZzjgId()
	{
		return zzjgId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column CPFYGL.ZZJG_ID
	 * 
	 * @param zzjgId
	 *            the value for CPFYGL.ZZJG_ID
	 * 
	 * @mbggenerated
	 */
	public void setZzjgId(String zzjgId)
	{
		this.zzjgId = zzjgId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column CPFYGL.CPFYGL_ORG
	 * 
	 * @return the value of CPFYGL.CPFYGL_ORG
	 * 
	 * @mbggenerated
	 */
	public String getCpfyglOrg()
	{
		return cpfyglOrg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column CPFYGL.CPFYGL_ORG
	 * 
	 * @param cpfyglOrg
	 *            the value for CPFYGL.CPFYGL_ORG
	 * 
	 * @mbggenerated
	 */
	public void setCpfyglOrg(String cpfyglOrg)
	{
		this.cpfyglOrg = cpfyglOrg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column CPFYGL.CPFYGL_DEP
	 * 
	 * @return the value of CPFYGL.CPFYGL_DEP
	 * 
	 * @mbggenerated
	 */
	public String getCpfyglDep()
	{
		return cpfyglDep;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column CPFYGL.CPFYGL_DEP
	 * 
	 * @param cpfyglDep
	 *            the value for CPFYGL.CPFYGL_DEP
	 * 
	 * @mbggenerated
	 */
	public void setCpfyglDep(String cpfyglDep)
	{
		this.cpfyglDep = cpfyglDep;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column CPFYGL.CPFYGL_DWDM
	 * 
	 * @return the value of CPFYGL.CPFYGL_DWDM
	 * 
	 * @mbggenerated
	 */
	public String getCpfyglDwdm()
	{
		return cpfyglDwdm;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column CPFYGL.CPFYGL_DWDM
	 * 
	 * @param cpfyglDwdm
	 *            the value for CPFYGL.CPFYGL_DWDM
	 * 
	 * @mbggenerated
	 */
	public void setCpfyglDwdm(String cpfyglDwdm)
	{
		this.cpfyglDwdm = cpfyglDwdm;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column CPFYGL.CPFYGL_DWMC
	 * 
	 * @return the value of CPFYGL.CPFYGL_DWMC
	 * 
	 * @mbggenerated
	 */
	public String getCpfyglDwmc()
	{
		return cpfyglDwmc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column CPFYGL.CPFYGL_DWMC
	 * 
	 * @param cpfyglDwmc
	 *            the value for CPFYGL.CPFYGL_DWMC
	 * 
	 * @mbggenerated
	 */
	public void setCpfyglDwmc(String cpfyglDwmc)
	{
		this.cpfyglDwmc = cpfyglDwmc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column CPFYGL.CPFYGL_NDYFFZ
	 * 
	 * @return the value of CPFYGL.CPFYGL_NDYFFZ
	 * 
	 * @mbggenerated
	 */
	public Long getCpfyglNdyffz()
	{
		return cpfyglNdyffz;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column CPFYGL.CPFYGL_NDYFFZ
	 * 
	 * @param cpfyglNdyffz
	 *            the value for CPFYGL.CPFYGL_NDYFFZ
	 * 
	 * @mbggenerated
	 */
	public void setCpfyglNdyffz(Long cpfyglNdyffz)
	{
		this.cpfyglNdyffz = cpfyglNdyffz;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column CPFYGL.CPFYGL_SYCPCS
	 * 
	 * @return the value of CPFYGL.CPFYGL_SYCPCS
	 * 
	 * @mbggenerated
	 */
	public Long getCpfyglSycpcs()
	{
		return cpfyglSycpcs;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column CPFYGL.CPFYGL_SYCPCS
	 * 
	 * @param cpfyglSycpcs
	 *            the value for CPFYGL.CPFYGL_SYCPCS
	 * 
	 * @mbggenerated
	 */
	public void setCpfyglSycpcs(Long cpfyglSycpcs)
	{
		this.cpfyglSycpcs = cpfyglSycpcs;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column CPFYGL.CPFYGL_ADDTIME
	 * 
	 * @return the value of CPFYGL.CPFYGL_ADDTIME
	 * 
	 * @mbggenerated
	 */
	public Date getCpfyglAddtime()
	{
		return cpfyglAddtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column CPFYGL.CPFYGL_ADDTIME
	 * 
	 * @param cpfyglAddtime
	 *            the value for CPFYGL.CPFYGL_ADDTIME
	 * 
	 * @mbggenerated
	 */
	public void setCpfyglAddtime(Date cpfyglAddtime)
	{
		this.cpfyglAddtime = cpfyglAddtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column CPFYGL.CPFYGL_DELFLAG
	 * 
	 * @return the value of CPFYGL.CPFYGL_DELFLAG
	 * 
	 * @mbggenerated
	 */
	public Long getCpfyglDelflag()
	{
		return cpfyglDelflag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column CPFYGL.CPFYGL_DELFLAG
	 * 
	 * @param cpfyglDelflag
	 *            the value for CPFYGL.CPFYGL_DELFLAG
	 * 
	 * @mbggenerated
	 */
	public void setCpfyglDelflag(Long cpfyglDelflag)
	{
		this.cpfyglDelflag = cpfyglDelflag;
	}
}