package com.ttgis.recruit.domain;

import java.io.Serializable;

public class Hydj implements Serializable
{
	private static final long serialVersionUID = 8596298431690097463L;

	private String hydjCpdj;

	public String getHydjCpdj()
	{
		return hydjCpdj;
	}

	public void setHydjCpdj(String hydjCpdj)
	{
		this.hydjCpdj = hydjCpdj;
	}

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column HYDJ.HYDJ_ID
	 * 
	 * @mbggenerated
	 */
	private String hydjId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column HYDJ.HYDJ_FY
	 * 
	 * @mbggenerated
	 */
	private String hydjFy;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column HYDJ.HYDJ_CPCS
	 * 
	 * @mbggenerated
	 */
	private String hydjCpcs;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column HYDJ.HYDJ_DELFLAG
	 * 
	 * @mbggenerated
	 */
	private String hydjName;

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column HYDJ.HYDJ_ID
	 * 
	 * @return the value of HYDJ.HYDJ_ID
	 * 
	 * @mbggenerated
	 */
	public String getHydjId()
	{
		return hydjId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column HYDJ.HYDJ_ID
	 * 
	 * @param hydjId
	 *            the value for HYDJ.HYDJ_ID
	 * 
	 * @mbggenerated
	 */
	public void setHydjId(String hydjId)
	{
		this.hydjId = hydjId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column HYDJ.HYDJ_FY
	 * 
	 * @return the value of HYDJ.HYDJ_FY
	 * 
	 * @mbggenerated
	 */
	public String getHydjFy()
	{
		return hydjFy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column HYDJ.HYDJ_FY
	 * 
	 * @param hydjFy
	 *            the value for HYDJ.HYDJ_FY
	 * 
	 * @mbggenerated
	 */
	public void setHydjFy(String hydjFy)
	{
		this.hydjFy = hydjFy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column HYDJ.HYDJ_CPCS
	 * 
	 * @return the value of HYDJ.HYDJ_CPCS
	 * 
	 * @mbggenerated
	 */
	public String getHydjCpcs()
	{
		return hydjCpcs;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column HYDJ.HYDJ_CPCS
	 * 
	 * @param hydjCpcs
	 *            the value for HYDJ.HYDJ_CPCS
	 * 
	 * @mbggenerated
	 */
	public void setHydjCpcs(String hydjCpcs)
	{
		this.hydjCpcs = hydjCpcs;
	}

	public String getHydjName()
	{
		return hydjName;
	}

	public void setHydjName(String hydjName)
	{
		this.hydjName = hydjName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column HYDJ.HYDJ_DELFLAG
	 * 
	 * @return the value of HYDJ.HYDJ_DELFLAG
	 * 
	 * @mbggenerated
	 */
}