package com.ttgis.recruit.domain;

import java.io.Serializable;
import java.util.Date;

public class Jk implements Serializable
{

	private static final long serialVersionUID = -7757278317415661189L;

	private String tjsj;

	public String getTjsj()
	{
		return tjsj;
	}

	public void setTjsj(String tjsj)
	{
		this.tjsj = tjsj;
	}

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column JK.JK_ID
	 * 
	 * @mbggenerated
	 */
	private String jkId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column JK.JK_NAME
	 * 
	 * @mbggenerated
	 */
	private String jkName;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column JK.JK_ADDTIME
	 * 
	 * @mbggenerated
	 */
	private Date jkAddtime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column JK.JK_ID
	 * 
	 * @return the value of JK.JK_ID
	 * 
	 * @mbggenerated
	 */
	public String getJkId()
	{
		return jkId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column JK.JK_ID
	 * 
	 * @param jkId
	 *            the value for JK.JK_ID
	 * 
	 * @mbggenerated
	 */
	public void setJkId(String jkId)
	{
		this.jkId = jkId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column JK.JK_NAME
	 * 
	 * @return the value of JK.JK_NAME
	 * 
	 * @mbggenerated
	 */
	public String getJkName()
	{
		return jkName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column JK.JK_NAME
	 * 
	 * @param jkName
	 *            the value for JK.JK_NAME
	 * 
	 * @mbggenerated
	 */
	public void setJkName(String jkName)
	{
		this.jkName = jkName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column JK.JK_ADDTIME
	 * 
	 * @return the value of JK.JK_ADDTIME
	 * 
	 * @mbggenerated
	 */
	public Date getJkAddtime()
	{
		return jkAddtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column JK.JK_ADDTIME
	 * 
	 * @param jkAddtime
	 *            the value for JK.JK_ADDTIME
	 * 
	 * @mbggenerated
	 */
	public void setJkAddtime(Date jkAddtime)
	{
		this.jkAddtime = jkAddtime;
	}
}