package com.ttgis.recruit.domain;

public class JkglFxtWithBLOBs extends JkglFxt
{

	/**
	 * 
	 */
	private static final long serialVersionUID = -160266502752057860L;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column JKGL_FXT.STTG
	 * 
	 * @mbggenerated
	 */
	private String sttg;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column JKGL_FXT.STXXA
	 * 
	 * @mbggenerated
	 */
	private String stxxa;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column JKGL_FXT.STXXB
	 * 
	 * @mbggenerated
	 */
	private String stxxb;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column JKGL_FXT.STXXC
	 * 
	 * @mbggenerated
	 */
	private String stxxc;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column JKGL_FXT.STXXD
	 * 
	 * @mbggenerated
	 */
	private String stxxd;

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column JKGL_FXT.STTG
	 * 
	 * @return the value of JKGL_FXT.STTG
	 * 
	 * @mbggenerated
	 */
	public String getSttg()
	{
		return sttg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column JKGL_FXT.STTG
	 * 
	 * @param sttg
	 *            the value for JKGL_FXT.STTG
	 * 
	 * @mbggenerated
	 */
	public void setSttg(String sttg)
	{
		this.sttg = sttg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column JKGL_FXT.STXXA
	 * 
	 * @return the value of JKGL_FXT.STXXA
	 * 
	 * @mbggenerated
	 */
	public String getStxxa()
	{
		return stxxa;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column JKGL_FXT.STXXA
	 * 
	 * @param stxxa
	 *            the value for JKGL_FXT.STXXA
	 * 
	 * @mbggenerated
	 */
	public void setStxxa(String stxxa)
	{
		this.stxxa = stxxa;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column JKGL_FXT.STXXB
	 * 
	 * @return the value of JKGL_FXT.STXXB
	 * 
	 * @mbggenerated
	 */
	public String getStxxb()
	{
		return stxxb;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column JKGL_FXT.STXXB
	 * 
	 * @param stxxb
	 *            the value for JKGL_FXT.STXXB
	 * 
	 * @mbggenerated
	 */
	public void setStxxb(String stxxb)
	{
		this.stxxb = stxxb;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column JKGL_FXT.STXXC
	 * 
	 * @return the value of JKGL_FXT.STXXC
	 * 
	 * @mbggenerated
	 */
	public String getStxxc()
	{
		return stxxc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column JKGL_FXT.STXXC
	 * 
	 * @param stxxc
	 *            the value for JKGL_FXT.STXXC
	 * 
	 * @mbggenerated
	 */
	public void setStxxc(String stxxc)
	{
		this.stxxc = stxxc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column JKGL_FXT.STXXD
	 * 
	 * @return the value of JKGL_FXT.STXXD
	 * 
	 * @mbggenerated
	 */
	public String getStxxd()
	{
		return stxxd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column JKGL_FXT.STXXD
	 * 
	 * @param stxxd
	 *            the value for JKGL_FXT.STXXD
	 * 
	 * @mbggenerated
	 */
	public void setStxxd(String stxxd)
	{
		this.stxxd = stxxd;
	}
}