package com.ttgis.recruit.domain;

import java.io.Serializable;

public class JkglFxt implements Serializable
{
	private static final long serialVersionUID = -6391353322167176500L;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column JKGL_FXT.ID
	 * 
	 * @mbggenerated
	 */
	private String id;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column JKGL_FXT.STBH
	 * 
	 * @mbggenerated
	 */
	private String stbh;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column JKGL_FXT.STLX
	 * 
	 * @mbggenerated
	 */
	private String stlx;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column JKGL_FXT.STDA
	 * 
	 * @mbggenerated
	 */
	private String stda;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column JKGL_FXT.sjbh
	 * 
	 * @mbggenerated
	 */
	private String sjbh;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column JKGL_FXT.STATUS2
	 * 
	 * @mbggenerated
	 */
	private String status2;

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column JKGL_FXT.ID
	 * 
	 * @return the value of JKGL_FXT.ID
	 * 
	 * @mbggenerated
	 */
	public String getId()
	{
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column JKGL_FXT.ID
	 * 
	 * @param id
	 *            the value for JKGL_FXT.ID
	 * 
	 * @mbggenerated
	 */
	public void setId(String id)
	{
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column JKGL_FXT.STBH
	 * 
	 * @return the value of JKGL_FXT.STBH
	 * 
	 * @mbggenerated
	 */
	public String getStbh()
	{
		return stbh;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column JKGL_FXT.STBH
	 * 
	 * @param stbh
	 *            the value for JKGL_FXT.STBH
	 * 
	 * @mbggenerated
	 */
	public void setStbh(String stbh)
	{
		this.stbh = stbh;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column JKGL_FXT.STLX
	 * 
	 * @return the value of JKGL_FXT.STLX
	 * 
	 * @mbggenerated
	 */
	public String getStlx()
	{
		return stlx;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column JKGL_FXT.STLX
	 * 
	 * @param stlx
	 *            the value for JKGL_FXT.STLX
	 * 
	 * @mbggenerated
	 */
	public void setStlx(String stlx)
	{
		this.stlx = stlx;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column JKGL_FXT.STDA
	 * 
	 * @return the value of JKGL_FXT.STDA
	 * 
	 * @mbggenerated
	 */
	public String getStda()
	{
		return stda;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column JKGL_FXT.STDA
	 * 
	 * @param stda
	 *            the value for JKGL_FXT.STDA
	 * 
	 * @mbggenerated
	 */
	public void setStda(String stda)
	{
		this.stda = stda;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column JKGL_FXT.sjbh
	 * 
	 * @return the value of JKGL_FXT.sjbh
	 * 
	 * @mbggenerated
	 */

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column JKGL_FXT.STATUS2
	 * 
	 * @return the value of JKGL_FXT.STATUS2
	 * 
	 * @mbggenerated
	 */
	public String getStatus2()
	{
		return status2;
	}

	public String getSjbh()
	{
		return sjbh;
	}

	public void setSjbh(String sjbh)
	{
		this.sjbh = sjbh;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column JKGL_FXT.STATUS2
	 * 
	 * @param status2
	 *            the value for JKGL_FXT.STATUS2
	 * 
	 * @mbggenerated
	 */
	public void setStatus2(String status2)
	{
		this.status2 = status2;
	}
}