package com.ttgis.recruit.domain;

import java.io.Serializable;

public class Jkgl implements Serializable
{
	private static final long serialVersionUID = -787366999700947330L;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column JKGL.JKGL_ID
	 * 
	 * @mbggenerated
	 */
	private String jkglId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column JKGL.JKGL_STBH
	 * 
	 * @mbggenerated
	 */
	private String jkglStbh;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column JKGL.JKGL_STLX
	 * 
	 * @mbggenerated
	 */
	private String jkglStlx;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column JKGL.JKGL_STDA
	 * 
	 * @mbggenerated
	 */
	private String jkglStda;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column JKGL.JKGL_SJBH
	 * 
	 * @mbggenerated
	 */
	private String jkglSjbh;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column JKGL.STATUS1
	 * 
	 * @mbggenerated
	 */
	private String status1;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column JKGL.STATUS2
	 * 
	 * @mbggenerated
	 */
	private String status2;

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column JKGL.JKGL_ID
	 * 
	 * @return the value of JKGL.JKGL_ID
	 * 
	 * @mbggenerated
	 */
	public String getJkglId()
	{
		return jkglId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column JKGL.JKGL_ID
	 * 
	 * @param jkglId
	 *            the value for JKGL.JKGL_ID
	 * 
	 * @mbggenerated
	 */
	public void setJkglId(String jkglId)
	{
		this.jkglId = jkglId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column JKGL.JKGL_STBH
	 * 
	 * @return the value of JKGL.JKGL_STBH
	 * 
	 * @mbggenerated
	 */
	public String getJkglStbh()
	{
		return jkglStbh;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column JKGL.JKGL_STBH
	 * 
	 * @param jkglStbh
	 *            the value for JKGL.JKGL_STBH
	 * 
	 * @mbggenerated
	 */
	public void setJkglStbh(String jkglStbh)
	{
		this.jkglStbh = jkglStbh;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column JKGL.JKGL_STLX
	 * 
	 * @return the value of JKGL.JKGL_STLX
	 * 
	 * @mbggenerated
	 */
	public String getJkglStlx()
	{
		return jkglStlx;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column JKGL.JKGL_STLX
	 * 
	 * @param jkglStlx
	 *            the value for JKGL.JKGL_STLX
	 * 
	 * @mbggenerated
	 */
	public void setJkglStlx(String jkglStlx)
	{
		this.jkglStlx = jkglStlx;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column JKGL.JKGL_STDA
	 * 
	 * @return the value of JKGL.JKGL_STDA
	 * 
	 * @mbggenerated
	 */
	public String getJkglStda()
	{
		return jkglStda;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column JKGL.JKGL_STDA
	 * 
	 * @param jkglStda
	 *            the value for JKGL.JKGL_STDA
	 * 
	 * @mbggenerated
	 */
	public void setJkglStda(String jkglStda)
	{
		this.jkglStda = jkglStda;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column JKGL.JKGL_SJBH
	 * 
	 * @return the value of JKGL.JKGL_SJBH
	 * 
	 * @mbggenerated
	 */
	public String getJkglSjbh()
	{
		return jkglSjbh;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column JKGL.JKGL_SJBH
	 * 
	 * @param jkglSjbh
	 *            the value for JKGL.JKGL_SJBH
	 * 
	 * @mbggenerated
	 */
	public void setJkglSjbh(String jkglSjbh)
	{
		this.jkglSjbh = jkglSjbh;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column JKGL.STATUS1
	 * 
	 * @return the value of JKGL.STATUS1
	 * 
	 * @mbggenerated
	 */
	public String getStatus1()
	{
		return status1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column JKGL.STATUS1
	 * 
	 * @param status1
	 *            the value for JKGL.STATUS1
	 * 
	 * @mbggenerated
	 */
	public void setStatus1(String status1)
	{
		this.status1 = status1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column JKGL.STATUS2
	 * 
	 * @return the value of JKGL.STATUS2
	 * 
	 * @mbggenerated
	 */
	public String getStatus2()
	{
		return status2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column JKGL.STATUS2
	 * 
	 * @param status2
	 *            the value for JKGL.STATUS2
	 * 
	 * @mbggenerated
	 */
	public void setStatus2(String status2)
	{
		this.status2 = status2;
	}
}