package com.ttgis.recruit.domain;

public class JkglWithBLOBs extends Jkgl
{

	/**
	 * 
	 */
	private static final long serialVersionUID = -7001735547701431685L;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column JKGL.JKGL_STTG
	 * 
	 * @mbggenerated
	 */
	private String jkglSttg;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column JKGL.JKGL_STXXA
	 * 
	 * @mbggenerated
	 */
	private String jkglStxxa;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column JKGL.JKGL_STXXB
	 * 
	 * @mbggenerated
	 */
	private String jkglStxxb;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column JKGL.JKGL_STXXC
	 * 
	 * @mbggenerated
	 */
	private String jkglStxxc;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column JKGL.JKGL_STXXD
	 * 
	 * @mbggenerated
	 */
	private String jkglStxxd;

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column JKGL.JKGL_STTG
	 * 
	 * @return the value of JKGL.JKGL_STTG
	 * 
	 * @mbggenerated
	 */
	public String getJkglSttg()
	{
		return jkglSttg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column JKGL.JKGL_STTG
	 * 
	 * @param jkglSttg
	 *            the value for JKGL.JKGL_STTG
	 * 
	 * @mbggenerated
	 */
	public void setJkglSttg(String jkglSttg)
	{
		this.jkglSttg = jkglSttg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column JKGL.JKGL_STXXA
	 * 
	 * @return the value of JKGL.JKGL_STXXA
	 * 
	 * @mbggenerated
	 */
	public String getJkglStxxa()
	{
		return jkglStxxa;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column JKGL.JKGL_STXXA
	 * 
	 * @param jkglStxxa
	 *            the value for JKGL.JKGL_STXXA
	 * 
	 * @mbggenerated
	 */
	public void setJkglStxxa(String jkglStxxa)
	{
		this.jkglStxxa = jkglStxxa;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column JKGL.JKGL_STXXB
	 * 
	 * @return the value of JKGL.JKGL_STXXB
	 * 
	 * @mbggenerated
	 */
	public String getJkglStxxb()
	{
		return jkglStxxb;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column JKGL.JKGL_STXXB
	 * 
	 * @param jkglStxxb
	 *            the value for JKGL.JKGL_STXXB
	 * 
	 * @mbggenerated
	 */
	public void setJkglStxxb(String jkglStxxb)
	{
		this.jkglStxxb = jkglStxxb;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column JKGL.JKGL_STXXC
	 * 
	 * @return the value of JKGL.JKGL_STXXC
	 * 
	 * @mbggenerated
	 */
	public String getJkglStxxc()
	{
		return jkglStxxc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column JKGL.JKGL_STXXC
	 * 
	 * @param jkglStxxc
	 *            the value for JKGL.JKGL_STXXC
	 * 
	 * @mbggenerated
	 */
	public void setJkglStxxc(String jkglStxxc)
	{
		this.jkglStxxc = jkglStxxc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column JKGL.JKGL_STXXD
	 * 
	 * @return the value of JKGL.JKGL_STXXD
	 * 
	 * @mbggenerated
	 */
	public String getJkglStxxd()
	{
		return jkglStxxd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column JKGL.JKGL_STXXD
	 * 
	 * @param jkglStxxd
	 *            the value for JKGL.JKGL_STXXD
	 * 
	 * @mbggenerated
	 */
	public void setJkglStxxd(String jkglStxxd)
	{
		this.jkglStxxd = jkglStxxd;
	}
}