package com.ttgis.recruit.domain;

import java.io.Serializable;
import java.util.Date;

public class Kcgl implements Serializable
{
	private static final long serialVersionUID = 5569104284770137654L;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column KCGL.KCGL_ID
	 * 
	 * @mbggenerated
	 */
	private String kcglId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column KCGL.KCGL_NAME
	 * 
	 * @mbggenerated
	 */
	private String kcglName;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column KCGL.KCGL_DZ
	 * 
	 * @mbggenerated
	 */
	private String kcglDz;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column KCGL.KCGL_KSRQ
	 * 
	 * @mbggenerated
	 */
	private String kcglKsrq;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column KCGL.KCGL_KSSJ_START
	 * 
	 * @mbggenerated
	 */
	private String kcglKssjStart;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column KCGL.KCGL_KSSJ_END
	 * 
	 * @mbggenerated
	 */
	private String kcglKssjEnd;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column KCGL.KCGL_KCRL
	 * 
	 * @mbggenerated
	 */
	private Long kcglKcrl;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column KCGL.KCGL_YBMS
	 * 
	 * @mbggenerated
	 */
	private Long kcglYbms;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column KCGL.KCGL_SYRL
	 * 
	 * @mbggenerated
	 */
	private Long kcglSyrl;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column KCGL.KCGL_KCZT
	 * 
	 * @mbggenerated
	 */
	private String kcglKczt;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column KCGL.KCGL_ADDTIME
	 * 
	 * @mbggenerated
	 */
	private Date kcglAddtime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column KCGL.KCGL_DELFLAG
	 * 
	 * @mbggenerated
	 */
	private Long kcglDelflag;

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column KCGL.KCGL_ID
	 * 
	 * @return the value of KCGL.KCGL_ID
	 * 
	 * @mbggenerated
	 */
	public String getKcglId()
	{
		return kcglId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column KCGL.KCGL_ID
	 * 
	 * @param kcglId
	 *            the value for KCGL.KCGL_ID
	 * 
	 * @mbggenerated
	 */
	public void setKcglId(String kcglId)
	{
		this.kcglId = kcglId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column KCGL.KCGL_NAME
	 * 
	 * @return the value of KCGL.KCGL_NAME
	 * 
	 * @mbggenerated
	 */
	public String getKcglName()
	{
		return kcglName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column KCGL.KCGL_NAME
	 * 
	 * @param kcglName
	 *            the value for KCGL.KCGL_NAME
	 * 
	 * @mbggenerated
	 */
	public void setKcglName(String kcglName)
	{
		this.kcglName = kcglName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column KCGL.KCGL_DZ
	 * 
	 * @return the value of KCGL.KCGL_DZ
	 * 
	 * @mbggenerated
	 */
	public String getKcglDz()
	{
		return kcglDz;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column KCGL.KCGL_DZ
	 * 
	 * @param kcglDz
	 *            the value for KCGL.KCGL_DZ
	 * 
	 * @mbggenerated
	 */
	public void setKcglDz(String kcglDz)
	{
		this.kcglDz = kcglDz;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column KCGL.KCGL_KSRQ
	 * 
	 * @return the value of KCGL.KCGL_KSRQ
	 * 
	 * @mbggenerated
	 */
	public String getKcglKsrq()
	{
		return kcglKsrq;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column KCGL.KCGL_KSRQ
	 * 
	 * @param kcglKsrq
	 *            the value for KCGL.KCGL_KSRQ
	 * 
	 * @mbggenerated
	 */
	public void setKcglKsrq(String kcglKsrq)
	{
		this.kcglKsrq = kcglKsrq;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column KCGL.KCGL_KSSJ_START
	 * 
	 * @return the value of KCGL.KCGL_KSSJ_START
	 * 
	 * @mbggenerated
	 */
	public String getKcglKssjStart()
	{
		return kcglKssjStart;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column KCGL.KCGL_KSSJ_START
	 * 
	 * @param kcglKssjStart
	 *            the value for KCGL.KCGL_KSSJ_START
	 * 
	 * @mbggenerated
	 */
	public void setKcglKssjStart(String kcglKssjStart)
	{
		this.kcglKssjStart = kcglKssjStart;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column KCGL.KCGL_KSSJ_END
	 * 
	 * @return the value of KCGL.KCGL_KSSJ_END
	 * 
	 * @mbggenerated
	 */
	public String getKcglKssjEnd()
	{
		return kcglKssjEnd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column KCGL.KCGL_KSSJ_END
	 * 
	 * @param kcglKssjEnd
	 *            the value for KCGL.KCGL_KSSJ_END
	 * 
	 * @mbggenerated
	 */
	public void setKcglKssjEnd(String kcglKssjEnd)
	{
		this.kcglKssjEnd = kcglKssjEnd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column KCGL.KCGL_KCRL
	 * 
	 * @return the value of KCGL.KCGL_KCRL
	 * 
	 * @mbggenerated
	 */
	public Long getKcglKcrl()
	{
		return kcglKcrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column KCGL.KCGL_KCRL
	 * 
	 * @param kcglKcrl
	 *            the value for KCGL.KCGL_KCRL
	 * 
	 * @mbggenerated
	 */
	public void setKcglKcrl(Long kcglKcrl)
	{
		this.kcglKcrl = kcglKcrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column KCGL.KCGL_YBMS
	 * 
	 * @return the value of KCGL.KCGL_YBMS
	 * 
	 * @mbggenerated
	 */
	public Long getKcglYbms()
	{
		return kcglYbms;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column KCGL.KCGL_YBMS
	 * 
	 * @param kcglYbms
	 *            the value for KCGL.KCGL_YBMS
	 * 
	 * @mbggenerated
	 */
	public void setKcglYbms(Long kcglYbms)
	{
		this.kcglYbms = kcglYbms;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column KCGL.KCGL_SYRL
	 * 
	 * @return the value of KCGL.KCGL_SYRL
	 * 
	 * @mbggenerated
	 */
	public Long getKcglSyrl()
	{
		return kcglSyrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column KCGL.KCGL_SYRL
	 * 
	 * @param kcglSyrl
	 *            the value for KCGL.KCGL_SYRL
	 * 
	 * @mbggenerated
	 */
	public void setKcglSyrl(Long kcglSyrl)
	{
		this.kcglSyrl = kcglSyrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column KCGL.KCGL_KCZT
	 * 
	 * @return the value of KCGL.KCGL_KCZT
	 * 
	 * @mbggenerated
	 */
	public String getKcglKczt()
	{
		return kcglKczt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column KCGL.KCGL_KCZT
	 * 
	 * @param kcglKczt
	 *            the value for KCGL.KCGL_KCZT
	 * 
	 * @mbggenerated
	 */
	public void setKcglKczt(String kcglKczt)
	{
		this.kcglKczt = kcglKczt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column KCGL.KCGL_ADDTIME
	 * 
	 * @return the value of KCGL.KCGL_ADDTIME
	 * 
	 * @mbggenerated
	 */
	public Date getKcglAddtime()
	{
		return kcglAddtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column KCGL.KCGL_ADDTIME
	 * 
	 * @param kcglAddtime
	 *            the value for KCGL.KCGL_ADDTIME
	 * 
	 * @mbggenerated
	 */
	public void setKcglAddtime(Date kcglAddtime)
	{
		this.kcglAddtime = kcglAddtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column KCGL.KCGL_DELFLAG
	 * 
	 * @return the value of KCGL.KCGL_DELFLAG
	 * 
	 * @mbggenerated
	 */
	public Long getKcglDelflag()
	{
		return kcglDelflag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column KCGL.KCGL_DELFLAG
	 * 
	 * @param kcglDelflag
	 *            the value for KCGL.KCGL_DELFLAG
	 * 
	 * @mbggenerated
	 */
	public void setKcglDelflag(Long kcglDelflag)
	{
		this.kcglDelflag = kcglDelflag;
	}
}