package com.ttgis.recruit.domain;

import java.io.Serializable;
import java.util.Date;

public class Ksxtkbgl implements Serializable
{
	private static final long serialVersionUID = -6046800213478955127L;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column KSXTKBGL.KSXTKBGL_ID
	 * 
	 * @mbggenerated
	 */
	private String ksxtkbglId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column KSXTKBGL.KSXTKBGL_XH
	 * 
	 * @mbggenerated
	 */
	private String ksxtkbglXh;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column KSXTKBGL.KSXTKBGL_STARTTIME
	 * 
	 * @mbggenerated
	 */
	private String ksxtkbglStarttime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column KSXTKBGL.KSXTKBGL_ENDTIME
	 * 
	 * @mbggenerated
	 */
	private String ksxtkbglEndtime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column KSXTKBGL.KSXTKBGL_ID
	 * 
	 * @return the value of KSXTKBGL.KSXTKBGL_ID
	 * 
	 * @mbggenerated
	 */
	private Date ksxtkbglAddtime;
	private long ksxtkbglDelflag;

	public String getKsxtkbglId()
	{
		return ksxtkbglId;
	}

	public Date getKsxtkbglAddtime()
	{
		return ksxtkbglAddtime;
	}

	public void setKsxtkbglAddtime(Date ksxtkbglAddtime)
	{
		this.ksxtkbglAddtime = ksxtkbglAddtime;
	}

	public long getKsxtkbglDelflag()
	{
		return ksxtkbglDelflag;
	}

	public void setKsxtkbglDelflag(long ksxtkbglDelflag)
	{
		this.ksxtkbglDelflag = ksxtkbglDelflag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column KSXTKBGL.KSXTKBGL_ID
	 * 
	 * @param ksxtkbglId
	 *            the value for KSXTKBGL.KSXTKBGL_ID
	 * 
	 * @mbggenerated
	 */
	public void setKsxtkbglId(String ksxtkbglId)
	{
		this.ksxtkbglId = ksxtkbglId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column KSXTKBGL.KSXTKBGL_XH
	 * 
	 * @return the value of KSXTKBGL.KSXTKBGL_XH
	 * 
	 * @mbggenerated
	 */
	public String getKsxtkbglXh()
	{
		return ksxtkbglXh;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column KSXTKBGL.KSXTKBGL_XH
	 * 
	 * @param ksxtkbglXh
	 *            the value for KSXTKBGL.KSXTKBGL_XH
	 * 
	 * @mbggenerated
	 */
	public void setKsxtkbglXh(String ksxtkbglXh)
	{
		this.ksxtkbglXh = ksxtkbglXh;
	}

	public String getKsxtkbglStarttime()
	{
		return ksxtkbglStarttime;
	}

	public void setKsxtkbglStarttime(String ksxtkbglStarttime)
	{
		this.ksxtkbglStarttime = ksxtkbglStarttime;
	}

	public String getKsxtkbglEndtime()
	{
		return ksxtkbglEndtime;
	}

	public void setKsxtkbglEndtime(String ksxtkbglEndtime)
	{
		this.ksxtkbglEndtime = ksxtkbglEndtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column KSXTKBGL.KSXTKBGL_STARTTIME
	 * 
	 * @return the value of KSXTKBGL.KSXTKBGL_STARTTIME
	 * 
	 * @mbggenerated
	 */

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column KSXTKBGL.KSXTKBGL_STARTTIME
	 * 
	 * @param ksxtkbglStarttime
	 *            the value for KSXTKBGL.KSXTKBGL_STARTTIME
	 * 
	 * @mbggenerated
	 */

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column KSXTKBGL.KSXTKBGL_ENDTIME
	 * 
	 * @return the value of KSXTKBGL.KSXTKBGL_ENDTIME
	 * 
	 * @mbggenerated
	 */

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column KSXTKBGL.KSXTKBGL_ENDTIME
	 * 
	 * @param ksxtkbglEndtime
	 *            the value for KSXTKBGL.KSXTKBGL_ENDTIME
	 * 
	 * @mbggenerated
	 */
}