package com.ttgis.recruit.domain;

import java.io.Serializable;

public class Link implements Serializable
{
	private static final long serialVersionUID = 3448778044223175450L;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column LINK.LINK_ID
	 * 
	 * @mbggenerated
	 */
	private String linkId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column LINK.LINK_NAME
	 * 
	 * @mbggenerated
	 */
	private String linkName;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column LINK.LINK_PIC
	 * 
	 * @mbggenerated
	 */
	private String linkPic;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column LINK.LINK_CAT
	 * 
	 * @mbggenerated
	 */
	private String linkCat;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column LINK.LINK_INDEX
	 * 
	 * @mbggenerated
	 */
	private Integer linkIndex;

	private String linkl;

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column LINK.LINK_ID
	 * 
	 * @return the value of LINK.LINK_ID
	 * 
	 * @mbggenerated
	 */
	public String getLinkId()
	{
		return linkId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column LINK.LINK_ID
	 * 
	 * @param linkId
	 *            the value for LINK.LINK_ID
	 * 
	 * @mbggenerated
	 */
	public void setLinkId(String linkId)
	{
		this.linkId = linkId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column LINK.LINK_NAME
	 * 
	 * @return the value of LINK.LINK_NAME
	 * 
	 * @mbggenerated
	 */
	public String getLinkName()
	{
		return linkName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column LINK.LINK_NAME
	 * 
	 * @param linkName
	 *            the value for LINK.LINK_NAME
	 * 
	 * @mbggenerated
	 */
	public void setLinkName(String linkName)
	{
		this.linkName = linkName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column LINK.LINK_PIC
	 * 
	 * @return the value of LINK.LINK_PIC
	 * 
	 * @mbggenerated
	 */
	public String getLinkPic()
	{
		return linkPic;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column LINK.LINK_PIC
	 * 
	 * @param linkPic
	 *            the value for LINK.LINK_PIC
	 * 
	 * @mbggenerated
	 */
	public void setLinkPic(String linkPic)
	{
		this.linkPic = linkPic;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column LINK.LINK_CAT
	 * 
	 * @return the value of LINK.LINK_CAT
	 * 
	 * @mbggenerated
	 */
	public String getLinkCat()
	{
		return linkCat;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column LINK.LINK_CAT
	 * 
	 * @param linkCat
	 *            the value for LINK.LINK_CAT
	 * 
	 * @mbggenerated
	 */
	public void setLinkCat(String linkCat)
	{
		this.linkCat = linkCat;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column LINK.LINK_INDEX
	 * 
	 * @return the value of LINK.LINK_INDEX
	 * 
	 * @mbggenerated
	 */
	public Integer getLinkIndex()
	{
		return linkIndex;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column LINK.LINK_INDEX
	 * 
	 * @param linkIndex
	 *            the value for LINK.LINK_INDEX
	 * 
	 * @mbggenerated
	 */
	public void setLinkIndex(Integer linkIndex)
	{
		this.linkIndex = linkIndex;
	}

	public String getLinkl()
	{
		return linkl;
	}

	public void setLinkl(String linkl)
	{
		this.linkl = linkl;
	}

}