package com.ttgis.recruit.domain;

import java.io.Serializable;
import java.util.Date;

public class Ltbk implements Serializable
{

	private static final long serialVersionUID = 3522321412724400455L;

	private String tlqName;

	public String getTlqName()
	{
		return tlqName;
	}

	public void setTlqName(String tlqName)
	{
		this.tlqName = tlqName;
	}

	private String tlqId;

	public String getTlqId()
	{
		return tlqId;
	}

	public void setTlqId(String tlqId)
	{
		this.tlqId = tlqId;
	}

	private String addTime;

	public String getAddTime()
	{
		return addTime;
	}

	public void setAddTime(String addTime)
	{
		this.addTime = addTime;
	}

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column LTBK.LTBK_ID
	 * 
	 * @mbggenerated
	 */
	private String ltbkId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column LTBK.LTBK_NAME
	 * 
	 * @mbggenerated
	 */
	private String ltbkName;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column LTBK.LTBK_DELFLAG
	 * 
	 * @mbggenerated
	 */
	private String ltbkDelflag;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column LTBK.LTBK_ADDTIME
	 * 
	 * @mbggenerated
	 */
	private Date ltbkAddtime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column LTBK.LTBK_TYPE
	 * 
	 * @mbggenerated
	 */
	private String ltbkType;

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column LTBK.LTBK_ID
	 * 
	 * @return the value of LTBK.LTBK_ID
	 * 
	 * @mbggenerated
	 */
	public String getLtbkId()
	{
		return ltbkId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column LTBK.LTBK_ID
	 * 
	 * @param ltbkId
	 *            the value for LTBK.LTBK_ID
	 * 
	 * @mbggenerated
	 */
	public void setLtbkId(String ltbkId)
	{
		this.ltbkId = ltbkId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column LTBK.LTBK_NAME
	 * 
	 * @return the value of LTBK.LTBK_NAME
	 * 
	 * @mbggenerated
	 */
	public String getLtbkName()
	{
		return ltbkName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column LTBK.LTBK_NAME
	 * 
	 * @param ltbkName
	 *            the value for LTBK.LTBK_NAME
	 * 
	 * @mbggenerated
	 */
	public void setLtbkName(String ltbkName)
	{
		this.ltbkName = ltbkName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column LTBK.LTBK_DELFLAG
	 * 
	 * @return the value of LTBK.LTBK_DELFLAG
	 * 
	 * @mbggenerated
	 */
	public String getLtbkDelflag()
	{
		return ltbkDelflag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column LTBK.LTBK_DELFLAG
	 * 
	 * @param ltbkDelflag
	 *            the value for LTBK.LTBK_DELFLAG
	 * 
	 * @mbggenerated
	 */
	public void setLtbkDelflag(String ltbkDelflag)
	{
		this.ltbkDelflag = ltbkDelflag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column LTBK.LTBK_ADDTIME
	 * 
	 * @return the value of LTBK.LTBK_ADDTIME
	 * 
	 * @mbggenerated
	 */
	public Date getLtbkAddtime()
	{
		return ltbkAddtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column LTBK.LTBK_ADDTIME
	 * 
	 * @param ltbkAddtime
	 *            the value for LTBK.LTBK_ADDTIME
	 * 
	 * @mbggenerated
	 */
	public void setLtbkAddtime(Date ltbkAddtime)
	{
		this.ltbkAddtime = ltbkAddtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column LTBK.LTBK_TYPE
	 * 
	 * @return the value of LTBK.LTBK_TYPE
	 * 
	 * @mbggenerated
	 */
	public String getLtbkType()
	{
		return ltbkType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column LTBK.LTBK_TYPE
	 * 
	 * @param ltbkType
	 *            the value for LTBK.LTBK_TYPE
	 * 
	 * @mbggenerated
	 */
	public void setLtbkType(String ltbkType)
	{
		this.ltbkType = ltbkType;
	}
}