package com.ttgis.recruit.domain;

import java.io.Serializable;
import java.util.Date;

public class Ltbq implements Serializable
{

	private static final long serialVersionUID = -2176473499040114185L;

	private String ltbqBbsid;

	public String getLtbqBbsid()
	{
		return ltbqBbsid;
	}

	public void setLtbqBbsid(String ltbqBbsid)
	{
		this.ltbqBbsid = ltbqBbsid;
	}

	private String ltbqType;

	public String getLtbqType()
	{
		return ltbqType;
	}

	public void setLtbqType(String ltbqType)
	{
		this.ltbqType = ltbqType;
	}

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column LTBQ.LTBQ_ID
	 * 
	 * @mbggenerated
	 */
	private String ltbqId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column LTBQ.LTBQ_NAME
	 * 
	 * @mbggenerated
	 */
	private String ltbqName;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column LTBQ.LTBQ_ORDER
	 * 
	 * @mbggenerated
	 */
	private Long ltbqOrder;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column LTBQ.LTBQ_ADDTIME
	 * 
	 * @mbggenerated
	 */
	private Date ltbqAddtime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column LTBQ.LTBQ_DELFLAG
	 * 
	 * @mbggenerated
	 */
	private Long ltbqDelflag;

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column LTBQ.LTBQ_ID
	 * 
	 * @return the value of LTBQ.LTBQ_ID
	 * 
	 * @mbggenerated
	 */
	public String getLtbqId()
	{
		return ltbqId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column LTBQ.LTBQ_ID
	 * 
	 * @param ltbqId
	 *            the value for LTBQ.LTBQ_ID
	 * 
	 * @mbggenerated
	 */
	public void setLtbqId(String ltbqId)
	{
		this.ltbqId = ltbqId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column LTBQ.LTBQ_NAME
	 * 
	 * @return the value of LTBQ.LTBQ_NAME
	 * 
	 * @mbggenerated
	 */
	public String getLtbqName()
	{
		return ltbqName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column LTBQ.LTBQ_NAME
	 * 
	 * @param ltbqName
	 *            the value for LTBQ.LTBQ_NAME
	 * 
	 * @mbggenerated
	 */
	public void setLtbqName(String ltbqName)
	{
		this.ltbqName = ltbqName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column LTBQ.LTBQ_ORDER
	 * 
	 * @return the value of LTBQ.LTBQ_ORDER
	 * 
	 * @mbggenerated
	 */
	public Long getLtbqOrder()
	{
		return ltbqOrder;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column LTBQ.LTBQ_ORDER
	 * 
	 * @param ltbqOrder
	 *            the value for LTBQ.LTBQ_ORDER
	 * 
	 * @mbggenerated
	 */
	public void setLtbqOrder(Long ltbqOrder)
	{
		this.ltbqOrder = ltbqOrder;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column LTBQ.LTBQ_ADDTIME
	 * 
	 * @return the value of LTBQ.LTBQ_ADDTIME
	 * 
	 * @mbggenerated
	 */
	public Date getLtbqAddtime()
	{
		return ltbqAddtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column LTBQ.LTBQ_ADDTIME
	 * 
	 * @param ltbqAddtime
	 *            the value for LTBQ.LTBQ_ADDTIME
	 * 
	 * @mbggenerated
	 */
	public void setLtbqAddtime(Date ltbqAddtime)
	{
		this.ltbqAddtime = ltbqAddtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column LTBQ.LTBQ_DELFLAG
	 * 
	 * @return the value of LTBQ.LTBQ_DELFLAG
	 * 
	 * @mbggenerated
	 */
	public Long getLtbqDelflag()
	{
		return ltbqDelflag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column LTBQ.LTBQ_DELFLAG
	 * 
	 * @param ltbqDelflag
	 *            the value for LTBQ.LTBQ_DELFLAG
	 * 
	 * @mbggenerated
	 */
	public void setLtbqDelflag(Long ltbqDelflag)
	{
		this.ltbqDelflag = ltbqDelflag;
	}
}