package com.ttgis.recruit.domain;

import java.io.Serializable;
import java.util.Date;

public class Mbgl implements Serializable
{
	private static final long serialVersionUID = 6801381291478729413L;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column MBGL.MBGL_ID
	 * 
	 * @mbggenerated
	 */
	private String mbglId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column MBGL.MBGL_NAME
	 * 
	 * @mbggenerated
	 */
	private String mbglName;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column MBGL.MBGL_TYPE
	 * 
	 * @mbggenerated
	 */
	private String mbglType;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column MBGL.MBGL_SSDW
	 * 
	 * @mbggenerated
	 */
	private String mbglSsdw;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column MBGL.MBGL_ADDUSER
	 * 
	 * @mbggenerated
	 */
	private String mbglContent;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column MBGL.MBGL_ADDTIME
	 * 
	 * @mbggenerated
	 */
	private Date mbglAddtime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column MBGL.MBGL_ID
	 * 
	 * @return the value of MBGL.MBGL_ID
	 * 
	 * @mbggenerated
	 */
	public String getMbglId()
	{
		return mbglId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column MBGL.MBGL_ID
	 * 
	 * @param mbglId
	 *            the value for MBGL.MBGL_ID
	 * 
	 * @mbggenerated
	 */
	public void setMbglId(String mbglId)
	{
		this.mbglId = mbglId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column MBGL.MBGL_NAME
	 * 
	 * @return the value of MBGL.MBGL_NAME
	 * 
	 * @mbggenerated
	 */
	public String getMbglName()
	{
		return mbglName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column MBGL.MBGL_NAME
	 * 
	 * @param mbglName
	 *            the value for MBGL.MBGL_NAME
	 * 
	 * @mbggenerated
	 */
	public void setMbglName(String mbglName)
	{
		this.mbglName = mbglName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column MBGL.MBGL_TYPE
	 * 
	 * @return the value of MBGL.MBGL_TYPE
	 * 
	 * @mbggenerated
	 */
	public String getMbglType()
	{
		return mbglType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column MBGL.MBGL_TYPE
	 * 
	 * @param mbglType
	 *            the value for MBGL.MBGL_TYPE
	 * 
	 * @mbggenerated
	 */
	public void setMbglType(String mbglType)
	{
		this.mbglType = mbglType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column MBGL.MBGL_SSDW
	 * 
	 * @return the value of MBGL.MBGL_SSDW
	 * 
	 * @mbggenerated
	 */
	public String getMbglSsdw()
	{
		return mbglSsdw;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column MBGL.MBGL_SSDW
	 * 
	 * @param mbglSsdw
	 *            the value for MBGL.MBGL_SSDW
	 * 
	 * @mbggenerated
	 */
	public void setMbglSsdw(String mbglSsdw)
	{
		this.mbglSsdw = mbglSsdw;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column MBGL.MBGL_ADDUSER
	 * 
	 * @return the value of MBGL.MBGL_ADDUSER
	 * 
	 * @mbggenerated
	 */
	public String getMbglContent()
	{
		return mbglContent;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column MBGL.MBGL_ADDUSER
	 * 
	 * @param mbglContent
	 *            the value for MBGL.MBGL_ADDUSER
	 * 
	 * @mbggenerated
	 */
	public void setMbglContent(String mbglContent)
	{
		this.mbglContent = mbglContent;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column MBGL.MBGL_ADDTIME
	 * 
	 * @return the value of MBGL.MBGL_ADDTIME
	 * 
	 * @mbggenerated
	 */
	public Date getMbglAddtime()
	{
		return mbglAddtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column MBGL.MBGL_ADDTIME
	 * 
	 * @param mbglAddtime
	 *            the value for MBGL.MBGL_ADDTIME
	 * 
	 * @mbggenerated
	 */
	public void setMbglAddtime(Date mbglAddtime)
	{
		this.mbglAddtime = mbglAddtime;
	}
}