package com.ttgis.recruit.domain;

import java.io.Serializable;

public class Member implements Serializable
{
	private static final long serialVersionUID = -3535436298702735415L;
	private String yfye;
	private String cpcs;
	private String sycpcs;
	private String memberYycpcs;

	public String getYfye()
	{
		return yfye;
	}

	public void setYfye(String yfye)
	{
		this.yfye = yfye;
	}

	public String getCpcs()
	{
		return cpcs;
	}

	public void setCpcs(String cpcs)
	{
		this.cpcs = cpcs;
	}

	public String getSycpcs()
	{
		return sycpcs;
	}

	public void setSycpcs(String sycpcs)
	{
		this.sycpcs = sycpcs;
	}

	public String getMemberYycpcs()
	{
		return memberYycpcs;
	}

	public void setMemberYycpcs(String memberYycpcs)
	{
		this.memberYycpcs = memberYycpcs;
	}

	private String yjf;

	public String getYjf()
	{
		return yjf;
	}

	public void setYjf(String yjf)
	{
		this.yjf = yjf;
	}

	private String memberYfkye;

	public String getMemberYfkye()
	{
		return memberYfkye;
	}

	public void setMemberYfkye(String memberYfkye)
	{
		this.memberYfkye = memberYfkye;
	}

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column MEMBER.MEMBER_ID
	 * 
	 * @mbggenerated
	 */
	private String memberId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column MEMBER.MEMBER_NAME
	 * 
	 * @mbggenerated
	 */
	private String memberName;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column MEMBER.MEMBER_IDCARD
	 * 
	 * @mbggenerated
	 */
	private String memberIdcard;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column MEMBER.MEMBER_TELEPHONE
	 * 
	 * @mbggenerated
	 */
	private String memberTelephone;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column MEMBER.MEMBER_EMAIL
	 * 
	 * @mbggenerated
	 */
	private String memberEmail;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column MEMBER.MEMBER_ZZJG
	 * 
	 * @mbggenerated
	 */
	private String memberZzjg;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column MEMBER.MEMBER_HYDJ
	 * 
	 * @mbggenerated
	 */
	private String memberHydj;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column MEMBER.MEMBER_DELFLAG
	 * 
	 * @mbggenerated
	 */
	private String memberDelflag;

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column MEMBER.MEMBER_ID
	 * 
	 * @return the value of MEMBER.MEMBER_ID
	 * 
	 * @mbggenerated
	 */
	public String getMemberId()
	{
		return memberId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column MEMBER.MEMBER_ID
	 * 
	 * @param memberId
	 *            the value for MEMBER.MEMBER_ID
	 * 
	 * @mbggenerated
	 */
	public void setMemberId(String memberId)
	{
		this.memberId = memberId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column MEMBER.MEMBER_NAME
	 * 
	 * @return the value of MEMBER.MEMBER_NAME
	 * 
	 * @mbggenerated
	 */
	public String getMemberName()
	{
		return memberName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column MEMBER.MEMBER_NAME
	 * 
	 * @param memberName
	 *            the value for MEMBER.MEMBER_NAME
	 * 
	 * @mbggenerated
	 */
	public void setMemberName(String memberName)
	{
		this.memberName = memberName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column MEMBER.MEMBER_IDCARD
	 * 
	 * @return the value of MEMBER.MEMBER_IDCARD
	 * 
	 * @mbggenerated
	 */
	public String getMemberIdcard()
	{
		return memberIdcard;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column MEMBER.MEMBER_IDCARD
	 * 
	 * @param memberIdcard
	 *            the value for MEMBER.MEMBER_IDCARD
	 * 
	 * @mbggenerated
	 */
	public void setMemberIdcard(String memberIdcard)
	{
		this.memberIdcard = memberIdcard;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column MEMBER.MEMBER_TELEPHONE
	 * 
	 * @return the value of MEMBER.MEMBER_TELEPHONE
	 * 
	 * @mbggenerated
	 */
	public String getMemberTelephone()
	{
		return memberTelephone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column MEMBER.MEMBER_TELEPHONE
	 * 
	 * @param memberTelephone
	 *            the value for MEMBER.MEMBER_TELEPHONE
	 * 
	 * @mbggenerated
	 */
	public void setMemberTelephone(String memberTelephone)
	{
		this.memberTelephone = memberTelephone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column MEMBER.MEMBER_EMAIL
	 * 
	 * @return the value of MEMBER.MEMBER_EMAIL
	 * 
	 * @mbggenerated
	 */
	public String getMemberEmail()
	{
		return memberEmail;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column MEMBER.MEMBER_EMAIL
	 * 
	 * @param memberEmail
	 *            the value for MEMBER.MEMBER_EMAIL
	 * 
	 * @mbggenerated
	 */
	public void setMemberEmail(String memberEmail)
	{
		this.memberEmail = memberEmail;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column MEMBER.MEMBER_ZZJG
	 * 
	 * @return the value of MEMBER.MEMBER_ZZJG
	 * 
	 * @mbggenerated
	 */
	public String getMemberZzjg()
	{
		return memberZzjg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column MEMBER.MEMBER_ZZJG
	 * 
	 * @param memberZzjg
	 *            the value for MEMBER.MEMBER_ZZJG
	 * 
	 * @mbggenerated
	 */
	public void setMemberZzjg(String memberZzjg)
	{
		this.memberZzjg = memberZzjg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column MEMBER.MEMBER_HYDJ
	 * 
	 * @return the value of MEMBER.MEMBER_HYDJ
	 * 
	 * @mbggenerated
	 */
	public String getMemberHydj()
	{
		return memberHydj;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column MEMBER.MEMBER_HYDJ
	 * 
	 * @param memberHydj
	 *            the value for MEMBER.MEMBER_HYDJ
	 * 
	 * @mbggenerated
	 */
	public void setMemberHydj(String memberHydj)
	{
		this.memberHydj = memberHydj;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column MEMBER.MEMBER_DELFLAG
	 * 
	 * @return the value of MEMBER.MEMBER_DELFLAG
	 * 
	 * @mbggenerated
	 */
	public String getMemberDelflag()
	{
		return memberDelflag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column MEMBER.MEMBER_DELFLAG
	 * 
	 * @param memberDelflag
	 *            the value for MEMBER.MEMBER_DELFLAG
	 * 
	 * @mbggenerated
	 */
	public void setMemberDelflag(String memberDelflag)
	{
		this.memberDelflag = memberDelflag;
	}
}