package com.ttgis.recruit.domain;

import java.io.Serializable;
import java.util.Date;
import java.util.List;

public class Msq implements Serializable
{
	private static final long serialVersionUID = -5981087676311757854L;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column MSQ.MSQ_ID
	 * 
	 * @mbggenerated
	 */
	private String msqId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column MSQ.ZZJG_ID
	 * 
	 * @mbggenerated
	 */
	private String zzjgId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column MSQ.MSQ_NAME
	 * 
	 * @mbggenerated
	 */
	private String msqName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column MSQ.MSQ_ADDTIME
	 * 
	 * @mbggenerated
	 */
	private Date msqAddtime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column MSQ.MSQ_MSG_IDS
	 * 
	 * @mbggenerated
	 */
	private String msqMsgIds;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column MSQ.MSQ_MSG_NAMES
	 * 
	 * @mbggenerated
	 */
	private String msqMsgNames;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column MSQ.MSQ_MSSJ
	 * 
	 * @mbggenerated
	 */
	private String msqMssj;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column MSQ.MSQ_MSDD
	 * 
	 * @mbggenerated
	 */
	private String msqMsdd;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column MSQ.MSQ_MSLB
	 * 
	 * @mbggenerated
	 */
	private String msqMslb;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column MSQ.MSQ_DELFLAG
	 * 
	 * @mbggenerated
	 */
	private Integer msqDelflag;
	private List<Userinfo> msqMsgList;

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column MSQ.MSQ_ID
	 * 
	 * @return the value of MSQ.MSQ_ID
	 * @mbggenerated
	 */
	public String getMsqId()
	{
		return msqId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column MSQ.MSQ_ID
	 * 
	 * @param msqId
	 *            the value for MSQ.MSQ_ID
	 * @mbggenerated
	 */
	public void setMsqId(String msqId)
	{
		this.msqId = msqId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column MSQ.ZZJG_ID
	 * 
	 * @return the value of MSQ.ZZJG_ID
	 * @mbggenerated
	 */
	public String getZzjgId()
	{
		return zzjgId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column MSQ.ZZJG_ID
	 * 
	 * @param zzjgId
	 *            the value for MSQ.ZZJG_ID
	 * @mbggenerated
	 */
	public void setZzjgId(String zzjgId)
	{
		this.zzjgId = zzjgId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column MSQ.MSQ_NAME
	 * 
	 * @return the value of MSQ.MSQ_NAME
	 * @mbggenerated
	 */
	public String getMsqName()
	{
		return msqName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column MSQ.MSQ_NAME
	 * 
	 * @param msqName
	 *            the value for MSQ.MSQ_NAME
	 * @mbggenerated
	 */
	public void setMsqName(String msqName)
	{
		this.msqName = msqName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column MSQ.MSQ_ADDTIME
	 * 
	 * @return the value of MSQ.MSQ_ADDTIME
	 * @mbggenerated
	 */
	public Date getMsqAddtime()
	{
		return msqAddtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column MSQ.MSQ_ADDTIME
	 * 
	 * @param msqAddtime
	 *            the value for MSQ.MSQ_ADDTIME
	 * @mbggenerated
	 */
	public void setMsqAddtime(Date msqAddtime)
	{
		this.msqAddtime = msqAddtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column MSQ.MSQ_MSG_IDS
	 * 
	 * @return the value of MSQ.MSQ_MSG_IDS
	 * @mbggenerated
	 */
	public String getMsqMsgIds()
	{
		return msqMsgIds;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column MSQ.MSQ_MSG_IDS
	 * 
	 * @param msqMsgIds
	 *            the value for MSQ.MSQ_MSG_IDS
	 * @mbggenerated
	 */
	public void setMsqMsgIds(String msqMsgIds)
	{
		this.msqMsgIds = msqMsgIds;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column MSQ.MSQ_MSG_NAMES
	 * 
	 * @return the value of MSQ.MSQ_MSG_NAMES
	 * @mbggenerated
	 */
	public String getMsqMsgNames()
	{
		return msqMsgNames;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column MSQ.MSQ_MSG_NAMES
	 * 
	 * @param msqMsgNames
	 *            the value for MSQ.MSQ_MSG_NAMES
	 * @mbggenerated
	 */
	public void setMsqMsgNames(String msqMsgNames)
	{
		this.msqMsgNames = msqMsgNames;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column MSQ.MSQ_MSSJ
	 * 
	 * @return the value of MSQ.MSQ_MSSJ
	 * @mbggenerated
	 */
	public String getMsqMssj()
	{
		return msqMssj;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column MSQ.MSQ_MSSJ
	 * 
	 * @param msqMssj
	 *            the value for MSQ.MSQ_MSSJ
	 * @mbggenerated
	 */
	public void setMsqMssj(String msqMssj)
	{
		this.msqMssj = msqMssj;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column MSQ.MSQ_MSDD
	 * 
	 * @return the value of MSQ.MSQ_MSDD
	 * @mbggenerated
	 */
	public String getMsqMsdd()
	{
		return msqMsdd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column MSQ.MSQ_MSDD
	 * 
	 * @param msqMsdd
	 *            the value for MSQ.MSQ_MSDD
	 * @mbggenerated
	 */
	public void setMsqMsdd(String msqMsdd)
	{
		this.msqMsdd = msqMsdd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column MSQ.MSQ_MSLB
	 * 
	 * @return the value of MSQ.MSQ_MSLB
	 * @mbggenerated
	 */
	public String getMsqMslb()
	{
		return msqMslb;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column MSQ.MSQ_MSLB
	 * 
	 * @param msqMslb
	 *            the value for MSQ.MSQ_MSLB
	 * @mbggenerated
	 */
	public void setMsqMslb(String msqMslb)
	{
		this.msqMslb = msqMslb;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column MSQ.MSQ_DELFLAG
	 * 
	 * @return the value of MSQ.MSQ_DELFLAG
	 * @mbggenerated
	 */
	public Integer getMsqDelflag()
	{
		return msqDelflag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column MSQ.MSQ_DELFLAG
	 * 
	 * @param msqDelflag
	 *            the value for MSQ.MSQ_DELFLAG
	 * @mbggenerated
	 */
	public void setMsqDelflag(Integer msqDelflag)
	{
		this.msqDelflag = msqDelflag;
	}

	public List<Userinfo> getMsqMsgList()
	{
		return msqMsgList;
	}

	public void setMsqMsgList(List<Userinfo> msqMsgList)
	{
		this.msqMsgList = msqMsgList;
	}

}