package com.ttgis.recruit.domain;

import java.io.Serializable;
import java.util.Date;

public class Msqgl_detailed implements Serializable
{
	private static final long serialVersionUID = 6998446979275567365L;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column MSQGL_DETAILED.MSQGL_DETAILED_ID
	 * 
	 * @mbggenerated
	 */
	private String msqglDetailedId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column MSQGL_DETAILED.JTJLK_ID
	 * 
	 * @mbggenerated
	 */
	private String jtjlkId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column MSQGL_DETAILED.MSQGL_DETAILED_MSLB
	 * 
	 * @mbggenerated
	 */
	private String msqglDetailedMslb;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column MSQGL_DETAILED.MSQGL_DETAILED_MSSJ
	 * 
	 * @mbggenerated
	 */
	private String msqglDetailedMssj;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column MSQGL_DETAILED.MSQGL_DETAILED_MSDD
	 * 
	 * @mbggenerated
	 */
	private String msqglDetailedMsdd;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column MSQGL_DETAILED.MSQGL_DETAILED_MSG
	 * 
	 * @mbggenerated
	 */
	private String msqglDetailedMsg;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column MSQGL_DETAILED.MSQGL_DETAILED_LSZH_ID
	 * 
	 * @mbggenerated
	 */
	private String msqglDetailedLszhId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column MSQGL_DETAILED.MSQGL_DETAILED_ADDTIME
	 * 
	 * @mbggenerated
	 */
	private Date msqglDetailedAddtime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column MSQGL_DETAILED.MSQGL_DETAILED_DELFLAG
	 * 
	 * @mbggenerated
	 */
	private Long msqglDetailedDelflag;

	private String msqglDetailedPj;

	private String msqglDetailedJl;

	private String jtjlkName;

	public String getJtjlkName()
	{
		return jtjlkName;
	}

	public void setJtjlkName(String jtjlkName)
	{
		this.jtjlkName = jtjlkName;
	}

	public String getMsqglDetailedPj()
	{
		return msqglDetailedPj;
	}

	public void setMsqglDetailedPj(String msqglDetailedPj)
	{
		this.msqglDetailedPj = msqglDetailedPj;
	}

	public String getMsqglDetailedJl()
	{
		return msqglDetailedJl;
	}

	public void setMsqglDetailedJl(String msqglDetailedJl)
	{
		this.msqglDetailedJl = msqglDetailedJl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column MSQGL_DETAILED.MSQGL_DETAILED_ID
	 * 
	 * @return the value of MSQGL_DETAILED.MSQGL_DETAILED_ID
	 * 
	 * @mbggenerated
	 */
	public String getMsqglDetailedId()
	{
		return msqglDetailedId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column MSQGL_DETAILED.MSQGL_DETAILED_ID
	 * 
	 * @param msqglDetailedId
	 *            the value for MSQGL_DETAILED.MSQGL_DETAILED_ID
	 * 
	 * @mbggenerated
	 */
	public void setMsqglDetailedId(String msqglDetailedId)
	{
		this.msqglDetailedId = msqglDetailedId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column MSQGL_DETAILED.JTJLK_ID
	 * 
	 * @return the value of MSQGL_DETAILED.JTJLK_ID
	 * 
	 * @mbggenerated
	 */
	public String getJtjlkId()
	{
		return jtjlkId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column MSQGL_DETAILED.JTJLK_ID
	 * 
	 * @param jtjlkId
	 *            the value for MSQGL_DETAILED.JTJLK_ID
	 * 
	 * @mbggenerated
	 */
	public void setJtjlkId(String jtjlkId)
	{
		this.jtjlkId = jtjlkId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column MSQGL_DETAILED.MSQGL_DETAILED_MSLB
	 * 
	 * @return the value of MSQGL_DETAILED.MSQGL_DETAILED_MSLB
	 * 
	 * @mbggenerated
	 */
	public String getMsqglDetailedMslb()
	{
		return msqglDetailedMslb;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column MSQGL_DETAILED.MSQGL_DETAILED_MSLB
	 * 
	 * @param msqglDetailedMslb
	 *            the value for MSQGL_DETAILED.MSQGL_DETAILED_MSLB
	 * 
	 * @mbggenerated
	 */
	public void setMsqglDetailedMslb(String msqglDetailedMslb)
	{
		this.msqglDetailedMslb = msqglDetailedMslb;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column MSQGL_DETAILED.MSQGL_DETAILED_MSSJ
	 * 
	 * @return the value of MSQGL_DETAILED.MSQGL_DETAILED_MSSJ
	 * 
	 * @mbggenerated
	 */
	public String getMsqglDetailedMssj()
	{
		return msqglDetailedMssj;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column MSQGL_DETAILED.MSQGL_DETAILED_MSSJ
	 * 
	 * @param msqglDetailedMssj
	 *            the value for MSQGL_DETAILED.MSQGL_DETAILED_MSSJ
	 * 
	 * @mbggenerated
	 */
	public void setMsqglDetailedMssj(String msqglDetailedMssj)
	{
		this.msqglDetailedMssj = msqglDetailedMssj;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column MSQGL_DETAILED.MSQGL_DETAILED_MSDD
	 * 
	 * @return the value of MSQGL_DETAILED.MSQGL_DETAILED_MSDD
	 * 
	 * @mbggenerated
	 */
	public String getMsqglDetailedMsdd()
	{
		return msqglDetailedMsdd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column MSQGL_DETAILED.MSQGL_DETAILED_MSDD
	 * 
	 * @param msqglDetailedMsdd
	 *            the value for MSQGL_DETAILED.MSQGL_DETAILED_MSDD
	 * 
	 * @mbggenerated
	 */
	public void setMsqglDetailedMsdd(String msqglDetailedMsdd)
	{
		this.msqglDetailedMsdd = msqglDetailedMsdd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column MSQGL_DETAILED.MSQGL_DETAILED_MSG
	 * 
	 * @return the value of MSQGL_DETAILED.MSQGL_DETAILED_MSG
	 * 
	 * @mbggenerated
	 */
	public String getMsqglDetailedMsg()
	{
		return msqglDetailedMsg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column MSQGL_DETAILED.MSQGL_DETAILED_MSG
	 * 
	 * @param msqglDetailedMsg
	 *            the value for MSQGL_DETAILED.MSQGL_DETAILED_MSG
	 * 
	 * @mbggenerated
	 */
	public void setMsqglDetailedMsg(String msqglDetailedMsg)
	{
		this.msqglDetailedMsg = msqglDetailedMsg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column MSQGL_DETAILED.MSQGL_DETAILED_LSZH_ID
	 * 
	 * @return the value of MSQGL_DETAILED.MSQGL_DETAILED_LSZH_ID
	 * 
	 * @mbggenerated
	 */
	public String getMsqglDetailedLszhId()
	{
		return msqglDetailedLszhId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column MSQGL_DETAILED.MSQGL_DETAILED_LSZH_ID
	 * 
	 * @param msqglDetailedLszhId
	 *            the value for MSQGL_DETAILED.MSQGL_DETAILED_LSZH_ID
	 * 
	 * @mbggenerated
	 */
	public void setMsqglDetailedLszhId(String msqglDetailedLszhId)
	{
		this.msqglDetailedLszhId = msqglDetailedLszhId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column MSQGL_DETAILED.MSQGL_DETAILED_ADDTIME
	 * 
	 * @return the value of MSQGL_DETAILED.MSQGL_DETAILED_ADDTIME
	 * 
	 * @mbggenerated
	 */
	public Date getMsqglDetailedAddtime()
	{
		return msqglDetailedAddtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column MSQGL_DETAILED.MSQGL_DETAILED_ADDTIME
	 * 
	 * @param msqglDetailedAddtime
	 *            the value for MSQGL_DETAILED.MSQGL_DETAILED_ADDTIME
	 * 
	 * @mbggenerated
	 */
	public void setMsqglDetailedAddtime(Date msqglDetailedAddtime)
	{
		this.msqglDetailedAddtime = msqglDetailedAddtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column MSQGL_DETAILED.MSQGL_DETAILED_DELFLAG
	 * 
	 * @return the value of MSQGL_DETAILED.MSQGL_DETAILED_DELFLAG
	 * 
	 * @mbggenerated
	 */
	public Long getMsqglDetailedDelflag()
	{
		return msqglDetailedDelflag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column MSQGL_DETAILED.MSQGL_DETAILED_DELFLAG
	 * 
	 * @param msqglDetailedDelflag
	 *            the value for MSQGL_DETAILED.MSQGL_DETAILED_DELFLAG
	 * 
	 * @mbggenerated
	 */
	public void setMsqglDetailedDelflag(Long msqglDetailedDelflag)
	{
		this.msqglDetailedDelflag = msqglDetailedDelflag;
	}
}