package com.ttgis.recruit.domain;

import java.io.Serializable;
import java.util.Date;

public class Position implements Serializable
{
	private static final long serialVersionUID = 8953628789922737905L;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column POSITION.POSITION_ID
	 * 
	 * @mbggenerated
	 */
	private String positionId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column POSITION.ZZJG_ID
	 * 
	 * @mbggenerated
	 */
	private String zzjgId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column POSITION.POSITION_ZSDW
	 * 
	 * @mbggenerated
	 */
	private String positionZsdw;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column POSITION.POSITION_NAME
	 * 
	 * @mbggenerated
	 */
	private String positionName;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column POSITION.POSITION_TYPE
	 * 
	 * @mbggenerated
	 */
	private String positionType;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column POSITION.POSITION_WORKADDRESS
	 * 
	 * @mbggenerated
	 */
	private String positionWorkaddress;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column POSITION.POSITION_STATUS
	 * 
	 * @mbggenerated
	 */
	private String positionStatus;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column POSITION.POSITION_ADDTIME
	 * 
	 * @mbggenerated
	 */
	private Date positionAddtime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column POSITION.POSITION_DELFLAG
	 * 
	 * @mbggenerated
	 */
	private Integer positionDelflag;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column POSITION.POSITION_XLYQ
	 * 
	 * @mbggenerated
	 */
	private String positionXlyq;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column POSITION.POSITION_ZPZY
	 * 
	 * @mbggenerated
	 */
	private String positionZpzy;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column POSITION.POSITION_XQRS
	 * 
	 * @mbggenerated
	 */
	private String positionXqrs;
	private String positionZylb;
	private String positionZpfl;
	private String positionCanEdit;

	public String getPositionCanEdit()
	{
		return positionCanEdit;
	}

	public void setPositionCanEdit(String positionCanEdit)
	{
		this.positionCanEdit = positionCanEdit;
	}

	public String getPositionZylb()
	{
		return positionZylb;
	}

	public void setPositionZylb(String positionZylb)
	{
		this.positionZylb = positionZylb;
	}

	public String getPositionId()
	{
		return positionId;
	}

	public void setPositionId(String positionId)
	{
		this.positionId = positionId;
	}

	public String getZzjgId()
	{
		return zzjgId;
	}

	public void setZzjgId(String zzjgId)
	{
		this.zzjgId = zzjgId;
	}

	public String getPositionZsdw()
	{
		return positionZsdw;
	}

	public void setPositionZsdw(String positionZsdw)
	{
		this.positionZsdw = positionZsdw;
	}

	public String getPositionName()
	{
		return positionName;
	}

	public void setPositionName(String positionName)
	{
		this.positionName = positionName;
	}

	public String getPositionType()
	{
		return positionType;
	}

	public void setPositionType(String positionType)
	{
		this.positionType = positionType;
	}

	public String getPositionWorkaddress()
	{
		return positionWorkaddress;
	}

	public void setPositionWorkaddress(String positionWorkaddress)
	{
		this.positionWorkaddress = positionWorkaddress;
	}

	public String getPositionStatus()
	{
		return positionStatus;
	}

	public void setPositionStatus(String positionStatus)
	{
		this.positionStatus = positionStatus;
	}

	public Date getPositionAddtime()
	{
		return positionAddtime;
	}

	public void setPositionAddtime(Date positionAddtime)
	{
		this.positionAddtime = positionAddtime;
	}

	public Integer getPositionDelflag()
	{
		return positionDelflag;
	}

	public void setPositionDelflag(Integer positionDelflag)
	{
		this.positionDelflag = positionDelflag;
	}

	public String getPositionXlyq()
	{
		return positionXlyq;
	}

	public void setPositionXlyq(String positionXlyq)
	{
		this.positionXlyq = positionXlyq;
	}

	public String getPositionZpzy()
	{
		return positionZpzy;
	}

	public void setPositionZpzy(String positionZpzy)
	{
		this.positionZpzy = positionZpzy;
	}

	public String getPositionZpfl()
	{
		return positionZpfl;
	}

	public void setPositionZpfl(String positionZpfl)
	{
		this.positionZpfl = positionZpfl;
	}

	public String getPositionXqrs()
	{
		return positionXqrs;
	}

	public void setPositionXqrs(String positionXqrs)
	{
		this.positionXqrs = positionXqrs;
	}

}