package com.ttgis.recruit.domain;

public class PositionWithBLOBs extends Position
{
	/**
	 * 
	 */
	private static final long serialVersionUID = -1794880440411747117L;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column POSITION.POSITION_DUTY
	 * 
	 * @mbggenerated
	 */
	private String positionDuty;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column POSITION.POSITION_REQUIERD
	 * 
	 * @mbggenerated
	 */
	private String positionRequierd;

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column POSITION.POSITION_DUTY
	 * 
	 * @return the value of POSITION.POSITION_DUTY
	 * 
	 * @mbggenerated
	 */
	public String getPositionDuty()
	{
		return positionDuty;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column POSITION.POSITION_DUTY
	 * 
	 * @param positionDuty
	 *            the value for POSITION.POSITION_DUTY
	 * 
	 * @mbggenerated
	 */
	public void setPositionDuty(String positionDuty)
	{
		this.positionDuty = positionDuty;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column POSITION.POSITION_REQUIERD
	 * 
	 * @return the value of POSITION.POSITION_REQUIERD
	 * 
	 * @mbggenerated
	 */
	public String getPositionRequierd()
	{
		return positionRequierd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column POSITION.POSITION_REQUIERD
	 * 
	 * @param positionRequierd
	 *            the value for POSITION.POSITION_REQUIERD
	 * 
	 * @mbggenerated
	 */
	public void setPositionRequierd(String positionRequierd)
	{
		this.positionRequierd = positionRequierd;
	}
}