package com.ttgis.recruit.domain;

import java.io.Serializable;
import java.util.Date;

public class Resume_xnzw implements Serializable
{
	private static final long serialVersionUID = 8688118029684057169L;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column RESUME_XNZW.RESUME_XNZWID
	 * 
	 * @mbggenerated
	 */
	private String resumeXnzwid;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column RESUME_XNZW.RESUME_ID
	 * 
	 * @mbggenerated
	 */
	private String resumeId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column RESUME_XNZW.RESUME_XNZWMC
	 * 
	 * @mbggenerated
	 */
	private String resumeXnzwmc;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column RESUME_XNZW.RESUME_RZSJ
	 * 
	 * @mbggenerated
	 */
	private String resumeRzsj;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column RESUME_XNZW.RESUME_RZSJ1
	 * 
	 * @mbggenerated
	 */
	private String resumeRzsj1;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column RESUME_XNZW.RESUME_ZZHYJ
	 * 
	 * @mbggenerated
	 */
	private String resumeZzhyj;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column RESUME_XNZW.RESUME_ADDTIME
	 * 
	 * @mbggenerated
	 */
	private Date resumeAddtime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column RESUME_XNZW.RESUME_DELFLAG
	 * 
	 * @mbggenerated
	 */
	private Long resumeDelflag;

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column RESUME_XNZW.RESUME_XNZWID
	 * 
	 * @return the value of RESUME_XNZW.RESUME_XNZWID
	 * 
	 * @mbggenerated
	 */
	public String getResumeXnzwid()
	{
		return resumeXnzwid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column RESUME_XNZW.RESUME_XNZWID
	 * 
	 * @param resumeXnzwid
	 *            the value for RESUME_XNZW.RESUME_XNZWID
	 * 
	 * @mbggenerated
	 */
	public void setResumeXnzwid(String resumeXnzwid)
	{
		this.resumeXnzwid = resumeXnzwid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column RESUME_XNZW.RESUME_ID
	 * 
	 * @return the value of RESUME_XNZW.RESUME_ID
	 * 
	 * @mbggenerated
	 */
	public String getResumeId()
	{
		return resumeId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column RESUME_XNZW.RESUME_ID
	 * 
	 * @param resumeId
	 *            the value for RESUME_XNZW.RESUME_ID
	 * 
	 * @mbggenerated
	 */
	public void setResumeId(String resumeId)
	{
		this.resumeId = resumeId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column RESUME_XNZW.RESUME_XNZWMC
	 * 
	 * @return the value of RESUME_XNZW.RESUME_XNZWMC
	 * 
	 * @mbggenerated
	 */
	public String getResumeXnzwmc()
	{
		return resumeXnzwmc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column RESUME_XNZW.RESUME_XNZWMC
	 * 
	 * @param resumeXnzwmc
	 *            the value for RESUME_XNZW.RESUME_XNZWMC
	 * 
	 * @mbggenerated
	 */
	public void setResumeXnzwmc(String resumeXnzwmc)
	{
		this.resumeXnzwmc = resumeXnzwmc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column RESUME_XNZW.RESUME_RZSJ
	 * 
	 * @return the value of RESUME_XNZW.RESUME_RZSJ
	 * 
	 * @mbggenerated
	 */
	public String getResumeRzsj()
	{
		return resumeRzsj;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column RESUME_XNZW.RESUME_RZSJ
	 * 
	 * @param resumeRzsj
	 *            the value for RESUME_XNZW.RESUME_RZSJ
	 * 
	 * @mbggenerated
	 */
	public void setResumeRzsj(String resumeRzsj)
	{
		this.resumeRzsj = resumeRzsj;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column RESUME_XNZW.RESUME_RZSJ1
	 * 
	 * @return the value of RESUME_XNZW.RESUME_RZSJ1
	 * 
	 * @mbggenerated
	 */
	public String getResumeRzsj1()
	{
		return resumeRzsj1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column RESUME_XNZW.RESUME_RZSJ1
	 * 
	 * @param resumeRzsj1
	 *            the value for RESUME_XNZW.RESUME_RZSJ1
	 * 
	 * @mbggenerated
	 */
	public void setResumeRzsj1(String resumeRzsj1)
	{
		this.resumeRzsj1 = resumeRzsj1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column RESUME_XNZW.RESUME_ZZHYJ
	 * 
	 * @return the value of RESUME_XNZW.RESUME_ZZHYJ
	 * 
	 * @mbggenerated
	 */
	public String getResumeZzhyj()
	{
		return resumeZzhyj;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column RESUME_XNZW.RESUME_ZZHYJ
	 * 
	 * @param resumeZzhyj
	 *            the value for RESUME_XNZW.RESUME_ZZHYJ
	 * 
	 * @mbggenerated
	 */
	public void setResumeZzhyj(String resumeZzhyj)
	{
		this.resumeZzhyj = resumeZzhyj;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column RESUME_XNZW.RESUME_ADDTIME
	 * 
	 * @return the value of RESUME_XNZW.RESUME_ADDTIME
	 * 
	 * @mbggenerated
	 */
	public Date getResumeAddtime()
	{
		return resumeAddtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column RESUME_XNZW.RESUME_ADDTIME
	 * 
	 * @param resumeAddtime
	 *            the value for RESUME_XNZW.RESUME_ADDTIME
	 * 
	 * @mbggenerated
	 */
	public void setResumeAddtime(Date resumeAddtime)
	{
		this.resumeAddtime = resumeAddtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column RESUME_XNZW.RESUME_DELFLAG
	 * 
	 * @return the value of RESUME_XNZW.RESUME_DELFLAG
	 * 
	 * @mbggenerated
	 */
	public Long getResumeDelflag()
	{
		return resumeDelflag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column RESUME_XNZW.RESUME_DELFLAG
	 * 
	 * @param resumeDelflag
	 *            the value for RESUME_XNZW.RESUME_DELFLAG
	 * 
	 * @mbggenerated
	 */
	public void setResumeDelflag(Long resumeDelflag)
	{
		this.resumeDelflag = resumeDelflag;
	}
}