package com.ttgis.recruit.domain;

import java.io.Serializable;
import java.util.Date;

public class Resume_jyjl implements Serializable
{
	private static final long serialVersionUID = -5519399727431035845L;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column RESUME_JYJL.RESUME_JYJLID
	 * 
	 * @mbggenerated
	 */
	private String resumeJyjlid;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column RESUME_JYJL.RESUME_ID
	 * 
	 * @mbggenerated
	 */
	private String resumeId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column RESUME_JYJL.RESUME_JDSJ
	 * 
	 * @mbggenerated
	 */
	private String resumeJdsj;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column RESUME_JYJL.RESUME_JDSJ1
	 * 
	 * @mbggenerated
	 */
	private String resumeJdsj1;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column RESUME_JYJL.RESUME_XXMC
	 * 
	 * @mbggenerated
	 */
	private String resumeXxmc;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column RESUME_JYJL.RESUME_ZYL
	 * 
	 * @mbggenerated
	 */
	private String resumeZyl;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column RESUME_JYJL.RESUME_ZY
	 * 
	 * @mbggenerated
	 */
	private String resumeZy;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column RESUME_JYJL.RESUME_XL
	 * 
	 * @mbggenerated
	 */
	private String resumeXl;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column RESUME_JYJL.RESUME_ZYMS
	 * 
	 * @mbggenerated
	 */
	private String resumeZyms;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column RESUME_JYJL.RESUME_XXCJ
	 * 
	 * @mbggenerated
	 */
	private Date resumeAddtime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column RESUME_JYJL.RESUME_DELFLAG
	 * 
	 * @mbggenerated
	 */
	private long resumeDelflag;

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column RESUME_JYJL.RESUME_JYJLID
	 * 
	 * @return the value of RESUME_JYJL.RESUME_JYJLID
	 * 
	 * @mbggenerated
	 */

	private String resumeYxpm;
	private String resumeBjpm;

	public String getResumeYxpm()
	{
		return resumeYxpm;
	}

	public void setResumeYxpm(String resumeYxpm)
	{
		this.resumeYxpm = resumeYxpm;
	}

	public String getResumeBjpm()
	{
		return resumeBjpm;
	}

	public void setResumeBjpm(String resumeBjpm)
	{
		this.resumeBjpm = resumeBjpm;
	}

	public String getResumeJyjlid()
	{
		return resumeJyjlid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column RESUME_JYJL.RESUME_JYJLID
	 * 
	 * @param resumeJyjlid
	 *            the value for RESUME_JYJL.RESUME_JYJLID
	 * 
	 * @mbggenerated
	 */
	public void setResumeJyjlid(String resumeJyjlid)
	{
		this.resumeJyjlid = resumeJyjlid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column RESUME_JYJL.RESUME_ID
	 * 
	 * @return the value of RESUME_JYJL.RESUME_ID
	 * 
	 * @mbggenerated
	 */
	public String getResumeId()
	{
		return resumeId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column RESUME_JYJL.RESUME_ID
	 * 
	 * @param resumeId
	 *            the value for RESUME_JYJL.RESUME_ID
	 * 
	 * @mbggenerated
	 */
	public void setResumeId(String resumeId)
	{
		this.resumeId = resumeId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column RESUME_JYJL.RESUME_JDSJ
	 * 
	 * @return the value of RESUME_JYJL.RESUME_JDSJ
	 * 
	 * @mbggenerated
	 */
	public String getResumeJdsj()
	{
		return resumeJdsj;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column RESUME_JYJL.RESUME_JDSJ
	 * 
	 * @param resumeJdsj
	 *            the value for RESUME_JYJL.RESUME_JDSJ
	 * 
	 * @mbggenerated
	 */
	public void setResumeJdsj(String resumeJdsj)
	{
		this.resumeJdsj = resumeJdsj;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column RESUME_JYJL.RESUME_JDSJ1
	 * 
	 * @return the value of RESUME_JYJL.RESUME_JDSJ1
	 * 
	 * @mbggenerated
	 */
	public String getResumeJdsj1()
	{
		return resumeJdsj1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column RESUME_JYJL.RESUME_JDSJ1
	 * 
	 * @param resumeJdsj1
	 *            the value for RESUME_JYJL.RESUME_JDSJ1
	 * 
	 * @mbggenerated
	 */
	public void setResumeJdsj1(String resumeJdsj1)
	{
		this.resumeJdsj1 = resumeJdsj1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column RESUME_JYJL.RESUME_XXMC
	 * 
	 * @return the value of RESUME_JYJL.RESUME_XXMC
	 * 
	 * @mbggenerated
	 */
	public String getResumeXxmc()
	{
		return resumeXxmc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column RESUME_JYJL.RESUME_XXMC
	 * 
	 * @param resumeXxmc
	 *            the value for RESUME_JYJL.RESUME_XXMC
	 * 
	 * @mbggenerated
	 */
	public void setResumeXxmc(String resumeXxmc)
	{
		this.resumeXxmc = resumeXxmc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column RESUME_JYJL.RESUME_ZYL
	 * 
	 * @return the value of RESUME_JYJL.RESUME_ZYL
	 * 
	 * @mbggenerated
	 */
	public String getResumeZyl()
	{
		return resumeZyl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column RESUME_JYJL.RESUME_ZYL
	 * 
	 * @param resumeZyl
	 *            the value for RESUME_JYJL.RESUME_ZYL
	 * 
	 * @mbggenerated
	 */
	public void setResumeZyl(String resumeZyl)
	{
		this.resumeZyl = resumeZyl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column RESUME_JYJL.RESUME_ZY
	 * 
	 * @return the value of RESUME_JYJL.RESUME_ZY
	 * 
	 * @mbggenerated
	 */
	public String getResumeZy()
	{
		return resumeZy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column RESUME_JYJL.RESUME_ZY
	 * 
	 * @param resumeZy
	 *            the value for RESUME_JYJL.RESUME_ZY
	 * 
	 * @mbggenerated
	 */
	public void setResumeZy(String resumeZy)
	{
		this.resumeZy = resumeZy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column RESUME_JYJL.RESUME_XL
	 * 
	 * @return the value of RESUME_JYJL.RESUME_XL
	 * 
	 * @mbggenerated
	 */
	public String getResumeXl()
	{
		return resumeXl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column RESUME_JYJL.RESUME_XL
	 * 
	 * @param resumeXl
	 *            the value for RESUME_JYJL.RESUME_XL
	 * 
	 * @mbggenerated
	 */
	public void setResumeXl(String resumeXl)
	{
		this.resumeXl = resumeXl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column RESUME_JYJL.RESUME_ZYMS
	 * 
	 * @return the value of RESUME_JYJL.RESUME_ZYMS
	 * 
	 * @mbggenerated
	 */
	public String getResumeZyms()
	{
		return resumeZyms;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column RESUME_JYJL.RESUME_ZYMS
	 * 
	 * @param resumeZyms
	 *            the value for RESUME_JYJL.RESUME_ZYMS
	 * 
	 * @mbggenerated
	 */
	public void setResumeZyms(String resumeZyms)
	{
		this.resumeZyms = resumeZyms;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column RESUME_JYJL.RESUME_XXCJ
	 * 
	 * @return the value of RESUME_JYJL.RESUME_XXCJ
	 * 
	 * @mbggenerated
	 */

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column RESUME_JYJL.RESUME_ADDTIME
	 * 
	 * @return the value of RESUME_JYJL.RESUME_ADDTIME
	 * 
	 * @mbggenerated
	 */
	public Date getResumeAddtime()
	{
		return resumeAddtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column RESUME_JYJL.RESUME_ADDTIME
	 * 
	 * @param resumeAddtime
	 *            the value for RESUME_JYJL.RESUME_ADDTIME
	 * 
	 * @mbggenerated
	 */
	public void setResumeAddtime(Date resumeAddtime)
	{
		this.resumeAddtime = resumeAddtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column RESUME_JYJL.RESUME_DELFLAG
	 * 
	 * @return the value of RESUME_JYJL.RESUME_DELFLAG
	 * 
	 * @mbggenerated
	 */
	public long getResumeDelflag()
	{
		return resumeDelflag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column RESUME_JYJL.RESUME_DELFLAG
	 * 
	 * @param resumeDelflag
	 *            the value for RESUME_JYJL.RESUME_DELFLAG
	 * 
	 * @mbggenerated
	 */
	public void setResumeDelflag(long resumeDelflag)
	{
		this.resumeDelflag = resumeDelflag;
	}
}