package com.ttgis.recruit.domain;

import java.io.Serializable;
import java.util.Date;

public class Resume_sjjl implements Serializable
{
	private static final long serialVersionUID = -595617092877082278L;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column RESUME_SJJL.RESUME_SJJLID
	 * 
	 * @mbggenerated
	 */
	private String resumeSjjlid;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column RESUME_SJJL.RESUME_ID
	 * 
	 * @mbggenerated
	 */
	private String resumeId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column RESUME_SJJL.RESUME_SJMC
	 * 
	 * @mbggenerated
	 */
	private String resumeSjmc;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column RESUME_SJJL.RESUME_SJSJ
	 * 
	 * @mbggenerated
	 */
	private String resumeSjsj;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column RESUME_SJJL.RESUME_SJSJ1
	 * 
	 * @mbggenerated
	 */
	private String resumeSjsj1;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column RESUME_SJJL.RESUME_SJMS
	 * 
	 * @mbggenerated
	 */
	private String resumeSjms;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column RESUME_SJJL.RESUME_ADDTIME
	 * 
	 * @mbggenerated
	 */
	private Date resumeAddtime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column RESUME_SJJL.RESUME_DELFLAG
	 * 
	 * @mbggenerated
	 */
	private Long resumeDelflag;

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column RESUME_SJJL.RESUME_SJJLID
	 * 
	 * @return the value of RESUME_SJJL.RESUME_SJJLID
	 * 
	 * @mbggenerated
	 */
	public String getResumeSjjlid()
	{
		return resumeSjjlid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column RESUME_SJJL.RESUME_SJJLID
	 * 
	 * @param resumeSjjlid
	 *            the value for RESUME_SJJL.RESUME_SJJLID
	 * 
	 * @mbggenerated
	 */
	public void setResumeSjjlid(String resumeSjjlid)
	{
		this.resumeSjjlid = resumeSjjlid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column RESUME_SJJL.RESUME_ID
	 * 
	 * @return the value of RESUME_SJJL.RESUME_ID
	 * 
	 * @mbggenerated
	 */
	public String getResumeId()
	{
		return resumeId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column RESUME_SJJL.RESUME_ID
	 * 
	 * @param resumeId
	 *            the value for RESUME_SJJL.RESUME_ID
	 * 
	 * @mbggenerated
	 */
	public void setResumeId(String resumeId)
	{
		this.resumeId = resumeId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column RESUME_SJJL.RESUME_SJMC
	 * 
	 * @return the value of RESUME_SJJL.RESUME_SJMC
	 * 
	 * @mbggenerated
	 */
	public String getResumeSjmc()
	{
		return resumeSjmc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column RESUME_SJJL.RESUME_SJMC
	 * 
	 * @param resumeSjmc
	 *            the value for RESUME_SJJL.RESUME_SJMC
	 * 
	 * @mbggenerated
	 */
	public void setResumeSjmc(String resumeSjmc)
	{
		this.resumeSjmc = resumeSjmc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column RESUME_SJJL.RESUME_SJSJ
	 * 
	 * @return the value of RESUME_SJJL.RESUME_SJSJ
	 * 
	 * @mbggenerated
	 */
	public String getResumeSjsj()
	{
		return resumeSjsj;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column RESUME_SJJL.RESUME_SJSJ
	 * 
	 * @param resumeSjsj
	 *            the value for RESUME_SJJL.RESUME_SJSJ
	 * 
	 * @mbggenerated
	 */
	public void setResumeSjsj(String resumeSjsj)
	{
		this.resumeSjsj = resumeSjsj;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column RESUME_SJJL.RESUME_SJSJ1
	 * 
	 * @return the value of RESUME_SJJL.RESUME_SJSJ1
	 * 
	 * @mbggenerated
	 */
	public String getResumeSjsj1()
	{
		return resumeSjsj1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column RESUME_SJJL.RESUME_SJSJ1
	 * 
	 * @param resumeSjsj1
	 *            the value for RESUME_SJJL.RESUME_SJSJ1
	 * 
	 * @mbggenerated
	 */
	public void setResumeSjsj1(String resumeSjsj1)
	{
		this.resumeSjsj1 = resumeSjsj1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column RESUME_SJJL.RESUME_SJMS
	 * 
	 * @return the value of RESUME_SJJL.RESUME_SJMS
	 * 
	 * @mbggenerated
	 */
	public String getResumeSjms()
	{
		return resumeSjms;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column RESUME_SJJL.RESUME_SJMS
	 * 
	 * @param resumeSjms
	 *            the value for RESUME_SJJL.RESUME_SJMS
	 * 
	 * @mbggenerated
	 */
	public void setResumeSjms(String resumeSjms)
	{
		this.resumeSjms = resumeSjms;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column RESUME_SJJL.RESUME_ADDTIME
	 * 
	 * @return the value of RESUME_SJJL.RESUME_ADDTIME
	 * 
	 * @mbggenerated
	 */
	public Date getResumeAddtime()
	{
		return resumeAddtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column RESUME_SJJL.RESUME_ADDTIME
	 * 
	 * @param resumeAddtime
	 *            the value for RESUME_SJJL.RESUME_ADDTIME
	 * 
	 * @mbggenerated
	 */
	public void setResumeAddtime(Date resumeAddtime)
	{
		this.resumeAddtime = resumeAddtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column RESUME_SJJL.RESUME_DELFLAG
	 * 
	 * @return the value of RESUME_SJJL.RESUME_DELFLAG
	 * 
	 * @mbggenerated
	 */
	public Long getResumeDelflag()
	{
		return resumeDelflag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column RESUME_SJJL.RESUME_DELFLAG
	 * 
	 * @param resumeDelflag
	 *            the value for RESUME_SJJL.RESUME_DELFLAG
	 * 
	 * @mbggenerated
	 */
	public void setResumeDelflag(Long resumeDelflag)
	{
		this.resumeDelflag = resumeDelflag;
	}
}