package com.ttgis.recruit.domain;

import java.io.Serializable;
import java.util.Date;

public class Resume_gzjl implements Serializable
{
	private static final long serialVersionUID = -4036137712941841104L;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column RESUME_GZJL.RESUME_GZJLID
	 * 
	 * @mbggenerated
	 */
	private String resumeGzjlid;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column RESUME_GZJL.RESUME_ID
	 * 
	 * @mbggenerated
	 */
	private String resumeId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column RESUME_GZJL.RESUME_GZGS
	 * 
	 * @mbggenerated
	 */
	private String resumeGzgs;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column RESUME_GZJL.RESUME_GZCS
	 * 
	 * @mbggenerated
	 */
	private String resumeGzcs;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column RESUME_GZJL.RESUME_GZBM
	 * 
	 * @mbggenerated
	 */
	private String resumeGzbm;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column RESUME_GZJL.RESUME_GZZW
	 * 
	 * @mbggenerated
	 */
	private String resumeGzzw;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column RESUME_GZJL.RESUME_GZHY
	 * 
	 * @mbggenerated
	 */
	private String resumeGzhy;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column RESUME_GZJL.RESUME_GZSJ
	 * 
	 * @mbggenerated
	 */
	private String resumeGzsj;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column RESUME_GZJL.RESUME_GZSJ1
	 * 
	 * @mbggenerated
	 */
	private String resumeGzsj1;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column RESUME_GZJL.RESUME_GZMS
	 * 
	 * @mbggenerated
	 */
	private String resumeGzms;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column RESUME_GZJL.RESUME_ADDTIME
	 * 
	 * @mbggenerated
	 */
	private Date resumeAddtime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column RESUME_GZJL.RESUME_DELFLAG
	 * 
	 * @mbggenerated
	 */
	private Long resumeDelflag;

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column RESUME_GZJL.RESUME_GZJLID
	 * 
	 * @return the value of RESUME_GZJL.RESUME_GZJLID
	 * 
	 * @mbggenerated
	 */
	public String getResumeGzjlid()
	{
		return resumeGzjlid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column RESUME_GZJL.RESUME_GZJLID
	 * 
	 * @param resumeGzjlid
	 *            the value for RESUME_GZJL.RESUME_GZJLID
	 * 
	 * @mbggenerated
	 */
	public void setResumeGzjlid(String resumeGzjlid)
	{
		this.resumeGzjlid = resumeGzjlid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column RESUME_GZJL.RESUME_ID
	 * 
	 * @return the value of RESUME_GZJL.RESUME_ID
	 * 
	 * @mbggenerated
	 */
	public String getResumeId()
	{
		return resumeId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column RESUME_GZJL.RESUME_ID
	 * 
	 * @param resumeId
	 *            the value for RESUME_GZJL.RESUME_ID
	 * 
	 * @mbggenerated
	 */
	public void setResumeId(String resumeId)
	{
		this.resumeId = resumeId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column RESUME_GZJL.RESUME_GZGS
	 * 
	 * @return the value of RESUME_GZJL.RESUME_GZGS
	 * 
	 * @mbggenerated
	 */
	public String getResumeGzgs()
	{
		return resumeGzgs;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column RESUME_GZJL.RESUME_GZGS
	 * 
	 * @param resumeGzgs
	 *            the value for RESUME_GZJL.RESUME_GZGS
	 * 
	 * @mbggenerated
	 */
	public void setResumeGzgs(String resumeGzgs)
	{
		this.resumeGzgs = resumeGzgs;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column RESUME_GZJL.RESUME_GZCS
	 * 
	 * @return the value of RESUME_GZJL.RESUME_GZCS
	 * 
	 * @mbggenerated
	 */
	public String getResumeGzcs()
	{
		return resumeGzcs;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column RESUME_GZJL.RESUME_GZCS
	 * 
	 * @param resumeGzcs
	 *            the value for RESUME_GZJL.RESUME_GZCS
	 * 
	 * @mbggenerated
	 */
	public void setResumeGzcs(String resumeGzcs)
	{
		this.resumeGzcs = resumeGzcs;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column RESUME_GZJL.RESUME_GZBM
	 * 
	 * @return the value of RESUME_GZJL.RESUME_GZBM
	 * 
	 * @mbggenerated
	 */
	public String getResumeGzbm()
	{
		return resumeGzbm;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column RESUME_GZJL.RESUME_GZBM
	 * 
	 * @param resumeGzbm
	 *            the value for RESUME_GZJL.RESUME_GZBM
	 * 
	 * @mbggenerated
	 */
	public void setResumeGzbm(String resumeGzbm)
	{
		this.resumeGzbm = resumeGzbm;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column RESUME_GZJL.RESUME_GZZW
	 * 
	 * @return the value of RESUME_GZJL.RESUME_GZZW
	 * 
	 * @mbggenerated
	 */
	public String getResumeGzzw()
	{
		return resumeGzzw;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column RESUME_GZJL.RESUME_GZZW
	 * 
	 * @param resumeGzzw
	 *            the value for RESUME_GZJL.RESUME_GZZW
	 * 
	 * @mbggenerated
	 */
	public void setResumeGzzw(String resumeGzzw)
	{
		this.resumeGzzw = resumeGzzw;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column RESUME_GZJL.RESUME_GZHY
	 * 
	 * @return the value of RESUME_GZJL.RESUME_GZHY
	 * 
	 * @mbggenerated
	 */
	public String getResumeGzhy()
	{
		return resumeGzhy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column RESUME_GZJL.RESUME_GZHY
	 * 
	 * @param resumeGzhy
	 *            the value for RESUME_GZJL.RESUME_GZHY
	 * 
	 * @mbggenerated
	 */
	public void setResumeGzhy(String resumeGzhy)
	{
		this.resumeGzhy = resumeGzhy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column RESUME_GZJL.RESUME_GZSJ
	 * 
	 * @return the value of RESUME_GZJL.RESUME_GZSJ
	 * 
	 * @mbggenerated
	 */
	public String getResumeGzsj()
	{
		return resumeGzsj;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column RESUME_GZJL.RESUME_GZSJ
	 * 
	 * @param resumeGzsj
	 *            the value for RESUME_GZJL.RESUME_GZSJ
	 * 
	 * @mbggenerated
	 */
	public void setResumeGzsj(String resumeGzsj)
	{
		this.resumeGzsj = resumeGzsj;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column RESUME_GZJL.RESUME_GZSJ1
	 * 
	 * @return the value of RESUME_GZJL.RESUME_GZSJ1
	 * 
	 * @mbggenerated
	 */
	public String getResumeGzsj1()
	{
		return resumeGzsj1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column RESUME_GZJL.RESUME_GZSJ1
	 * 
	 * @param resumeGzsj1
	 *            the value for RESUME_GZJL.RESUME_GZSJ1
	 * 
	 * @mbggenerated
	 */
	public void setResumeGzsj1(String resumeGzsj1)
	{
		this.resumeGzsj1 = resumeGzsj1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column RESUME_GZJL.RESUME_GZMS
	 * 
	 * @return the value of RESUME_GZJL.RESUME_GZMS
	 * 
	 * @mbggenerated
	 */
	public String getResumeGzms()
	{
		return resumeGzms;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column RESUME_GZJL.RESUME_GZMS
	 * 
	 * @param resumeGzms
	 *            the value for RESUME_GZJL.RESUME_GZMS
	 * 
	 * @mbggenerated
	 */
	public void setResumeGzms(String resumeGzms)
	{
		this.resumeGzms = resumeGzms;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column RESUME_GZJL.RESUME_ADDTIME
	 * 
	 * @return the value of RESUME_GZJL.RESUME_ADDTIME
	 * 
	 * @mbggenerated
	 */
	public Date getResumeAddtime()
	{
		return resumeAddtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column RESUME_GZJL.RESUME_ADDTIME
	 * 
	 * @param resumeAddtime
	 *            the value for RESUME_GZJL.RESUME_ADDTIME
	 * 
	 * @mbggenerated
	 */
	public void setResumeAddtime(Date resumeAddtime)
	{
		this.resumeAddtime = resumeAddtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column RESUME_GZJL.RESUME_DELFLAG
	 * 
	 * @return the value of RESUME_GZJL.RESUME_DELFLAG
	 * 
	 * @mbggenerated
	 */
	public Long getResumeDelflag()
	{
		return resumeDelflag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column RESUME_GZJL.RESUME_DELFLAG
	 * 
	 * @param resumeDelflag
	 *            the value for RESUME_GZJL.RESUME_DELFLAG
	 * 
	 * @mbggenerated
	 */
	public void setResumeDelflag(Long resumeDelflag)
	{
		this.resumeDelflag = resumeDelflag;
	}
}