package com.ttgis.recruit.domain;

import java.io.Serializable;
import java.util.Date;

public class Resume_sx implements Serializable
{
	private static final long serialVersionUID = -4893125440542491698L;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column RESUME_SX.RESUME_SXID
	 * 
	 * @mbggenerated
	 */
	private String resumeSxid;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column RESUME_SX.RESUME_ID
	 * 
	 * @mbggenerated
	 */
	private String resumeId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column RESUME_SX.RESUME_SXGS
	 * 
	 * @mbggenerated
	 */
	private String resumeSxgs;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column RESUME_SX.RESUME_SXCS
	 * 
	 * @mbggenerated
	 */
	private String resumeSxcs;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column RESUME_SX.RESUME_SXBM
	 * 
	 * @mbggenerated
	 */
	private String resumeSxbm;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column RESUME_SX.RESUME_SXZW
	 * 
	 * @mbggenerated
	 */
	private String resumeSxzw;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column RESUME_SX.RESUME_SXHY
	 * 
	 * @mbggenerated
	 */
	private String resumeSxhy;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column RESUME_SX.RESUME_SXSJ
	 * 
	 * @mbggenerated
	 */
	private String resumeSxsj;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column RESUME_SX.RESUME_SXSJ1
	 * 
	 * @mbggenerated
	 */
	private String resumeSxsj1;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column RESUME_SX.RESUME_SXMS
	 * 
	 * @mbggenerated
	 */
	private String resumeSxms;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column RESUME_SX.RESUME_ADDTIME
	 * 
	 * @mbggenerated
	 */
	private Date resumeAddtime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column RESUME_SX.RESUME_DELFLAG
	 * 
	 * @mbggenerated
	 */
	private Long resumeDelflag;

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column RESUME_SX.RESUME_SXID
	 * 
	 * @return the value of RESUME_SX.RESUME_SXID
	 * 
	 * @mbggenerated
	 */
	public String getResumeSxid()
	{
		return resumeSxid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column RESUME_SX.RESUME_SXID
	 * 
	 * @param resumeSxid
	 *            the value for RESUME_SX.RESUME_SXID
	 * 
	 * @mbggenerated
	 */
	public void setResumeSxid(String resumeSxid)
	{
		this.resumeSxid = resumeSxid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column RESUME_SX.RESUME_ID
	 * 
	 * @return the value of RESUME_SX.RESUME_ID
	 * 
	 * @mbggenerated
	 */
	public String getResumeId()
	{
		return resumeId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column RESUME_SX.RESUME_ID
	 * 
	 * @param resumeId
	 *            the value for RESUME_SX.RESUME_ID
	 * 
	 * @mbggenerated
	 */
	public void setResumeId(String resumeId)
	{
		this.resumeId = resumeId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column RESUME_SX.RESUME_SXGS
	 * 
	 * @return the value of RESUME_SX.RESUME_SXGS
	 * 
	 * @mbggenerated
	 */
	public String getResumeSxgs()
	{
		return resumeSxgs;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column RESUME_SX.RESUME_SXGS
	 * 
	 * @param resumeSxgs
	 *            the value for RESUME_SX.RESUME_SXGS
	 * 
	 * @mbggenerated
	 */
	public void setResumeSxgs(String resumeSxgs)
	{
		this.resumeSxgs = resumeSxgs;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column RESUME_SX.RESUME_SXCS
	 * 
	 * @return the value of RESUME_SX.RESUME_SXCS
	 * 
	 * @mbggenerated
	 */
	public String getResumeSxcs()
	{
		return resumeSxcs;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column RESUME_SX.RESUME_SXCS
	 * 
	 * @param resumeSxcs
	 *            the value for RESUME_SX.RESUME_SXCS
	 * 
	 * @mbggenerated
	 */
	public void setResumeSxcs(String resumeSxcs)
	{
		this.resumeSxcs = resumeSxcs;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column RESUME_SX.RESUME_SXBM
	 * 
	 * @return the value of RESUME_SX.RESUME_SXBM
	 * 
	 * @mbggenerated
	 */
	public String getResumeSxbm()
	{
		return resumeSxbm;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column RESUME_SX.RESUME_SXBM
	 * 
	 * @param resumeSxbm
	 *            the value for RESUME_SX.RESUME_SXBM
	 * 
	 * @mbggenerated
	 */
	public void setResumeSxbm(String resumeSxbm)
	{
		this.resumeSxbm = resumeSxbm;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column RESUME_SX.RESUME_SXZW
	 * 
	 * @return the value of RESUME_SX.RESUME_SXZW
	 * 
	 * @mbggenerated
	 */
	public String getResumeSxzw()
	{
		return resumeSxzw;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column RESUME_SX.RESUME_SXZW
	 * 
	 * @param resumeSxzw
	 *            the value for RESUME_SX.RESUME_SXZW
	 * 
	 * @mbggenerated
	 */
	public void setResumeSxzw(String resumeSxzw)
	{
		this.resumeSxzw = resumeSxzw;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column RESUME_SX.RESUME_SXHY
	 * 
	 * @return the value of RESUME_SX.RESUME_SXHY
	 * 
	 * @mbggenerated
	 */
	public String getResumeSxhy()
	{
		return resumeSxhy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column RESUME_SX.RESUME_SXHY
	 * 
	 * @param resumeSxhy
	 *            the value for RESUME_SX.RESUME_SXHY
	 * 
	 * @mbggenerated
	 */
	public void setResumeSxhy(String resumeSxhy)
	{
		this.resumeSxhy = resumeSxhy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column RESUME_SX.RESUME_SXSJ
	 * 
	 * @return the value of RESUME_SX.RESUME_SXSJ
	 * 
	 * @mbggenerated
	 */
	public String getResumeSxsj()
	{
		return resumeSxsj;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column RESUME_SX.RESUME_SXSJ
	 * 
	 * @param resumeSxsj
	 *            the value for RESUME_SX.RESUME_SXSJ
	 * 
	 * @mbggenerated
	 */
	public void setResumeSxsj(String resumeSxsj)
	{
		this.resumeSxsj = resumeSxsj;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column RESUME_SX.RESUME_SXSJ1
	 * 
	 * @return the value of RESUME_SX.RESUME_SXSJ1
	 * 
	 * @mbggenerated
	 */
	public String getResumeSxsj1()
	{
		return resumeSxsj1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column RESUME_SX.RESUME_SXSJ1
	 * 
	 * @param resumeSxsj1
	 *            the value for RESUME_SX.RESUME_SXSJ1
	 * 
	 * @mbggenerated
	 */
	public void setResumeSxsj1(String resumeSxsj1)
	{
		this.resumeSxsj1 = resumeSxsj1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column RESUME_SX.RESUME_SXMS
	 * 
	 * @return the value of RESUME_SX.RESUME_SXMS
	 * 
	 * @mbggenerated
	 */
	public String getResumeSxms()
	{
		return resumeSxms;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column RESUME_SX.RESUME_SXMS
	 * 
	 * @param resumeSxms
	 *            the value for RESUME_SX.RESUME_SXMS
	 * 
	 * @mbggenerated
	 */
	public void setResumeSxms(String resumeSxms)
	{
		this.resumeSxms = resumeSxms;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column RESUME_SX.RESUME_ADDTIME
	 * 
	 * @return the value of RESUME_SX.RESUME_ADDTIME
	 * 
	 * @mbggenerated
	 */
	public Date getResumeAddtime()
	{
		return resumeAddtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column RESUME_SX.RESUME_ADDTIME
	 * 
	 * @param resumeAddtime
	 *            the value for RESUME_SX.RESUME_ADDTIME
	 * 
	 * @mbggenerated
	 */
	public void setResumeAddtime(Date resumeAddtime)
	{
		this.resumeAddtime = resumeAddtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column RESUME_SX.RESUME_DELFLAG
	 * 
	 * @return the value of RESUME_SX.RESUME_DELFLAG
	 * 
	 * @mbggenerated
	 */
	public Long getResumeDelflag()
	{
		return resumeDelflag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column RESUME_SX.RESUME_DELFLAG
	 * 
	 * @param resumeDelflag
	 *            the value for RESUME_SX.RESUME_DELFLAG
	 * 
	 * @mbggenerated
	 */
	public void setResumeDelflag(Long resumeDelflag)
	{
		this.resumeDelflag = resumeDelflag;
	}
}