package com.ttgis.recruit.domain;

import java.io.Serializable;
import java.util.Date;

public class Resume_xnjl implements Serializable
{
	private static final long serialVersionUID = 9152698075254230854L;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column RESUME_XNJL.RESUME_XNJLID
	 * 
	 * @mbggenerated
	 */
	private String resumeXnjlid;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column RESUME_XNJL.RESUME_ID
	 * 
	 * @mbggenerated
	 */
	private String resumeId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column RESUME_XNJL.RESUME_JXMC
	 * 
	 * @mbggenerated
	 */
	private String resumeJxmc;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column RESUME_XNJL.RESUME_HJSJ
	 * 
	 * @mbggenerated
	 */
	private String resumeHjsj;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column RESUME_XNJL.RESUME_JLSM
	 * 
	 * @mbggenerated
	 */
	private String resumeJlsm;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column RESUME_XNJL.RESUME_ADDTIME
	 * 
	 * @mbggenerated
	 */
	private Date resumeAddtime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column RESUME_XNJL.RESUME_DELFLAG
	 * 
	 * @mbggenerated
	 */
	private Long resumeDelflag;

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column RESUME_XNJL.RESUME_XNJLID
	 * 
	 * @return the value of RESUME_XNJL.RESUME_XNJLID
	 * 
	 * @mbggenerated
	 */
	public String getResumeXnjlid()
	{
		return resumeXnjlid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column RESUME_XNJL.RESUME_XNJLID
	 * 
	 * @param resumeXnjlid
	 *            the value for RESUME_XNJL.RESUME_XNJLID
	 * 
	 * @mbggenerated
	 */
	public void setResumeXnjlid(String resumeXnjlid)
	{
		this.resumeXnjlid = resumeXnjlid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column RESUME_XNJL.RESUME_ID
	 * 
	 * @return the value of RESUME_XNJL.RESUME_ID
	 * 
	 * @mbggenerated
	 */
	public String getResumeId()
	{
		return resumeId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column RESUME_XNJL.RESUME_ID
	 * 
	 * @param resumeId
	 *            the value for RESUME_XNJL.RESUME_ID
	 * 
	 * @mbggenerated
	 */
	public void setResumeId(String resumeId)
	{
		this.resumeId = resumeId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column RESUME_XNJL.RESUME_JXMC
	 * 
	 * @return the value of RESUME_XNJL.RESUME_JXMC
	 * 
	 * @mbggenerated
	 */
	public String getResumeJxmc()
	{
		return resumeJxmc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column RESUME_XNJL.RESUME_JXMC
	 * 
	 * @param resumeJxmc
	 *            the value for RESUME_XNJL.RESUME_JXMC
	 * 
	 * @mbggenerated
	 */
	public void setResumeJxmc(String resumeJxmc)
	{
		this.resumeJxmc = resumeJxmc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column RESUME_XNJL.RESUME_HJSJ
	 * 
	 * @return the value of RESUME_XNJL.RESUME_HJSJ
	 * 
	 * @mbggenerated
	 */
	public String getResumeHjsj()
	{
		return resumeHjsj;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column RESUME_XNJL.RESUME_HJSJ
	 * 
	 * @param resumeHjsj
	 *            the value for RESUME_XNJL.RESUME_HJSJ
	 * 
	 * @mbggenerated
	 */
	public void setResumeHjsj(String resumeHjsj)
	{
		this.resumeHjsj = resumeHjsj;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column RESUME_XNJL.RESUME_JLSM
	 * 
	 * @return the value of RESUME_XNJL.RESUME_JLSM
	 * 
	 * @mbggenerated
	 */
	public String getResumeJlsm()
	{
		return resumeJlsm;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column RESUME_XNJL.RESUME_JLSM
	 * 
	 * @param resumeJlsm
	 *            the value for RESUME_XNJL.RESUME_JLSM
	 * 
	 * @mbggenerated
	 */
	public void setResumeJlsm(String resumeJlsm)
	{
		this.resumeJlsm = resumeJlsm;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column RESUME_XNJL.RESUME_ADDTIME
	 * 
	 * @return the value of RESUME_XNJL.RESUME_ADDTIME
	 * 
	 * @mbggenerated
	 */
	public Date getResumeAddtime()
	{
		return resumeAddtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column RESUME_XNJL.RESUME_ADDTIME
	 * 
	 * @param resumeAddtime
	 *            the value for RESUME_XNJL.RESUME_ADDTIME
	 * 
	 * @mbggenerated
	 */
	public void setResumeAddtime(Date resumeAddtime)
	{
		this.resumeAddtime = resumeAddtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column RESUME_XNJL.RESUME_DELFLAG
	 * 
	 * @return the value of RESUME_XNJL.RESUME_DELFLAG
	 * 
	 * @mbggenerated
	 */
	public Long getResumeDelflag()
	{
		return resumeDelflag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column RESUME_XNJL.RESUME_DELFLAG
	 * 
	 * @param resumeDelflag
	 *            the value for RESUME_XNJL.RESUME_DELFLAG
	 * 
	 * @mbggenerated
	 */
	public void setResumeDelflag(Long resumeDelflag)
	{
		this.resumeDelflag = resumeDelflag;
	}
}