package com.ttgis.recruit.domain;

import java.io.Serializable;
import java.util.Date;

public class Resume_yynl implements Serializable
{
	private static final long serialVersionUID = -8161966422098530170L;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column RESUME_YYNL.RESUME_YYNLID
	 * 
	 * @mbggenerated
	 */
	private String resumeYynlid;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column RESUME_YYNL.RESUME_ID
	 * 
	 * @mbggenerated
	 */
	private String resumeId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column RESUME_YYNL.RESUME_YYLB
	 * 
	 * @mbggenerated
	 */
	private String resumeYylb;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column RESUME_YYNL.RESUME_TSNL
	 * 
	 * @mbggenerated
	 */
	private String resumeTsnl;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column RESUME_YYNL.RESUME_DXNL
	 * 
	 * @mbggenerated
	 */
	private String resumeDxnl;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column RESUME_YYNL.RESUME_DJKS
	 * 
	 * @mbggenerated
	 */
	private String resumeDjks;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column RESUME_YYNL.RESUME_YYFS
	 * 
	 * @mbggenerated
	 */
	private String resumeYyfs;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column RESUME_YYNL.RESUME_ADDTIME
	 * 
	 * @mbggenerated
	 */
	private Date resumeAddtime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column RESUME_YYNL.RESUME_DELFLAG
	 * 
	 * @mbggenerated
	 */
	private Long resumeDelflag;

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column RESUME_YYNL.RESUME_YYNLID
	 * 
	 * @return the value of RESUME_YYNL.RESUME_YYNLID
	 * 
	 * @mbggenerated
	 */
	public String getResumeYynlid()
	{
		return resumeYynlid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column RESUME_YYNL.RESUME_YYNLID
	 * 
	 * @param resumeYynlid
	 *            the value for RESUME_YYNL.RESUME_YYNLID
	 * 
	 * @mbggenerated
	 */
	public void setResumeYynlid(String resumeYynlid)
	{
		this.resumeYynlid = resumeYynlid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column RESUME_YYNL.RESUME_ID
	 * 
	 * @return the value of RESUME_YYNL.RESUME_ID
	 * 
	 * @mbggenerated
	 */
	public String getResumeId()
	{
		return resumeId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column RESUME_YYNL.RESUME_ID
	 * 
	 * @param resumeId
	 *            the value for RESUME_YYNL.RESUME_ID
	 * 
	 * @mbggenerated
	 */
	public void setResumeId(String resumeId)
	{
		this.resumeId = resumeId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column RESUME_YYNL.RESUME_YYLB
	 * 
	 * @return the value of RESUME_YYNL.RESUME_YYLB
	 * 
	 * @mbggenerated
	 */
	public String getResumeYylb()
	{
		return resumeYylb;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column RESUME_YYNL.RESUME_YYLB
	 * 
	 * @param resumeYylb
	 *            the value for RESUME_YYNL.RESUME_YYLB
	 * 
	 * @mbggenerated
	 */
	public void setResumeYylb(String resumeYylb)
	{
		this.resumeYylb = resumeYylb;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column RESUME_YYNL.RESUME_TSNL
	 * 
	 * @return the value of RESUME_YYNL.RESUME_TSNL
	 * 
	 * @mbggenerated
	 */
	public String getResumeTsnl()
	{
		return resumeTsnl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column RESUME_YYNL.RESUME_TSNL
	 * 
	 * @param resumeTsnl
	 *            the value for RESUME_YYNL.RESUME_TSNL
	 * 
	 * @mbggenerated
	 */
	public void setResumeTsnl(String resumeTsnl)
	{
		this.resumeTsnl = resumeTsnl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column RESUME_YYNL.RESUME_DXNL
	 * 
	 * @return the value of RESUME_YYNL.RESUME_DXNL
	 * 
	 * @mbggenerated
	 */
	public String getResumeDxnl()
	{
		return resumeDxnl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column RESUME_YYNL.RESUME_DXNL
	 * 
	 * @param resumeDxnl
	 *            the value for RESUME_YYNL.RESUME_DXNL
	 * 
	 * @mbggenerated
	 */
	public void setResumeDxnl(String resumeDxnl)
	{
		this.resumeDxnl = resumeDxnl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column RESUME_YYNL.RESUME_DJKS
	 * 
	 * @return the value of RESUME_YYNL.RESUME_DJKS
	 * 
	 * @mbggenerated
	 */
	public String getResumeDjks()
	{
		return resumeDjks;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column RESUME_YYNL.RESUME_DJKS
	 * 
	 * @param resumeDjks
	 *            the value for RESUME_YYNL.RESUME_DJKS
	 * 
	 * @mbggenerated
	 */
	public void setResumeDjks(String resumeDjks)
	{
		this.resumeDjks = resumeDjks;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column RESUME_YYNL.RESUME_YYFS
	 * 
	 * @return the value of RESUME_YYNL.RESUME_YYFS
	 * 
	 * @mbggenerated
	 */
	public String getResumeYyfs()
	{
		return resumeYyfs;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column RESUME_YYNL.RESUME_YYFS
	 * 
	 * @param resumeYyfs
	 *            the value for RESUME_YYNL.RESUME_YYFS
	 * 
	 * @mbggenerated
	 */
	public void setResumeYyfs(String resumeYyfs)
	{
		this.resumeYyfs = resumeYyfs;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column RESUME_YYNL.RESUME_ADDTIME
	 * 
	 * @return the value of RESUME_YYNL.RESUME_ADDTIME
	 * 
	 * @mbggenerated
	 */
	public Date getResumeAddtime()
	{
		return resumeAddtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column RESUME_YYNL.RESUME_ADDTIME
	 * 
	 * @param resumeAddtime
	 *            the value for RESUME_YYNL.RESUME_ADDTIME
	 * 
	 * @mbggenerated
	 */
	public void setResumeAddtime(Date resumeAddtime)
	{
		this.resumeAddtime = resumeAddtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column RESUME_YYNL.RESUME_DELFLAG
	 * 
	 * @return the value of RESUME_YYNL.RESUME_DELFLAG
	 * 
	 * @mbggenerated
	 */
	public Long getResumeDelflag()
	{
		return resumeDelflag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column RESUME_YYNL.RESUME_DELFLAG
	 * 
	 * @param resumeDelflag
	 *            the value for RESUME_YYNL.RESUME_DELFLAG
	 * 
	 * @mbggenerated
	 */
	public void setResumeDelflag(Long resumeDelflag)
	{
		this.resumeDelflag = resumeDelflag;
	}
}