package com.ttgis.recruit.domain;

import java.io.Serializable;
import java.util.Date;

public class Resume_xmjy implements Serializable
{
	private static final long serialVersionUID = -3245428849361229751L;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column RESUME_XMJY.RESUME_XMJYID
	 * 
	 * @mbggenerated
	 */
	private String resumeXmjyid;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column RESUME_XMJY.RESUME_ID
	 * 
	 * @mbggenerated
	 */
	private String resumeId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column RESUME_XMJY.RESUME_XMMC
	 * 
	 * @mbggenerated
	 */
	private String resumeXmmc;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column RESUME_XMJY.RESUME_TDGM
	 * 
	 * @mbggenerated
	 */
	private String resumeTdgm;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column RESUME_XMJY.RESUME_XMJJ
	 * 
	 * @mbggenerated
	 */
	private String resumeXmjj;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column RESUME_XMJY.RESUME_XMJS
	 * 
	 * @mbggenerated
	 */
	private String resumeXmjs;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column RESUME_XMJY.RESUME_CYSJ
	 * 
	 * @mbggenerated
	 */
	private String resumeCysj;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column RESUME_XMJY.RESUME_CYSJ1
	 * 
	 * @mbggenerated
	 */
	private String resumeCysj1;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column RESUME_XMJY.RESUME_XMCG
	 * 
	 * @mbggenerated
	 */
	private String resumeXmcg;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column RESUME_XMJY.RESUME_ADDTIME
	 * 
	 * @mbggenerated
	 */
	private Date resumeAddtime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column RESUME_XMJY.RESUME_DELFLAG
	 * 
	 * @mbggenerated
	 */
	private Long resumeDelflag;

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column RESUME_XMJY.RESUME_XMJYID
	 * 
	 * @return the value of RESUME_XMJY.RESUME_XMJYID
	 * 
	 * @mbggenerated
	 */
	public String getResumeXmjyid()
	{
		return resumeXmjyid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column RESUME_XMJY.RESUME_XMJYID
	 * 
	 * @param resumeXmjyid
	 *            the value for RESUME_XMJY.RESUME_XMJYID
	 * 
	 * @mbggenerated
	 */
	public void setResumeXmjyid(String resumeXmjyid)
	{
		this.resumeXmjyid = resumeXmjyid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column RESUME_XMJY.RESUME_ID
	 * 
	 * @return the value of RESUME_XMJY.RESUME_ID
	 * 
	 * @mbggenerated
	 */
	public String getResumeId()
	{
		return resumeId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column RESUME_XMJY.RESUME_ID
	 * 
	 * @param resumeId
	 *            the value for RESUME_XMJY.RESUME_ID
	 * 
	 * @mbggenerated
	 */
	public void setResumeId(String resumeId)
	{
		this.resumeId = resumeId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column RESUME_XMJY.RESUME_XMMC
	 * 
	 * @return the value of RESUME_XMJY.RESUME_XMMC
	 * 
	 * @mbggenerated
	 */
	public String getResumeXmmc()
	{
		return resumeXmmc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column RESUME_XMJY.RESUME_XMMC
	 * 
	 * @param resumeXmmc
	 *            the value for RESUME_XMJY.RESUME_XMMC
	 * 
	 * @mbggenerated
	 */
	public void setResumeXmmc(String resumeXmmc)
	{
		this.resumeXmmc = resumeXmmc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column RESUME_XMJY.RESUME_TDGM
	 * 
	 * @return the value of RESUME_XMJY.RESUME_TDGM
	 * 
	 * @mbggenerated
	 */
	public String getResumeTdgm()
	{
		return resumeTdgm;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column RESUME_XMJY.RESUME_TDGM
	 * 
	 * @param resumeTdgm
	 *            the value for RESUME_XMJY.RESUME_TDGM
	 * 
	 * @mbggenerated
	 */
	public void setResumeTdgm(String resumeTdgm)
	{
		this.resumeTdgm = resumeTdgm;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column RESUME_XMJY.RESUME_XMJJ
	 * 
	 * @return the value of RESUME_XMJY.RESUME_XMJJ
	 * 
	 * @mbggenerated
	 */
	public String getResumeXmjj()
	{
		return resumeXmjj;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column RESUME_XMJY.RESUME_XMJJ
	 * 
	 * @param resumeXmjj
	 *            the value for RESUME_XMJY.RESUME_XMJJ
	 * 
	 * @mbggenerated
	 */
	public void setResumeXmjj(String resumeXmjj)
	{
		this.resumeXmjj = resumeXmjj;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column RESUME_XMJY.RESUME_XMJS
	 * 
	 * @return the value of RESUME_XMJY.RESUME_XMJS
	 * 
	 * @mbggenerated
	 */
	public String getResumeXmjs()
	{
		return resumeXmjs;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column RESUME_XMJY.RESUME_XMJS
	 * 
	 * @param resumeXmjs
	 *            the value for RESUME_XMJY.RESUME_XMJS
	 * 
	 * @mbggenerated
	 */
	public void setResumeXmjs(String resumeXmjs)
	{
		this.resumeXmjs = resumeXmjs;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column RESUME_XMJY.RESUME_CYSJ
	 * 
	 * @return the value of RESUME_XMJY.RESUME_CYSJ
	 * 
	 * @mbggenerated
	 */
	public String getResumeCysj()
	{
		return resumeCysj;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column RESUME_XMJY.RESUME_CYSJ
	 * 
	 * @param resumeCysj
	 *            the value for RESUME_XMJY.RESUME_CYSJ
	 * 
	 * @mbggenerated
	 */
	public void setResumeCysj(String resumeCysj)
	{
		this.resumeCysj = resumeCysj;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column RESUME_XMJY.RESUME_CYSJ1
	 * 
	 * @return the value of RESUME_XMJY.RESUME_CYSJ1
	 * 
	 * @mbggenerated
	 */
	public String getResumeCysj1()
	{
		return resumeCysj1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column RESUME_XMJY.RESUME_CYSJ1
	 * 
	 * @param resumeCysj1
	 *            the value for RESUME_XMJY.RESUME_CYSJ1
	 * 
	 * @mbggenerated
	 */
	public void setResumeCysj1(String resumeCysj1)
	{
		this.resumeCysj1 = resumeCysj1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column RESUME_XMJY.RESUME_XMCG
	 * 
	 * @return the value of RESUME_XMJY.RESUME_XMCG
	 * 
	 * @mbggenerated
	 */
	public String getResumeXmcg()
	{
		return resumeXmcg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column RESUME_XMJY.RESUME_XMCG
	 * 
	 * @param resumeXmcg
	 *            the value for RESUME_XMJY.RESUME_XMCG
	 * 
	 * @mbggenerated
	 */
	public void setResumeXmcg(String resumeXmcg)
	{
		this.resumeXmcg = resumeXmcg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column RESUME_XMJY.RESUME_ADDTIME
	 * 
	 * @return the value of RESUME_XMJY.RESUME_ADDTIME
	 * 
	 * @mbggenerated
	 */
	public Date getResumeAddtime()
	{
		return resumeAddtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column RESUME_XMJY.RESUME_ADDTIME
	 * 
	 * @param resumeAddtime
	 *            the value for RESUME_XMJY.RESUME_ADDTIME
	 * 
	 * @mbggenerated
	 */
	public void setResumeAddtime(Date resumeAddtime)
	{
		this.resumeAddtime = resumeAddtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column RESUME_XMJY.RESUME_DELFLAG
	 * 
	 * @return the value of RESUME_XMJY.RESUME_DELFLAG
	 * 
	 * @mbggenerated
	 */
	public Long getResumeDelflag()
	{
		return resumeDelflag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column RESUME_XMJY.RESUME_DELFLAG
	 * 
	 * @param resumeDelflag
	 *            the value for RESUME_XMJY.RESUME_DELFLAG
	 * 
	 * @mbggenerated
	 */
	public void setResumeDelflag(Long resumeDelflag)
	{
		this.resumeDelflag = resumeDelflag;
	}
}