package com.ttgis.recruit.domain;

import java.io.Serializable;
import java.util.Date;

public class Resume_pxjl implements Serializable
{
	private static final long serialVersionUID = -4442438954282586641L;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column RESUME_PXJL.RESUME_PXJLID
	 * 
	 * @mbggenerated
	 */
	private String resumePxjlid;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column RESUME_PXJL.RESUME_ID
	 * 
	 * @mbggenerated
	 */
	private String resumeId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column RESUME_PXJL.RESUME_PXMC
	 * 
	 * @mbggenerated
	 */
	private String resumePxmc;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column RESUME_PXJL.RESUME_PXJG
	 * 
	 * @mbggenerated
	 */
	private String resumePxjg;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column RESUME_PXJL.RESUME_PXSJ
	 * 
	 * @mbggenerated
	 */
	private String resumePxsj;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column RESUME_PXJL.RESUME_PXSJ1
	 * 
	 * @mbggenerated
	 */
	private String resumePxsj1;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column RESUME_PXJL.RESUME_PXNR
	 * 
	 * @mbggenerated
	 */
	private String resumePxnr;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column RESUME_PXJL.RESUME_ADDTIME
	 * 
	 * @mbggenerated
	 */
	private Date resumeAddtime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column RESUME_PXJL.RESUME_DELFLAG
	 * 
	 * @mbggenerated
	 */
	private Long resumeDelflag;

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column RESUME_PXJL.RESUME_PXJLID
	 * 
	 * @return the value of RESUME_PXJL.RESUME_PXJLID
	 * 
	 * @mbggenerated
	 */
	public String getResumePxjlid()
	{
		return resumePxjlid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column RESUME_PXJL.RESUME_PXJLID
	 * 
	 * @param resumePxjlid
	 *            the value for RESUME_PXJL.RESUME_PXJLID
	 * 
	 * @mbggenerated
	 */
	public void setResumePxjlid(String resumePxjlid)
	{
		this.resumePxjlid = resumePxjlid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column RESUME_PXJL.RESUME_ID
	 * 
	 * @return the value of RESUME_PXJL.RESUME_ID
	 * 
	 * @mbggenerated
	 */
	public String getResumeId()
	{
		return resumeId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column RESUME_PXJL.RESUME_ID
	 * 
	 * @param resumeId
	 *            the value for RESUME_PXJL.RESUME_ID
	 * 
	 * @mbggenerated
	 */
	public void setResumeId(String resumeId)
	{
		this.resumeId = resumeId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column RESUME_PXJL.RESUME_PXMC
	 * 
	 * @return the value of RESUME_PXJL.RESUME_PXMC
	 * 
	 * @mbggenerated
	 */
	public String getResumePxmc()
	{
		return resumePxmc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column RESUME_PXJL.RESUME_PXMC
	 * 
	 * @param resumePxmc
	 *            the value for RESUME_PXJL.RESUME_PXMC
	 * 
	 * @mbggenerated
	 */
	public void setResumePxmc(String resumePxmc)
	{
		this.resumePxmc = resumePxmc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column RESUME_PXJL.RESUME_PXJG
	 * 
	 * @return the value of RESUME_PXJL.RESUME_PXJG
	 * 
	 * @mbggenerated
	 */
	public String getResumePxjg()
	{
		return resumePxjg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column RESUME_PXJL.RESUME_PXJG
	 * 
	 * @param resumePxjg
	 *            the value for RESUME_PXJL.RESUME_PXJG
	 * 
	 * @mbggenerated
	 */
	public void setResumePxjg(String resumePxjg)
	{
		this.resumePxjg = resumePxjg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column RESUME_PXJL.RESUME_PXSJ
	 * 
	 * @return the value of RESUME_PXJL.RESUME_PXSJ
	 * 
	 * @mbggenerated
	 */
	public String getResumePxsj()
	{
		return resumePxsj;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column RESUME_PXJL.RESUME_PXSJ
	 * 
	 * @param resumePxsj
	 *            the value for RESUME_PXJL.RESUME_PXSJ
	 * 
	 * @mbggenerated
	 */
	public void setResumePxsj(String resumePxsj)
	{
		this.resumePxsj = resumePxsj;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column RESUME_PXJL.RESUME_PXSJ1
	 * 
	 * @return the value of RESUME_PXJL.RESUME_PXSJ1
	 * 
	 * @mbggenerated
	 */
	public String getResumePxsj1()
	{
		return resumePxsj1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column RESUME_PXJL.RESUME_PXSJ1
	 * 
	 * @param resumePxsj1
	 *            the value for RESUME_PXJL.RESUME_PXSJ1
	 * 
	 * @mbggenerated
	 */
	public void setResumePxsj1(String resumePxsj1)
	{
		this.resumePxsj1 = resumePxsj1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column RESUME_PXJL.RESUME_PXNR
	 * 
	 * @return the value of RESUME_PXJL.RESUME_PXNR
	 * 
	 * @mbggenerated
	 */
	public String getResumePxnr()
	{
		return resumePxnr;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column RESUME_PXJL.RESUME_PXNR
	 * 
	 * @param resumePxnr
	 *            the value for RESUME_PXJL.RESUME_PXNR
	 * 
	 * @mbggenerated
	 */
	public void setResumePxnr(String resumePxnr)
	{
		this.resumePxnr = resumePxnr;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column RESUME_PXJL.RESUME_ADDTIME
	 * 
	 * @return the value of RESUME_PXJL.RESUME_ADDTIME
	 * 
	 * @mbggenerated
	 */
	public Date getResumeAddtime()
	{
		return resumeAddtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column RESUME_PXJL.RESUME_ADDTIME
	 * 
	 * @param resumeAddtime
	 *            the value for RESUME_PXJL.RESUME_ADDTIME
	 * 
	 * @mbggenerated
	 */
	public void setResumeAddtime(Date resumeAddtime)
	{
		this.resumeAddtime = resumeAddtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column RESUME_PXJL.RESUME_DELFLAG
	 * 
	 * @return the value of RESUME_PXJL.RESUME_DELFLAG
	 * 
	 * @mbggenerated
	 */
	public Long getResumeDelflag()
	{
		return resumeDelflag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column RESUME_PXJL.RESUME_DELFLAG
	 * 
	 * @param resumeDelflag
	 *            the value for RESUME_PXJL.RESUME_DELFLAG
	 * 
	 * @mbggenerated
	 */
	public void setResumeDelflag(Long resumeDelflag)
	{
		this.resumeDelflag = resumeDelflag;
	}
}