package com.ttgis.recruit.domain;

import java.io.Serializable;
import java.util.Date;

public class Resume_qtxx implements Serializable
{
	private static final long serialVersionUID = -1906318405407987066L;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column RESUME_QTXX.RESUME_QTXXID
	 * 
	 * @mbggenerated
	 */
	private String resumeQtxxid;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column RESUME_QTXX.RESUME_ID
	 * 
	 * @mbggenerated
	 */
	private String resumeId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column RESUME_QTXX.RESUME_QTXXLB1
	 * 
	 * @mbggenerated
	 */
	private String resumeQtxxlb1;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column RESUME_QTXX.RESUME_QTXXLB2
	 * 
	 * @mbggenerated
	 */
	private String resumeQtxxlb2;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column RESUME_QTXX.RESUME_XXMS
	 * 
	 * @mbggenerated
	 */
	private String resumeXxms;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column RESUME_QTXX.RESUME_ADDTIME
	 * 
	 * @mbggenerated
	 */
	private Date resumeAddtime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column RESUME_QTXX.RESUME_DELFLAG
	 * 
	 * @mbggenerated
	 */
	private Long resumeDelflag;

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column RESUME_QTXX.RESUME_QTXXID
	 * 
	 * @return the value of RESUME_QTXX.RESUME_QTXXID
	 * 
	 * @mbggenerated
	 */
	public String getResumeQtxxid()
	{
		return resumeQtxxid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column RESUME_QTXX.RESUME_QTXXID
	 * 
	 * @param resumeQtxxid
	 *            the value for RESUME_QTXX.RESUME_QTXXID
	 * 
	 * @mbggenerated
	 */
	public void setResumeQtxxid(String resumeQtxxid)
	{
		this.resumeQtxxid = resumeQtxxid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column RESUME_QTXX.RESUME_ID
	 * 
	 * @return the value of RESUME_QTXX.RESUME_ID
	 * 
	 * @mbggenerated
	 */
	public String getResumeId()
	{
		return resumeId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column RESUME_QTXX.RESUME_ID
	 * 
	 * @param resumeId
	 *            the value for RESUME_QTXX.RESUME_ID
	 * 
	 * @mbggenerated
	 */
	public void setResumeId(String resumeId)
	{
		this.resumeId = resumeId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column RESUME_QTXX.RESUME_QTXXLB1
	 * 
	 * @return the value of RESUME_QTXX.RESUME_QTXXLB1
	 * 
	 * @mbggenerated
	 */
	public String getResumeQtxxlb1()
	{
		return resumeQtxxlb1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column RESUME_QTXX.RESUME_QTXXLB1
	 * 
	 * @param resumeQtxxlb1
	 *            the value for RESUME_QTXX.RESUME_QTXXLB1
	 * 
	 * @mbggenerated
	 */
	public void setResumeQtxxlb1(String resumeQtxxlb1)
	{
		this.resumeQtxxlb1 = resumeQtxxlb1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column RESUME_QTXX.RESUME_QTXXLB2
	 * 
	 * @return the value of RESUME_QTXX.RESUME_QTXXLB2
	 * 
	 * @mbggenerated
	 */
	public String getResumeQtxxlb2()
	{
		return resumeQtxxlb2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column RESUME_QTXX.RESUME_QTXXLB2
	 * 
	 * @param resumeQtxxlb2
	 *            the value for RESUME_QTXX.RESUME_QTXXLB2
	 * 
	 * @mbggenerated
	 */
	public void setResumeQtxxlb2(String resumeQtxxlb2)
	{
		this.resumeQtxxlb2 = resumeQtxxlb2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column RESUME_QTXX.RESUME_XXMS
	 * 
	 * @return the value of RESUME_QTXX.RESUME_XXMS
	 * 
	 * @mbggenerated
	 */
	public String getResumeXxms()
	{
		return resumeXxms;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column RESUME_QTXX.RESUME_XXMS
	 * 
	 * @param resumeXxms
	 *            the value for RESUME_QTXX.RESUME_XXMS
	 * 
	 * @mbggenerated
	 */
	public void setResumeXxms(String resumeXxms)
	{
		this.resumeXxms = resumeXxms;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column RESUME_QTXX.RESUME_ADDTIME
	 * 
	 * @return the value of RESUME_QTXX.RESUME_ADDTIME
	 * 
	 * @mbggenerated
	 */
	public Date getResumeAddtime()
	{
		return resumeAddtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column RESUME_QTXX.RESUME_ADDTIME
	 * 
	 * @param resumeAddtime
	 *            the value for RESUME_QTXX.RESUME_ADDTIME
	 * 
	 * @mbggenerated
	 */
	public void setResumeAddtime(Date resumeAddtime)
	{
		this.resumeAddtime = resumeAddtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column RESUME_QTXX.RESUME_DELFLAG
	 * 
	 * @return the value of RESUME_QTXX.RESUME_DELFLAG
	 * 
	 * @mbggenerated
	 */
	public Long getResumeDelflag()
	{
		return resumeDelflag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column RESUME_QTXX.RESUME_DELFLAG
	 * 
	 * @param resumeDelflag
	 *            the value for RESUME_QTXX.RESUME_DELFLAG
	 * 
	 * @mbggenerated
	 */
	public void setResumeDelflag(Long resumeDelflag)
	{
		this.resumeDelflag = resumeDelflag;
	}
}