package com.ttgis.recruit.domain;

import java.io.Serializable;
import java.util.Date;

public class Sqzt implements Serializable
{
	private static final long serialVersionUID = -4414021244750756486L;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column SQZT.SQZT_ID
	 * 
	 * @mbggenerated
	 */
	private String sqztId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column SQZT.ZZJG_ID
	 * 
	 * @mbggenerated
	 */
	private String zzjgId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column SQZT.SQZT_SQDW
	 * 
	 * @mbggenerated
	 */
	private String sqztSqdw;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column SQZT.SQZT_SQBM
	 * 
	 * @mbggenerated
	 */
	private String sqztSqbm;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column SQZT.SQZT_SQGW
	 * 
	 * @mbggenerated
	 */
	private String sqztSqgw;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column SQZT.SQZT_JLTJZK
	 * 
	 * @mbggenerated
	 */
	private String sqztJltjzk;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column SQZT.SQZT_SHJG
	 * 
	 * @mbggenerated
	 */
	private String sqztShjg;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column SQZT.SQZT_XXTZ
	 * 
	 * @mbggenerated
	 */
	private String sqztXxtz;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column SQZT.SQZT_USER
	 * 
	 * @mbggenerated
	 */
	private String sqztUser;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column SQZT.SQZT_ADDTIME
	 * 
	 * @mbggenerated
	 */
	private Date sqztAddtime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column SQZT.SQZT_CHECKUSER
	 * 
	 * @mbggenerated
	 */
	private String sqztCheckuser;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column SQZT.SQZT_CHECKTIME
	 * 
	 * @mbggenerated
	 */
	private Date sqztChecktime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column SQZT.SQZT_DELFLAG
	 * 
	 * @mbggenerated
	 */
	private Long sqztDelflag;

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column SQZT.SQZT_ID
	 * 
	 * @return the value of SQZT.SQZT_ID
	 * 
	 * @mbggenerated
	 */
	public String getSqztId()
	{
		return sqztId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column SQZT.SQZT_ID
	 * 
	 * @param sqztId
	 *            the value for SQZT.SQZT_ID
	 * 
	 * @mbggenerated
	 */
	public void setSqztId(String sqztId)
	{
		this.sqztId = sqztId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column SQZT.ZZJG_ID
	 * 
	 * @return the value of SQZT.ZZJG_ID
	 * 
	 * @mbggenerated
	 */
	public String getZzjgId()
	{
		return zzjgId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column SQZT.ZZJG_ID
	 * 
	 * @param zzjgId
	 *            the value for SQZT.ZZJG_ID
	 * 
	 * @mbggenerated
	 */
	public void setZzjgId(String zzjgId)
	{
		this.zzjgId = zzjgId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column SQZT.SQZT_SQDW
	 * 
	 * @return the value of SQZT.SQZT_SQDW
	 * 
	 * @mbggenerated
	 */
	public String getSqztSqdw()
	{
		return sqztSqdw;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column SQZT.SQZT_SQDW
	 * 
	 * @param sqztSqdw
	 *            the value for SQZT.SQZT_SQDW
	 * 
	 * @mbggenerated
	 */
	public void setSqztSqdw(String sqztSqdw)
	{
		this.sqztSqdw = sqztSqdw;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column SQZT.SQZT_SQBM
	 * 
	 * @return the value of SQZT.SQZT_SQBM
	 * 
	 * @mbggenerated
	 */
	public String getSqztSqbm()
	{
		return sqztSqbm;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column SQZT.SQZT_SQBM
	 * 
	 * @param sqztSqbm
	 *            the value for SQZT.SQZT_SQBM
	 * 
	 * @mbggenerated
	 */
	public void setSqztSqbm(String sqztSqbm)
	{
		this.sqztSqbm = sqztSqbm;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column SQZT.SQZT_SQGW
	 * 
	 * @return the value of SQZT.SQZT_SQGW
	 * 
	 * @mbggenerated
	 */
	public String getSqztSqgw()
	{
		return sqztSqgw;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column SQZT.SQZT_SQGW
	 * 
	 * @param sqztSqgw
	 *            the value for SQZT.SQZT_SQGW
	 * 
	 * @mbggenerated
	 */
	public void setSqztSqgw(String sqztSqgw)
	{
		this.sqztSqgw = sqztSqgw;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column SQZT.SQZT_JLTJZK
	 * 
	 * @return the value of SQZT.SQZT_JLTJZK
	 * 
	 * @mbggenerated
	 */
	public String getSqztJltjzk()
	{
		return sqztJltjzk;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column SQZT.SQZT_JLTJZK
	 * 
	 * @param sqztJltjzk
	 *            the value for SQZT.SQZT_JLTJZK
	 * 
	 * @mbggenerated
	 */
	public void setSqztJltjzk(String sqztJltjzk)
	{
		this.sqztJltjzk = sqztJltjzk;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column SQZT.SQZT_SHJG
	 * 
	 * @return the value of SQZT.SQZT_SHJG
	 * 
	 * @mbggenerated
	 */
	public String getSqztShjg()
	{
		return sqztShjg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column SQZT.SQZT_SHJG
	 * 
	 * @param sqztShjg
	 *            the value for SQZT.SQZT_SHJG
	 * 
	 * @mbggenerated
	 */
	public void setSqztShjg(String sqztShjg)
	{
		this.sqztShjg = sqztShjg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column SQZT.SQZT_XXTZ
	 * 
	 * @return the value of SQZT.SQZT_XXTZ
	 * 
	 * @mbggenerated
	 */
	public String getSqztXxtz()
	{
		return sqztXxtz;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column SQZT.SQZT_XXTZ
	 * 
	 * @param sqztXxtz
	 *            the value for SQZT.SQZT_XXTZ
	 * 
	 * @mbggenerated
	 */
	public void setSqztXxtz(String sqztXxtz)
	{
		this.sqztXxtz = sqztXxtz;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column SQZT.SQZT_USER
	 * 
	 * @return the value of SQZT.SQZT_USER
	 * 
	 * @mbggenerated
	 */
	public String getSqztUser()
	{
		return sqztUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column SQZT.SQZT_USER
	 * 
	 * @param sqztUser
	 *            the value for SQZT.SQZT_USER
	 * 
	 * @mbggenerated
	 */
	public void setSqztUser(String sqztUser)
	{
		this.sqztUser = sqztUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column SQZT.SQZT_ADDTIME
	 * 
	 * @return the value of SQZT.SQZT_ADDTIME
	 * 
	 * @mbggenerated
	 */
	public Date getSqztAddtime()
	{
		return sqztAddtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column SQZT.SQZT_ADDTIME
	 * 
	 * @param sqztAddtime
	 *            the value for SQZT.SQZT_ADDTIME
	 * 
	 * @mbggenerated
	 */
	public void setSqztAddtime(Date sqztAddtime)
	{
		this.sqztAddtime = sqztAddtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column SQZT.SQZT_CHECKUSER
	 * 
	 * @return the value of SQZT.SQZT_CHECKUSER
	 * 
	 * @mbggenerated
	 */
	public String getSqztCheckuser()
	{
		return sqztCheckuser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column SQZT.SQZT_CHECKUSER
	 * 
	 * @param sqztCheckuser
	 *            the value for SQZT.SQZT_CHECKUSER
	 * 
	 * @mbggenerated
	 */
	public void setSqztCheckuser(String sqztCheckuser)
	{
		this.sqztCheckuser = sqztCheckuser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column SQZT.SQZT_CHECKTIME
	 * 
	 * @return the value of SQZT.SQZT_CHECKTIME
	 * 
	 * @mbggenerated
	 */
	public Date getSqztChecktime()
	{
		return sqztChecktime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column SQZT.SQZT_CHECKTIME
	 * 
	 * @param sqztChecktime
	 *            the value for SQZT.SQZT_CHECKTIME
	 * 
	 * @mbggenerated
	 */
	public void setSqztChecktime(Date sqztChecktime)
	{
		this.sqztChecktime = sqztChecktime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column SQZT.SQZT_DELFLAG
	 * 
	 * @return the value of SQZT.SQZT_DELFLAG
	 * 
	 * @mbggenerated
	 */
	public Long getSqztDelflag()
	{
		return sqztDelflag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column SQZT.SQZT_DELFLAG
	 * 
	 * @param sqztDelflag
	 *            the value for SQZT.SQZT_DELFLAG
	 * 
	 * @mbggenerated
	 */
	public void setSqztDelflag(Long sqztDelflag)
	{
		this.sqztDelflag = sqztDelflag;
	}
}