package com.ttgis.recruit.domain;

import java.io.Serializable;

public class Sysmsg implements Serializable
{
	private static final long serialVersionUID = 6438773941991595971L;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column SYSMSG.SYSMSG_ID
	 * 
	 * @mbggenerated
	 */
	private String sysmsgId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column SYSMSG.SYSMSG_NAME
	 * 
	 * @mbggenerated
	 */
	private String sysmsgName;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column SYSMSG.SYSMSG_USER_ID
	 * 
	 * @mbggenerated
	 */
	private String sysmsgUserId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column SYSMSG.SYSMSG_ZZJG_ID
	 * 
	 * @mbggenerated
	 */
	private String sysmsgZzjgId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column SYSMSG.SYSMSG_TYPE
	 * 
	 * @mbggenerated
	 */
	private String sysmsgType;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column SYSMSG.SYSMSG_CONTENT
	 * 
	 * @mbggenerated
	 */
	private String sysmsgContent;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column SYSMSG.SYSMSG_ADDTIME
	 * 
	 * @mbggenerated
	 */
	private String sysmsgAddtime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column SYSMSG.SYSMSG_DELFLAG
	 * 
	 * @mbggenerated
	 */
	private Integer sysmsgDelflag;

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column SYSMSG.SYSMSG_ID
	 * 
	 * @return the value of SYSMSG.SYSMSG_ID
	 * 
	 * @mbggenerated
	 */
	public String getSysmsgId()
	{
		return sysmsgId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column SYSMSG.SYSMSG_ID
	 * 
	 * @param sysmsgId
	 *            the value for SYSMSG.SYSMSG_ID
	 * 
	 * @mbggenerated
	 */
	public void setSysmsgId(String sysmsgId)
	{
		this.sysmsgId = sysmsgId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column SYSMSG.SYSMSG_NAME
	 * 
	 * @return the value of SYSMSG.SYSMSG_NAME
	 * 
	 * @mbggenerated
	 */
	public String getSysmsgName()
	{
		return sysmsgName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column SYSMSG.SYSMSG_NAME
	 * 
	 * @param sysmsgName
	 *            the value for SYSMSG.SYSMSG_NAME
	 * 
	 * @mbggenerated
	 */
	public void setSysmsgName(String sysmsgName)
	{
		this.sysmsgName = sysmsgName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column SYSMSG.SYSMSG_USER_ID
	 * 
	 * @return the value of SYSMSG.SYSMSG_USER_ID
	 * 
	 * @mbggenerated
	 */
	public String getSysmsgUserId()
	{
		return sysmsgUserId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column SYSMSG.SYSMSG_USER_ID
	 * 
	 * @param sysmsgUserId
	 *            the value for SYSMSG.SYSMSG_USER_ID
	 * 
	 * @mbggenerated
	 */
	public void setSysmsgUserId(String sysmsgUserId)
	{
		this.sysmsgUserId = sysmsgUserId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column SYSMSG.SYSMSG_ZZJG_ID
	 * 
	 * @return the value of SYSMSG.SYSMSG_ZZJG_ID
	 * 
	 * @mbggenerated
	 */
	public String getSysmsgZzjgId()
	{
		return sysmsgZzjgId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column SYSMSG.SYSMSG_ZZJG_ID
	 * 
	 * @param sysmsgZzjgId
	 *            the value for SYSMSG.SYSMSG_ZZJG_ID
	 * 
	 * @mbggenerated
	 */
	public void setSysmsgZzjgId(String sysmsgZzjgId)
	{
		this.sysmsgZzjgId = sysmsgZzjgId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column SYSMSG.SYSMSG_TYPE
	 * 
	 * @return the value of SYSMSG.SYSMSG_TYPE
	 * 
	 * @mbggenerated
	 */
	public String getSysmsgType()
	{
		return sysmsgType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column SYSMSG.SYSMSG_TYPE
	 * 
	 * @param sysmsgType
	 *            the value for SYSMSG.SYSMSG_TYPE
	 * 
	 * @mbggenerated
	 */
	public void setSysmsgType(String sysmsgType)
	{
		this.sysmsgType = sysmsgType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column SYSMSG.SYSMSG_CONTENT
	 * 
	 * @return the value of SYSMSG.SYSMSG_CONTENT
	 * 
	 * @mbggenerated
	 */
	public String getSysmsgContent()
	{
		return sysmsgContent;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column SYSMSG.SYSMSG_CONTENT
	 * 
	 * @param sysmsgContent
	 *            the value for SYSMSG.SYSMSG_CONTENT
	 * 
	 * @mbggenerated
	 */
	public void setSysmsgContent(String sysmsgContent)
	{
		this.sysmsgContent = sysmsgContent;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column SYSMSG.SYSMSG_ADDTIME
	 * 
	 * @return the value of SYSMSG.SYSMSG_ADDTIME
	 * 
	 * @mbggenerated
	 */
	public String getSysmsgAddtime()
	{
		return sysmsgAddtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column SYSMSG.SYSMSG_ADDTIME
	 * 
	 * @param sysmsgAddtime
	 *            the value for SYSMSG.SYSMSG_ADDTIME
	 * 
	 * @mbggenerated
	 */
	public void setSysmsgAddtime(String sysmsgAddtime)
	{
		this.sysmsgAddtime = sysmsgAddtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column SYSMSG.SYSMSG_DELFLAG
	 * 
	 * @return the value of SYSMSG.SYSMSG_DELFLAG
	 * 
	 * @mbggenerated
	 */
	public Integer getSysmsgDelflag()
	{
		return sysmsgDelflag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column SYSMSG.SYSMSG_DELFLAG
	 * 
	 * @param sysmsgDelflag
	 *            the value for SYSMSG.SYSMSG_DELFLAG
	 * 
	 * @mbggenerated
	 */
	public void setSysmsgDelflag(Integer sysmsgDelflag)
	{
		this.sysmsgDelflag = sysmsgDelflag;
	}
}