package com.ttgis.recruit.domain;

public class TkglWithBLOBs extends Tkgl
{

	/**
	 * 
	 */
	private static final long serialVersionUID = -3964945428701051244L;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column TKGL.TKGL_STTG
	 * 
	 * @mbggenerated
	 */
	private String tkglSttg;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column TKGL.TKGL_STXX_A
	 * 
	 * @mbggenerated
	 */
	private String tkglStxxA;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column TKGL.TKGL_STXX_B
	 * 
	 * @mbggenerated
	 */
	private String tkglStxxB;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column TKGL.TKGL_STXX_C
	 * 
	 * @mbggenerated
	 */
	private String tkglStxxC;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column TKGL.TKGL_STXX_D
	 * 
	 * @mbggenerated
	 */
	private String tkglStxxD;

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column TKGL.TKGL_STTG
	 * 
	 * @return the value of TKGL.TKGL_STTG
	 * @mbggenerated
	 */
	public String getTkglSttg()
	{
		return tkglSttg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column TKGL.TKGL_STTG
	 * 
	 * @param tkglSttg
	 *            the value for TKGL.TKGL_STTG
	 * @mbggenerated
	 */
	public void setTkglSttg(String tkglSttg)
	{
		this.tkglSttg = tkglSttg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column TKGL.TKGL_STXX_A
	 * 
	 * @return the value of TKGL.TKGL_STXX_A
	 * @mbggenerated
	 */
	public String getTkglStxxA()
	{
		return tkglStxxA;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column TKGL.TKGL_STXX_A
	 * 
	 * @param tkglStxxA
	 *            the value for TKGL.TKGL_STXX_A
	 * @mbggenerated
	 */
	public void setTkglStxxA(String tkglStxxA)
	{
		this.tkglStxxA = tkglStxxA;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column TKGL.TKGL_STXX_B
	 * 
	 * @return the value of TKGL.TKGL_STXX_B
	 * @mbggenerated
	 */
	public String getTkglStxxB()
	{
		return tkglStxxB;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column TKGL.TKGL_STXX_B
	 * 
	 * @param tkglStxxB
	 *            the value for TKGL.TKGL_STXX_B
	 * @mbggenerated
	 */
	public void setTkglStxxB(String tkglStxxB)
	{
		this.tkglStxxB = tkglStxxB;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column TKGL.TKGL_STXX_C
	 * 
	 * @return the value of TKGL.TKGL_STXX_C
	 * @mbggenerated
	 */
	public String getTkglStxxC()
	{
		return tkglStxxC;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column TKGL.TKGL_STXX_C
	 * 
	 * @param tkglStxxC
	 *            the value for TKGL.TKGL_STXX_C
	 * @mbggenerated
	 */
	public void setTkglStxxC(String tkglStxxC)
	{
		this.tkglStxxC = tkglStxxC;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column TKGL.TKGL_STXX_D
	 * 
	 * @return the value of TKGL.TKGL_STXX_D
	 * @mbggenerated
	 */
	public String getTkglStxxD()
	{
		return tkglStxxD;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column TKGL.TKGL_STXX_D
	 * 
	 * @param tkglStxxD
	 *            the value for TKGL.TKGL_STXX_D
	 * @mbggenerated
	 */
	public void setTkglStxxD(String tkglStxxD)
	{
		this.tkglStxxD = tkglStxxD;
	}
}