package com.ttgis.recruit.domain;

import java.io.Serializable;

public class tkglFxt implements Serializable
{
	private static final long serialVersionUID = 364777841595848338L;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column TKGL_FXT.ID
	 * 
	 * @mbggenerated
	 */
	private String id;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column TKGL_FXT.STBH
	 * 
	 * @mbggenerated
	 */
	private String stbh;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column TKGL_FXT.STLX
	 * 
	 * @mbggenerated
	 */
	private String stlx;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column TKGL_FXT.STDA
	 * 
	 * @mbggenerated
	 */
	private String stda;

	private String sttg;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column TKGL_FXT.STXXA
	 * 
	 * @mbggenerated
	 */
	private String stxxa;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column TKGL_FXT.STXXB
	 * 
	 * @mbggenerated
	 */
	private String stxxb;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column TKGL_FXT.STXXC
	 * 
	 * @mbggenerated
	 */
	private String stxxc;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column TKGL_FXT.STXXD
	 * 
	 * @mbggenerated
	 */
	private String stxxd;

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column TKGL_FXT.ID
	 * 
	 * @return the value of TKGL_FXT.ID
	 * 
	 * @mbggenerated
	 */
	public String getId()
	{
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column TKGL_FXT.ID
	 * 
	 * @param id
	 *            the value for TKGL_FXT.ID
	 * 
	 * @mbggenerated
	 */
	public void setId(String id)
	{
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column TKGL_FXT.STBH
	 * 
	 * @return the value of TKGL_FXT.STBH
	 * 
	 * @mbggenerated
	 */
	public String getStbh()
	{
		return stbh;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column TKGL_FXT.STBH
	 * 
	 * @param stbh
	 *            the value for TKGL_FXT.STBH
	 * 
	 * @mbggenerated
	 */
	public void setStbh(String stbh)
	{
		this.stbh = stbh;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column TKGL_FXT.STLX
	 * 
	 * @return the value of TKGL_FXT.STLX
	 * 
	 * @mbggenerated
	 */
	public String getStlx()
	{
		return stlx;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column TKGL_FXT.STLX
	 * 
	 * @param stlx
	 *            the value for TKGL_FXT.STLX
	 * 
	 * @mbggenerated
	 */
	public void setStlx(String stlx)
	{
		this.stlx = stlx;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column TKGL_FXT.STDA
	 * 
	 * @return the value of TKGL_FXT.STDA
	 * 
	 * @mbggenerated
	 */
	public String getStda()
	{
		return stda;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column TKGL_FXT.STDA
	 * 
	 * @param stda
	 *            the value for TKGL_FXT.STDA
	 * 
	 * @mbggenerated
	 */
	public void setStda(String stda)
	{
		this.stda = stda;
	}

	public String getSttg()
	{
		return sttg;
	}

	public void setSttg(String sttg)
	{
		this.sttg = sttg;
	}

	public String getStxxa()
	{
		return stxxa;
	}

	public void setStxxa(String stxxa)
	{
		this.stxxa = stxxa;
	}

	public String getStxxb()
	{
		return stxxb;
	}

	public void setStxxb(String stxxb)
	{
		this.stxxb = stxxb;
	}

	public String getStxxc()
	{
		return stxxc;
	}

	public void setStxxc(String stxxc)
	{
		this.stxxc = stxxc;
	}

	public String getStxxd()
	{
		return stxxd;
	}

	public void setStxxd(String stxxd)
	{
		this.stxxd = stxxd;
	}

}