package com.ttgis.recruit.domain;

import java.io.Serializable;

public class Tlq implements Serializable
{
	private static final long serialVersionUID = -5820513213691128416L;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column TLQ.TLQ_ID
	 * 
	 * @mbggenerated
	 */
	private String tlqId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column TLQ.TLQ_NAME
	 * 
	 * @mbggenerated
	 */
	private String tlqName;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column TLQ.TLQ_ADDTIME
	 * 
	 * @mbggenerated
	 */
	private String tlqAddtime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column TLQ.TLQ_DELFLAG
	 * 
	 * @mbggenerated
	 */
	private Long tlqDelflag;

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column TLQ.TLQ_ID
	 * 
	 * @return the value of TLQ.TLQ_ID
	 * 
	 * @mbggenerated
	 */
	public String getTlqId()
	{
		return tlqId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column TLQ.TLQ_ID
	 * 
	 * @param tlqId
	 *            the value for TLQ.TLQ_ID
	 * 
	 * @mbggenerated
	 */
	public void setTlqId(String tlqId)
	{
		this.tlqId = tlqId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column TLQ.TLQ_NAME
	 * 
	 * @return the value of TLQ.TLQ_NAME
	 * 
	 * @mbggenerated
	 */
	public String getTlqName()
	{
		return tlqName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column TLQ.TLQ_NAME
	 * 
	 * @param tlqName
	 *            the value for TLQ.TLQ_NAME
	 * 
	 * @mbggenerated
	 */
	public void setTlqName(String tlqName)
	{
		this.tlqName = tlqName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column TLQ.TLQ_ADDTIME
	 * 
	 * @return the value of TLQ.TLQ_ADDTIME
	 * 
	 * @mbggenerated
	 */
	public String getTlqAddtime()
	{
		return tlqAddtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column TLQ.TLQ_ADDTIME
	 * 
	 * @param tlqAddtime
	 *            the value for TLQ.TLQ_ADDTIME
	 * 
	 * @mbggenerated
	 */
	public void setTlqAddtime(String tlqAddtime)
	{
		this.tlqAddtime = tlqAddtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column TLQ.TLQ_DELFLAG
	 * 
	 * @return the value of TLQ.TLQ_DELFLAG
	 * 
	 * @mbggenerated
	 */
	public Long getTlqDelflag()
	{
		return tlqDelflag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column TLQ.TLQ_DELFLAG
	 * 
	 * @param tlqDelflag
	 *            the value for TLQ.TLQ_DELFLAG
	 * 
	 * @mbggenerated
	 */
	public void setTlqDelflag(Long tlqDelflag)
	{
		this.tlqDelflag = tlqDelflag;
	}
}