package com.ttgis.recruit.domain;

import java.io.Serializable;
import java.util.Date;

public class Txl implements Serializable
{
	private static final long serialVersionUID = 3109060992663459099L;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column TXL.TXL_ID
	 * 
	 * @mbggenerated
	 */
	private String txlId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column TXL.ZZJG_ID
	 * 
	 * @mbggenerated
	 */
	private String zzjgId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column TXL.TXL_NAME
	 * 
	 * @mbggenerated
	 */
	private String txlName;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column TXL.TXL_EMAIL
	 * 
	 * @mbggenerated
	 */
	private String txlEmail;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column TXL.TXL_DEPARTMENT
	 * 
	 * @mbggenerated
	 */
	private String txlDepartment;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column TXL.TXL_POSITION
	 * 
	 * @mbggenerated
	 */
	private String txlPosition;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column TXL.TXL_ADDTIME
	 * 
	 * @mbggenerated
	 */
	private Date txlAddtime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column TXL.TXL_DELFLAG
	 * 
	 * @mbggenerated
	 */
	private Long txlDelflag;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column TXL.TXL_PHONE
	 * 
	 * @mbggenerated
	 */
	private String txlPhone;

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column TXL.TXL_ID
	 * 
	 * @return the value of TXL.TXL_ID
	 * 
	 * @mbggenerated
	 */
	public String getTxlId()
	{
		return txlId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column TXL.TXL_ID
	 * 
	 * @param txlId
	 *            the value for TXL.TXL_ID
	 * 
	 * @mbggenerated
	 */
	public void setTxlId(String txlId)
	{
		this.txlId = txlId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column TXL.ZZJG_ID
	 * 
	 * @return the value of TXL.ZZJG_ID
	 * 
	 * @mbggenerated
	 */
	public String getZzjgId()
	{
		return zzjgId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column TXL.ZZJG_ID
	 * 
	 * @param zzjgId
	 *            the value for TXL.ZZJG_ID
	 * 
	 * @mbggenerated
	 */
	public void setZzjgId(String zzjgId)
	{
		this.zzjgId = zzjgId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column TXL.TXL_NAME
	 * 
	 * @return the value of TXL.TXL_NAME
	 * 
	 * @mbggenerated
	 */
	public String getTxlName()
	{
		return txlName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column TXL.TXL_NAME
	 * 
	 * @param txlName
	 *            the value for TXL.TXL_NAME
	 * 
	 * @mbggenerated
	 */
	public void setTxlName(String txlName)
	{
		this.txlName = txlName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column TXL.TXL_EMAIL
	 * 
	 * @return the value of TXL.TXL_EMAIL
	 * 
	 * @mbggenerated
	 */
	public String getTxlEmail()
	{
		return txlEmail;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column TXL.TXL_EMAIL
	 * 
	 * @param txlEmail
	 *            the value for TXL.TXL_EMAIL
	 * 
	 * @mbggenerated
	 */
	public void setTxlEmail(String txlEmail)
	{
		this.txlEmail = txlEmail;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column TXL.TXL_DEPARTMENT
	 * 
	 * @return the value of TXL.TXL_DEPARTMENT
	 * 
	 * @mbggenerated
	 */
	public String getTxlDepartment()
	{
		return txlDepartment;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column TXL.TXL_DEPARTMENT
	 * 
	 * @param txlDepartment
	 *            the value for TXL.TXL_DEPARTMENT
	 * 
	 * @mbggenerated
	 */
	public void setTxlDepartment(String txlDepartment)
	{
		this.txlDepartment = txlDepartment;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column TXL.TXL_POSITION
	 * 
	 * @return the value of TXL.TXL_POSITION
	 * 
	 * @mbggenerated
	 */
	public String getTxlPosition()
	{
		return txlPosition;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column TXL.TXL_POSITION
	 * 
	 * @param txlPosition
	 *            the value for TXL.TXL_POSITION
	 * 
	 * @mbggenerated
	 */
	public void setTxlPosition(String txlPosition)
	{
		this.txlPosition = txlPosition;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column TXL.TXL_ADDTIME
	 * 
	 * @return the value of TXL.TXL_ADDTIME
	 * 
	 * @mbggenerated
	 */
	public Date getTxlAddtime()
	{
		return txlAddtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column TXL.TXL_ADDTIME
	 * 
	 * @param txlAddtime
	 *            the value for TXL.TXL_ADDTIME
	 * 
	 * @mbggenerated
	 */
	public void setTxlAddtime(Date txlAddtime)
	{
		this.txlAddtime = txlAddtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column TXL.TXL_DELFLAG
	 * 
	 * @return the value of TXL.TXL_DELFLAG
	 * 
	 * @mbggenerated
	 */
	public Long getTxlDelflag()
	{
		return txlDelflag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column TXL.TXL_DELFLAG
	 * 
	 * @param txlDelflag
	 *            the value for TXL.TXL_DELFLAG
	 * 
	 * @mbggenerated
	 */
	public void setTxlDelflag(Long txlDelflag)
	{
		this.txlDelflag = txlDelflag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column TXL.TXL_PHONE
	 * 
	 * @return the value of TXL.TXL_PHONE
	 * 
	 * @mbggenerated
	 */
	public String getTxlPhone()
	{
		return txlPhone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column TXL.TXL_PHONE
	 * 
	 * @param txlPhone
	 *            the value for TXL.TXL_PHONE
	 * 
	 * @mbggenerated
	 */
	public void setTxlPhone(String txlPhone)
	{
		this.txlPhone = txlPhone;
	}
}