package com.ttgis.recruit.domain;

import java.io.Serializable;
import java.util.Date;

public class Xcxx implements Serializable
{
	private static final long serialVersionUID = 3013162480836552409L;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column XCXX.XCXX_ID
	 * 
	 * @mbggenerated
	 */
	private String xcxxId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column XCXX.XCXX_TITLE
	 * 
	 * @mbggenerated
	 */
	private String xcxxTitle;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column XCXX.XCXX_XCLB
	 * 
	 * @mbggenerated
	 */
	private String xcxxXclb;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column XCXX.XCXX_FBSJ
	 * 
	 * @mbggenerated
	 */
	private String xcxxFbsj;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column XCXX.XCXX_KQZT
	 * 
	 * @mbggenerated
	 */
	private String xcxxKqzt;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column XCXX.XCXX_ADDUSER
	 * 
	 * @mbggenerated
	 */
	private String xcxxAdduser;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column XCXX.XCXX_ADDTIME
	 * 
	 * @mbggenerated
	 */
	private Date xcxxAddtime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column XCXX.XCXX_ADDCOMPANY
	 * 
	 * @mbggenerated
	 */
	private String xcxxAddcompany;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column XCXX.XCXX_CHECKSTATUS
	 * 
	 * @mbggenerated
	 */
	private String xcxxCheckstatus;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column XCXX.XCXX_CHECKUSER
	 * 
	 * @mbggenerated
	 */
	private String xcxxCheckuser;

	private String xcxxCheckmsg;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column XCXX.XCXX_CHECKTIME
	 * 
	 * @mbggenerated
	 */
	private Date xcxxChecktime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column XCXX.XCXX_DELFLAG
	 * 
	 * @mbggenerated
	 */
	private Integer xcxxDelflag;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column XCXX.XCXX_CONTENT
	 * 
	 * @mbggenerated
	 */
	private String xcxxContent;

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column XCXX.XCXX_ID
	 * 
	 * @return the value of XCXX.XCXX_ID
	 * 
	 * @mbggenerated
	 */
	public String getXcxxId()
	{
		return xcxxId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column XCXX.XCXX_ID
	 * 
	 * @param xcxxId
	 *            the value for XCXX.XCXX_ID
	 * 
	 * @mbggenerated
	 */
	public void setXcxxId(String xcxxId)
	{
		this.xcxxId = xcxxId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column XCXX.XCXX_TITLE
	 * 
	 * @return the value of XCXX.XCXX_TITLE
	 * 
	 * @mbggenerated
	 */
	public String getXcxxTitle()
	{
		return xcxxTitle;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column XCXX.XCXX_TITLE
	 * 
	 * @param xcxxTitle
	 *            the value for XCXX.XCXX_TITLE
	 * 
	 * @mbggenerated
	 */
	public void setXcxxTitle(String xcxxTitle)
	{
		this.xcxxTitle = xcxxTitle;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column XCXX.XCXX_XCLB
	 * 
	 * @return the value of XCXX.XCXX_XCLB
	 * 
	 * @mbggenerated
	 */
	public String getXcxxXclb()
	{
		return xcxxXclb;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column XCXX.XCXX_XCLB
	 * 
	 * @param xcxxXclb
	 *            the value for XCXX.XCXX_XCLB
	 * 
	 * @mbggenerated
	 */
	public void setXcxxXclb(String xcxxXclb)
	{
		this.xcxxXclb = xcxxXclb;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column XCXX.XCXX_FBSJ
	 * 
	 * @return the value of XCXX.XCXX_FBSJ
	 * 
	 * @mbggenerated
	 */
	public String getXcxxFbsj()
	{
		return xcxxFbsj;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column XCXX.XCXX_FBSJ
	 * 
	 * @param xcxxFbsj
	 *            the value for XCXX.XCXX_FBSJ
	 * 
	 * @mbggenerated
	 */
	public void setXcxxFbsj(String xcxxFbsj)
	{
		this.xcxxFbsj = xcxxFbsj;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column XCXX.XCXX_KQZT
	 * 
	 * @return the value of XCXX.XCXX_KQZT
	 * 
	 * @mbggenerated
	 */
	public String getXcxxKqzt()
	{
		return xcxxKqzt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column XCXX.XCXX_KQZT
	 * 
	 * @param xcxxKqzt
	 *            the value for XCXX.XCXX_KQZT
	 * 
	 * @mbggenerated
	 */
	public void setXcxxKqzt(String xcxxKqzt)
	{
		this.xcxxKqzt = xcxxKqzt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column XCXX.XCXX_ADDUSER
	 * 
	 * @return the value of XCXX.XCXX_ADDUSER
	 * 
	 * @mbggenerated
	 */
	public String getXcxxAdduser()
	{
		return xcxxAdduser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column XCXX.XCXX_ADDUSER
	 * 
	 * @param xcxxAdduser
	 *            the value for XCXX.XCXX_ADDUSER
	 * 
	 * @mbggenerated
	 */
	public void setXcxxAdduser(String xcxxAdduser)
	{
		this.xcxxAdduser = xcxxAdduser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column XCXX.XCXX_ADDTIME
	 * 
	 * @return the value of XCXX.XCXX_ADDTIME
	 * 
	 * @mbggenerated
	 */
	public Date getXcxxAddtime()
	{
		return xcxxAddtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column XCXX.XCXX_ADDTIME
	 * 
	 * @param xcxxAddtime
	 *            the value for XCXX.XCXX_ADDTIME
	 * 
	 * @mbggenerated
	 */
	public void setXcxxAddtime(Date xcxxAddtime)
	{
		this.xcxxAddtime = xcxxAddtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column XCXX.XCXX_ADDCOMPANY
	 * 
	 * @return the value of XCXX.XCXX_ADDCOMPANY
	 * 
	 * @mbggenerated
	 */
	public String getXcxxAddcompany()
	{
		return xcxxAddcompany;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column XCXX.XCXX_ADDCOMPANY
	 * 
	 * @param xcxxAddcompany
	 *            the value for XCXX.XCXX_ADDCOMPANY
	 * 
	 * @mbggenerated
	 */
	public void setXcxxAddcompany(String xcxxAddcompany)
	{
		this.xcxxAddcompany = xcxxAddcompany;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column XCXX.XCXX_CHECKSTATUS
	 * 
	 * @return the value of XCXX.XCXX_CHECKSTATUS
	 * 
	 * @mbggenerated
	 */
	public String getXcxxCheckstatus()
	{
		return xcxxCheckstatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column XCXX.XCXX_CHECKSTATUS
	 * 
	 * @param xcxxCheckstatus
	 *            the value for XCXX.XCXX_CHECKSTATUS
	 * 
	 * @mbggenerated
	 */
	public void setXcxxCheckstatus(String xcxxCheckstatus)
	{
		this.xcxxCheckstatus = xcxxCheckstatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column XCXX.XCXX_CHECKUSER
	 * 
	 * @return the value of XCXX.XCXX_CHECKUSER
	 * 
	 * @mbggenerated
	 */
	public String getXcxxCheckuser()
	{
		return xcxxCheckuser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column XCXX.XCXX_CHECKUSER
	 * 
	 * @param xcxxCheckuser
	 *            the value for XCXX.XCXX_CHECKUSER
	 * 
	 * @mbggenerated
	 */
	public void setXcxxCheckuser(String xcxxCheckuser)
	{
		this.xcxxCheckuser = xcxxCheckuser;
	}

	public String getXcxxCheckmsg()
	{
		return xcxxCheckmsg;
	}

	public void setXcxxCheckmsg(String xcxxCheckmsg)
	{
		this.xcxxCheckmsg = xcxxCheckmsg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column XCXX.XCXX_CHECKTIME
	 * 
	 * @return the value of XCXX.XCXX_CHECKTIME
	 * 
	 * @mbggenerated
	 */
	public Date getXcxxChecktime()
	{
		return xcxxChecktime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column XCXX.XCXX_CHECKTIME
	 * 
	 * @param xcxxChecktime
	 *            the value for XCXX.XCXX_CHECKTIME
	 * 
	 * @mbggenerated
	 */
	public void setXcxxChecktime(Date xcxxChecktime)
	{
		this.xcxxChecktime = xcxxChecktime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column XCXX.XCXX_DELFLAG
	 * 
	 * @return the value of XCXX.XCXX_DELFLAG
	 * 
	 * @mbggenerated
	 */
	public Integer getXcxxDelflag()
	{
		return xcxxDelflag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column XCXX.XCXX_DELFLAG
	 * 
	 * @param xcxxDelflag
	 *            the value for XCXX.XCXX_DELFLAG
	 * 
	 * @mbggenerated
	 */
	public void setXcxxDelflag(Integer xcxxDelflag)
	{
		this.xcxxDelflag = xcxxDelflag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column XCXX.XCXX_CONTENT
	 * 
	 * @return the value of XCXX.XCXX_CONTENT
	 * 
	 * @mbggenerated
	 */
	public String getXcxxContent()
	{
		return xcxxContent;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column XCXX.XCXX_CONTENT
	 * 
	 * @param xcxxContent
	 *            the value for XCXX.XCXX_CONTENT
	 * 
	 * @mbggenerated
	 */
	public void setXcxxContent(String xcxxContent)
	{
		this.xcxxContent = xcxxContent;
	}
}