package com.ttgis.recruit.domain;

import java.util.Date;

public class Xcxx_attach {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XCXX_ATTACH.XCXX_ATTACH_ID
     *
     * @mbggenerated
     */
    private String xcxxAttachId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XCXX_ATTACH.XCXX_ID
     *
     * @mbggenerated
     */
    private String xcxxId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XCXX_ATTACH.XCXX_ATTACH_TITLE
     *
     * @mbggenerated
     */
    private String xcxxAttachTitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XCXX_ATTACH.XCXX_ATTACH_TYPE
     *
     * @mbggenerated
     */
    private String xcxxAttachType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XCXX_ATTACH.XCXX_ATTACH_URL
     *
     * @mbggenerated
     */
    private String xcxxAttachUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XCXX_ATTACH.XCXX_ATTACH_ADDUSER
     *
     * @mbggenerated
     */
    private String xcxxAttachAdduser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XCXX_ATTACH.XCXX_ATTACH_ADDTIME
     *
     * @mbggenerated
     */
    private Date xcxxAttachAddtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XCXX_ATTACH.XCXX_ATTACH_DELFLAG
     *
     * @mbggenerated
     */
    private Long xcxxAttachDelflag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XCXX_ATTACH.XCXX_ATTACH_CONTENT
     *
     * @mbggenerated
     */
    private String xcxxAttachContent;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XCXX_ATTACH.XCXX_ATTACH_ID
     *
     * @return the value of XCXX_ATTACH.XCXX_ATTACH_ID
     *
     * @mbggenerated
     */
    public String getXcxxAttachId() {
        return xcxxAttachId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XCXX_ATTACH.XCXX_ATTACH_ID
     *
     * @param xcxxAttachId the value for XCXX_ATTACH.XCXX_ATTACH_ID
     *
     * @mbggenerated
     */
    public void setXcxxAttachId(String xcxxAttachId) {
        this.xcxxAttachId = xcxxAttachId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XCXX_ATTACH.XCXX_ID
     *
     * @return the value of XCXX_ATTACH.XCXX_ID
     *
     * @mbggenerated
     */
    public String getXcxxId() {
        return xcxxId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XCXX_ATTACH.XCXX_ID
     *
     * @param xcxxId the value for XCXX_ATTACH.XCXX_ID
     *
     * @mbggenerated
     */
    public void setXcxxId(String xcxxId) {
        this.xcxxId = xcxxId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XCXX_ATTACH.XCXX_ATTACH_TITLE
     *
     * @return the value of XCXX_ATTACH.XCXX_ATTACH_TITLE
     *
     * @mbggenerated
     */
    public String getXcxxAttachTitle() {
        return xcxxAttachTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XCXX_ATTACH.XCXX_ATTACH_TITLE
     *
     * @param xcxxAttachTitle the value for XCXX_ATTACH.XCXX_ATTACH_TITLE
     *
     * @mbggenerated
     */
    public void setXcxxAttachTitle(String xcxxAttachTitle) {
        this.xcxxAttachTitle = xcxxAttachTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XCXX_ATTACH.XCXX_ATTACH_TYPE
     *
     * @return the value of XCXX_ATTACH.XCXX_ATTACH_TYPE
     *
     * @mbggenerated
     */
    public String getXcxxAttachType() {
        return xcxxAttachType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XCXX_ATTACH.XCXX_ATTACH_TYPE
     *
     * @param xcxxAttachType the value for XCXX_ATTACH.XCXX_ATTACH_TYPE
     *
     * @mbggenerated
     */
    public void setXcxxAttachType(String xcxxAttachType) {
        this.xcxxAttachType = xcxxAttachType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XCXX_ATTACH.XCXX_ATTACH_URL
     *
     * @return the value of XCXX_ATTACH.XCXX_ATTACH_URL
     *
     * @mbggenerated
     */
    public String getXcxxAttachUrl() {
        return xcxxAttachUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XCXX_ATTACH.XCXX_ATTACH_URL
     *
     * @param xcxxAttachUrl the value for XCXX_ATTACH.XCXX_ATTACH_URL
     *
     * @mbggenerated
     */
    public void setXcxxAttachUrl(String xcxxAttachUrl) {
        this.xcxxAttachUrl = xcxxAttachUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XCXX_ATTACH.XCXX_ATTACH_ADDUSER
     *
     * @return the value of XCXX_ATTACH.XCXX_ATTACH_ADDUSER
     *
     * @mbggenerated
     */
    public String getXcxxAttachAdduser() {
        return xcxxAttachAdduser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XCXX_ATTACH.XCXX_ATTACH_ADDUSER
     *
     * @param xcxxAttachAdduser the value for XCXX_ATTACH.XCXX_ATTACH_ADDUSER
     *
     * @mbggenerated
     */
    public void setXcxxAttachAdduser(String xcxxAttachAdduser) {
        this.xcxxAttachAdduser = xcxxAttachAdduser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XCXX_ATTACH.XCXX_ATTACH_ADDTIME
     *
     * @return the value of XCXX_ATTACH.XCXX_ATTACH_ADDTIME
     *
     * @mbggenerated
     */
    public Date getXcxxAttachAddtime() {
        return xcxxAttachAddtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XCXX_ATTACH.XCXX_ATTACH_ADDTIME
     *
     * @param xcxxAttachAddtime the value for XCXX_ATTACH.XCXX_ATTACH_ADDTIME
     *
     * @mbggenerated
     */
    public void setXcxxAttachAddtime(Date xcxxAttachAddtime) {
        this.xcxxAttachAddtime = xcxxAttachAddtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XCXX_ATTACH.XCXX_ATTACH_DELFLAG
     *
     * @return the value of XCXX_ATTACH.XCXX_ATTACH_DELFLAG
     *
     * @mbggenerated
     */
    public Long getXcxxAttachDelflag() {
        return xcxxAttachDelflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XCXX_ATTACH.XCXX_ATTACH_DELFLAG
     *
     * @param xcxxAttachDelflag the value for XCXX_ATTACH.XCXX_ATTACH_DELFLAG
     *
     * @mbggenerated
     */
    public void setXcxxAttachDelflag(Long xcxxAttachDelflag) {
        this.xcxxAttachDelflag = xcxxAttachDelflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XCXX_ATTACH.XCXX_ATTACH_CONTENT
     *
     * @return the value of XCXX_ATTACH.XCXX_ATTACH_CONTENT
     *
     * @mbggenerated
     */
    public String getXcxxAttachContent() {
        return xcxxAttachContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XCXX_ATTACH.XCXX_ATTACH_CONTENT
     *
     * @param xcxxAttachContent the value for XCXX_ATTACH.XCXX_ATTACH_CONTENT
     *
     * @mbggenerated
     */
    public void setXcxxAttachContent(String xcxxAttachContent) {
        this.xcxxAttachContent = xcxxAttachContent;
    }
}