package com.ttgis.recruit.domain;

import java.io.Serializable;
import java.util.Date;

public class XqqzLxgl implements Serializable
{
	private static final long serialVersionUID = 1240822904060703767L;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column XQQZLXGL.XQQZLXGL_ID
	 * 
	 * @mbggenerated
	 */
	private String xqqzlxglId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column XQQZLXGL.XQQZLXGL_LXMC
	 * 
	 * @mbggenerated
	 */
	private String xqqzlxglLxmc;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column XQQZLXGL.XQQZLXGL_ADDTIME
	 * 
	 * @mbggenerated
	 */
	private Date xqqzlxglAddtime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column XQQZLXGL.XQQZLXGL_DELFLAG
	 * 
	 * @mbggenerated
	 */
	private Long xqqzlxglDelflag;

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column XQQZLXGL.XQQZLXGL_ID
	 * 
	 * @return the value of XQQZLXGL.XQQZLXGL_ID
	 * 
	 * @mbggenerated
	 */
	public String getXqqzlxglId()
	{
		return xqqzlxglId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column XQQZLXGL.XQQZLXGL_ID
	 * 
	 * @param xqqzlxglId
	 *            the value for XQQZLXGL.XQQZLXGL_ID
	 * 
	 * @mbggenerated
	 */
	public void setXqqzlxglId(String xqqzlxglId)
	{
		this.xqqzlxglId = xqqzlxglId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column XQQZLXGL.XQQZLXGL_LXMC
	 * 
	 * @return the value of XQQZLXGL.XQQZLXGL_LXMC
	 * 
	 * @mbggenerated
	 */
	public String getXqqzlxglLxmc()
	{
		return xqqzlxglLxmc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column XQQZLXGL.XQQZLXGL_LXMC
	 * 
	 * @param xqqzlxglLxmc
	 *            the value for XQQZLXGL.XQQZLXGL_LXMC
	 * 
	 * @mbggenerated
	 */
	public void setXqqzlxglLxmc(String xqqzlxglLxmc)
	{
		this.xqqzlxglLxmc = xqqzlxglLxmc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column XQQZLXGL.XQQZLXGL_ADDTIME
	 * 
	 * @return the value of XQQZLXGL.XQQZLXGL_ADDTIME
	 * 
	 * @mbggenerated
	 */
	public Date getXqqzlxglAddtime()
	{
		return xqqzlxglAddtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column XQQZLXGL.XQQZLXGL_ADDTIME
	 * 
	 * @param xqqzlxglAddtime
	 *            the value for XQQZLXGL.XQQZLXGL_ADDTIME
	 * 
	 * @mbggenerated
	 */
	public void setXqqzlxglAddtime(Date xqqzlxglAddtime)
	{
		this.xqqzlxglAddtime = xqqzlxglAddtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column XQQZLXGL.XQQZLXGL_DELFLAG
	 * 
	 * @return the value of XQQZLXGL.XQQZLXGL_DELFLAG
	 * 
	 * @mbggenerated
	 */
	public Long getXqqzlxglDelflag()
	{
		return xqqzlxglDelflag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column XQQZLXGL.XQQZLXGL_DELFLAG
	 * 
	 * @param xqqzlxglDelflag
	 *            the value for XQQZLXGL.XQQZLXGL_DELFLAG
	 * 
	 * @mbggenerated
	 */
	public void setXqqzlxglDelflag(Long xqqzlxglDelflag)
	{
		this.xqqzlxglDelflag = xqqzlxglDelflag;
	}
}