package com.ttgis.recruit.domain;

import java.io.Serializable;
import java.util.Date;

public class Xqqz implements Serializable
{
	private static final long serialVersionUID = 3911614179328583240L;
	private String pls;
	private String lxmc;

	public String getLxmc()
	{
		return lxmc;
	}

	public void setLxmc(String lxmc)
	{
		this.lxmc = lxmc;
	}

	public String getPls()
	{
		return pls;
	}

	public void setPls(String pls)
	{
		this.pls = pls;
	}

	private String nr;

	public String getNr()
	{
		return nr;
	}

	public void setNr(String nr)
	{
		this.nr = nr;
	}

	private String fbsj;

	public String getFbsj()
	{
		return fbsj;
	}

	public void setFbsj(String fbsj)
	{
		this.fbsj = fbsj;
	}

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column XQQZ.XQQZ_ID
	 * 
	 * @mbggenerated
	 */
	private String xqqzId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column XQQZ.XQQZ_TITLE
	 * 
	 * @mbggenerated
	 */
	private String xqqzTitle;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column XQQZ.XQQZ_NR
	 * 
	 * @mbggenerated
	 */
	private String xqqzNr;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column XQQZ.XQQZ_FBSJ
	 * 
	 * @mbggenerated
	 */
	private Date xqqzFbsj;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column XQQZ.XQQZ_FBR
	 * 
	 * @mbggenerated
	 */
	private String xqqzFbr;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column XQQZ.XQQZ_DELFLAG
	 * 
	 * @mbggenerated
	 */
	private String xqqzDelflag;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column XQQZ.XQQZ_TYPE
	 * 
	 * @mbggenerated
	 */
	private String xqqzType;

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column XQQZ.XQQZ_ID
	 * 
	 * @return the value of XQQZ.XQQZ_ID
	 * 
	 * @mbggenerated
	 */
	public String getXqqzId()
	{
		return xqqzId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column XQQZ.XQQZ_ID
	 * 
	 * @param xqqzId
	 *            the value for XQQZ.XQQZ_ID
	 * 
	 * @mbggenerated
	 */
	public void setXqqzId(String xqqzId)
	{
		this.xqqzId = xqqzId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column XQQZ.XQQZ_TITLE
	 * 
	 * @return the value of XQQZ.XQQZ_TITLE
	 * 
	 * @mbggenerated
	 */
	public String getXqqzTitle()
	{
		return xqqzTitle;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column XQQZ.XQQZ_TITLE
	 * 
	 * @param xqqzTitle
	 *            the value for XQQZ.XQQZ_TITLE
	 * 
	 * @mbggenerated
	 */
	public void setXqqzTitle(String xqqzTitle)
	{
		this.xqqzTitle = xqqzTitle;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column XQQZ.XQQZ_NR
	 * 
	 * @return the value of XQQZ.XQQZ_NR
	 * 
	 * @mbggenerated
	 */
	public String getXqqzNr()
	{
		return xqqzNr;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column XQQZ.XQQZ_NR
	 * 
	 * @param xqqzNr
	 *            the value for XQQZ.XQQZ_NR
	 * 
	 * @mbggenerated
	 */
	public void setXqqzNr(String xqqzNr)
	{
		this.xqqzNr = xqqzNr;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column XQQZ.XQQZ_FBSJ
	 * 
	 * @return the value of XQQZ.XQQZ_FBSJ
	 * 
	 * @mbggenerated
	 */
	public Date getXqqzFbsj()
	{
		return xqqzFbsj;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column XQQZ.XQQZ_FBSJ
	 * 
	 * @param xqqzFbsj
	 *            the value for XQQZ.XQQZ_FBSJ
	 * 
	 * @mbggenerated
	 */
	public void setXqqzFbsj(Date xqqzFbsj)
	{
		this.xqqzFbsj = xqqzFbsj;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column XQQZ.XQQZ_FBR
	 * 
	 * @return the value of XQQZ.XQQZ_FBR
	 * 
	 * @mbggenerated
	 */
	public String getXqqzFbr()
	{
		return xqqzFbr;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column XQQZ.XQQZ_FBR
	 * 
	 * @param xqqzFbr
	 *            the value for XQQZ.XQQZ_FBR
	 * 
	 * @mbggenerated
	 */
	public void setXqqzFbr(String xqqzFbr)
	{
		this.xqqzFbr = xqqzFbr;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column XQQZ.XQQZ_DELFLAG
	 * 
	 * @return the value of XQQZ.XQQZ_DELFLAG
	 * 
	 * @mbggenerated
	 */
	public String getXqqzDelflag()
	{
		return xqqzDelflag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column XQQZ.XQQZ_DELFLAG
	 * 
	 * @param xqqzDelflag
	 *            the value for XQQZ.XQQZ_DELFLAG
	 * 
	 * @mbggenerated
	 */
	public void setXqqzDelflag(String xqqzDelflag)
	{
		this.xqqzDelflag = xqqzDelflag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column XQQZ.XQQZ_TYPE
	 * 
	 * @return the value of XQQZ.XQQZ_TYPE
	 * 
	 * @mbggenerated
	 */
	public String getXqqzType()
	{
		return xqqzType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column XQQZ.XQQZ_TYPE
	 * 
	 * @param xqqzType
	 *            the value for XQQZ.XQQZ_TYPE
	 * 
	 * @mbggenerated
	 */
	public void setXqqzType(String xqqzType)
	{
		this.xqqzType = xqqzType;
	}
}