package com.ttgis.recruit.domain;

import java.io.Serializable;
import java.util.Date;

public class Xxtz implements Serializable
{
	private static final long serialVersionUID = -7083229543901135403L;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column XXTZ.XXTZ_ID
	 * 
	 * @mbggenerated
	 */
	private String xxtzId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column XXTZ.USER_ID
	 * 
	 * @mbggenerated
	 */
	private String userId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column XXTZ.XXTZ_TYPE
	 * 
	 * @mbggenerated
	 */
	private String xxtzType;
	private String[] type;

	public String[] getType()
	{
		return type;
	}

	public void setType(String[] type)
	{
		this.type = type;
	}

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column XXTZ.XXTZ_USER
	 * 
	 * @mbggenerated
	 */
	private String xxtzUser;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column XXTZ.XXTZ_TELEPOHNE
	 * 
	 * @mbggenerated
	 */
	private Long xxtzTelepohne;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column XXTZ.XXTZ_EMAIL
	 * 
	 * @mbggenerated
	 */
	private String xxtzEmail;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column XXTZ.XXTZ_MESSAGE_CONTENT
	 * 
	 * @mbggenerated
	 */
	private String xxtzMessageContent;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column XXTZ.XXTZ_MESSAGE_TIME
	 * 
	 * @mbggenerated
	 */
	private Date xxtzMessageTime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column XXTZ.XXTZ_MESSAGE_RESULT
	 * 
	 * @mbggenerated
	 */
	private String xxtzMessageResult;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column XXTZ.XXTZ_EMAIL_CONTENT
	 * 
	 * @mbggenerated
	 */
	private String xxtzEmailContent;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column XXTZ.XXTZ_EMAIL_TIME
	 * 
	 * @mbggenerated
	 */
	private Date xxtzEmailTime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column XXTZ.XXTZ_EMAIL_RESULT
	 * 
	 * @mbggenerated
	 */
	private String xxtzEmailResult;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column XXTZ.XXTZ_CUSER
	 * 
	 * @mbggenerated
	 */
	private String xxtzCuser;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column XXTZ.XXTZ_ADDTIME
	 * 
	 * @mbggenerated
	 */
	private Date xxtzAddtime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column XXTZ.XXTZ_DELFLAG
	 * 
	 * @mbggenerated
	 */
	private Long xxtzDelflag;

	private Integer xxtzIsread;

	public Integer getXxtzIsread()
	{
		return xxtzIsread;
	}

	public void setXxtzIsread(Integer xxtzIsread)
	{
		this.xxtzIsread = xxtzIsread;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column XXTZ.XXTZ_ID
	 * 
	 * @return the value of XXTZ.XXTZ_ID
	 * 
	 * @mbggenerated
	 */
	public String getXxtzId()
	{
		return xxtzId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column XXTZ.XXTZ_ID
	 * 
	 * @param xxtzId
	 *            the value for XXTZ.XXTZ_ID
	 * 
	 * @mbggenerated
	 */
	public void setXxtzId(String xxtzId)
	{
		this.xxtzId = xxtzId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column XXTZ.USER_ID
	 * 
	 * @return the value of XXTZ.USER_ID
	 * 
	 * @mbggenerated
	 */
	public String getUserId()
	{
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column XXTZ.USER_ID
	 * 
	 * @param userId
	 *            the value for XXTZ.USER_ID
	 * 
	 * @mbggenerated
	 */
	public void setUserId(String userId)
	{
		this.userId = userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column XXTZ.XXTZ_TYPE
	 * 
	 * @return the value of XXTZ.XXTZ_TYPE
	 * 
	 * @mbggenerated
	 */
	public String getXxtzType()
	{
		return xxtzType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column XXTZ.XXTZ_TYPE
	 * 
	 * @param xxtzType
	 *            the value for XXTZ.XXTZ_TYPE
	 * 
	 * @mbggenerated
	 */
	public void setXxtzType(String xxtzType)
	{
		this.xxtzType = xxtzType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column XXTZ.XXTZ_USER
	 * 
	 * @return the value of XXTZ.XXTZ_USER
	 * 
	 * @mbggenerated
	 */
	public String getXxtzUser()
	{
		return xxtzUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column XXTZ.XXTZ_USER
	 * 
	 * @param xxtzUser
	 *            the value for XXTZ.XXTZ_USER
	 * 
	 * @mbggenerated
	 */
	public void setXxtzUser(String xxtzUser)
	{
		this.xxtzUser = xxtzUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column XXTZ.XXTZ_TELEPOHNE
	 * 
	 * @return the value of XXTZ.XXTZ_TELEPOHNE
	 * 
	 * @mbggenerated
	 */
	public Long getXxtzTelepohne()
	{
		return xxtzTelepohne;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column XXTZ.XXTZ_TELEPOHNE
	 * 
	 * @param xxtzTelepohne
	 *            the value for XXTZ.XXTZ_TELEPOHNE
	 * 
	 * @mbggenerated
	 */
	public void setXxtzTelepohne(Long xxtzTelepohne)
	{
		this.xxtzTelepohne = xxtzTelepohne;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column XXTZ.XXTZ_EMAIL
	 * 
	 * @return the value of XXTZ.XXTZ_EMAIL
	 * 
	 * @mbggenerated
	 */
	public String getXxtzEmail()
	{
		return xxtzEmail;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column XXTZ.XXTZ_EMAIL
	 * 
	 * @param xxtzEmail
	 *            the value for XXTZ.XXTZ_EMAIL
	 * 
	 * @mbggenerated
	 */
	public void setXxtzEmail(String xxtzEmail)
	{
		this.xxtzEmail = xxtzEmail;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column XXTZ.XXTZ_MESSAGE_CONTENT
	 * 
	 * @return the value of XXTZ.XXTZ_MESSAGE_CONTENT
	 * 
	 * @mbggenerated
	 */
	public String getXxtzMessageContent()
	{
		return xxtzMessageContent;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column XXTZ.XXTZ_MESSAGE_CONTENT
	 * 
	 * @param xxtzMessageContent
	 *            the value for XXTZ.XXTZ_MESSAGE_CONTENT
	 * 
	 * @mbggenerated
	 */
	public void setXxtzMessageContent(String xxtzMessageContent)
	{
		this.xxtzMessageContent = xxtzMessageContent;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column XXTZ.XXTZ_MESSAGE_TIME
	 * 
	 * @return the value of XXTZ.XXTZ_MESSAGE_TIME
	 * 
	 * @mbggenerated
	 */
	public Date getXxtzMessageTime()
	{
		return xxtzMessageTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column XXTZ.XXTZ_MESSAGE_TIME
	 * 
	 * @param xxtzMessageTime
	 *            the value for XXTZ.XXTZ_MESSAGE_TIME
	 * 
	 * @mbggenerated
	 */
	public void setXxtzMessageTime(Date xxtzMessageTime)
	{
		this.xxtzMessageTime = xxtzMessageTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column XXTZ.XXTZ_MESSAGE_RESULT
	 * 
	 * @return the value of XXTZ.XXTZ_MESSAGE_RESULT
	 * 
	 * @mbggenerated
	 */
	public String getXxtzMessageResult()
	{
		return xxtzMessageResult;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column XXTZ.XXTZ_MESSAGE_RESULT
	 * 
	 * @param xxtzMessageResult
	 *            the value for XXTZ.XXTZ_MESSAGE_RESULT
	 * 
	 * @mbggenerated
	 */
	public void setXxtzMessageResult(String xxtzMessageResult)
	{
		this.xxtzMessageResult = xxtzMessageResult;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column XXTZ.XXTZ_EMAIL_CONTENT
	 * 
	 * @return the value of XXTZ.XXTZ_EMAIL_CONTENT
	 * 
	 * @mbggenerated
	 */
	public String getXxtzEmailContent()
	{
		return xxtzEmailContent;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column XXTZ.XXTZ_EMAIL_CONTENT
	 * 
	 * @param xxtzEmailContent
	 *            the value for XXTZ.XXTZ_EMAIL_CONTENT
	 * 
	 * @mbggenerated
	 */
	public void setXxtzEmailContent(String xxtzEmailContent)
	{
		this.xxtzEmailContent = xxtzEmailContent;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column XXTZ.XXTZ_EMAIL_TIME
	 * 
	 * @return the value of XXTZ.XXTZ_EMAIL_TIME
	 * 
	 * @mbggenerated
	 */
	public Date getXxtzEmailTime()
	{
		return xxtzEmailTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column XXTZ.XXTZ_EMAIL_TIME
	 * 
	 * @param xxtzEmailTime
	 *            the value for XXTZ.XXTZ_EMAIL_TIME
	 * 
	 * @mbggenerated
	 */
	public void setXxtzEmailTime(Date xxtzEmailTime)
	{
		this.xxtzEmailTime = xxtzEmailTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column XXTZ.XXTZ_EMAIL_RESULT
	 * 
	 * @return the value of XXTZ.XXTZ_EMAIL_RESULT
	 * 
	 * @mbggenerated
	 */
	public String getXxtzEmailResult()
	{
		return xxtzEmailResult;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column XXTZ.XXTZ_EMAIL_RESULT
	 * 
	 * @param xxtzEmailResult
	 *            the value for XXTZ.XXTZ_EMAIL_RESULT
	 * 
	 * @mbggenerated
	 */
	public void setXxtzEmailResult(String xxtzEmailResult)
	{
		this.xxtzEmailResult = xxtzEmailResult;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column XXTZ.XXTZ_CUSER
	 * 
	 * @return the value of XXTZ.XXTZ_CUSER
	 * 
	 * @mbggenerated
	 */
	public String getXxtzCuser()
	{
		return xxtzCuser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column XXTZ.XXTZ_CUSER
	 * 
	 * @param xxtzCuser
	 *            the value for XXTZ.XXTZ_CUSER
	 * 
	 * @mbggenerated
	 */
	public void setXxtzCuser(String xxtzCuser)
	{
		this.xxtzCuser = xxtzCuser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column XXTZ.XXTZ_ADDTIME
	 * 
	 * @return the value of XXTZ.XXTZ_ADDTIME
	 * 
	 * @mbggenerated
	 */
	public Date getXxtzAddtime()
	{
		return xxtzAddtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column XXTZ.XXTZ_ADDTIME
	 * 
	 * @param xxtzAddtime
	 *            the value for XXTZ.XXTZ_ADDTIME
	 * 
	 * @mbggenerated
	 */
	public void setXxtzAddtime(Date xxtzAddtime)
	{
		this.xxtzAddtime = xxtzAddtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column XXTZ.XXTZ_DELFLAG
	 * 
	 * @return the value of XXTZ.XXTZ_DELFLAG
	 * 
	 * @mbggenerated
	 */
	public Long getXxtzDelflag()
	{
		return xxtzDelflag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column XXTZ.XXTZ_DELFLAG
	 * 
	 * @param xxtzDelflag
	 *            the value for XXTZ.XXTZ_DELFLAG
	 * 
	 * @mbggenerated
	 */
	public void setXxtzDelflag(Long xxtzDelflag)
	{
		this.xxtzDelflag = xxtzDelflag;
	}
}