package com.ttgis.recruit.domain;

import java.io.Serializable;
import java.util.Date;

public class Zjgz implements Serializable
{
	private static final long serialVersionUID = 4005488315397824883L;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column ZJGZ.ZJGZ_ID
	 * 
	 * @mbggenerated
	 */
	private String zjgzId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column ZJGZ.ZJGZ_LX
	 * 
	 * @mbggenerated
	 */
	private String zjgzLx;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column ZJGZ.ZJGZ_BH
	 * 
	 * @mbggenerated
	 */
	private String zjgzBh;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column ZJGZ.ZJGZ_YXDJ
	 * 
	 * @mbggenerated
	 */
	private String zjgzYxdj;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column ZJGZ.ZJGZ_SYKSLX
	 * 
	 * @mbggenerated
	 */
	private String zjgzSykslx;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column ZJGZ.ZJGZ_GZNR
	 * 
	 * @mbggenerated
	 */
	private String zjgzGznr;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column ZJGZ.ZJGZ_ADDTIME
	 * 
	 * @mbggenerated
	 */
	private Date zjgzAddtime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column ZJGZ.ZJGZ_DELFLAG
	 * 
	 * @mbggenerated
	 */
	private Long zjgzDelflag;

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column ZJGZ.ZJGZ_ID
	 * 
	 * @return the value of ZJGZ.ZJGZ_ID
	 * 
	 * @mbggenerated
	 */
	public String getZjgzId()
	{
		return zjgzId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column ZJGZ.ZJGZ_ID
	 * 
	 * @param zjgzId
	 *            the value for ZJGZ.ZJGZ_ID
	 * 
	 * @mbggenerated
	 */
	public void setZjgzId(String zjgzId)
	{
		this.zjgzId = zjgzId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column ZJGZ.ZJGZ_LX
	 * 
	 * @return the value of ZJGZ.ZJGZ_LX
	 * 
	 * @mbggenerated
	 */
	public String getZjgzLx()
	{
		return zjgzLx;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column ZJGZ.ZJGZ_LX
	 * 
	 * @param zjgzLx
	 *            the value for ZJGZ.ZJGZ_LX
	 * 
	 * @mbggenerated
	 */
	public void setZjgzLx(String zjgzLx)
	{
		this.zjgzLx = zjgzLx;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column ZJGZ.ZJGZ_BH
	 * 
	 * @return the value of ZJGZ.ZJGZ_BH
	 * 
	 * @mbggenerated
	 */
	public String getZjgzBh()
	{
		return zjgzBh;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column ZJGZ.ZJGZ_BH
	 * 
	 * @param zjgzBh
	 *            the value for ZJGZ.ZJGZ_BH
	 * 
	 * @mbggenerated
	 */
	public void setZjgzBh(String zjgzBh)
	{
		this.zjgzBh = zjgzBh;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column ZJGZ.ZJGZ_YXDJ
	 * 
	 * @return the value of ZJGZ.ZJGZ_YXDJ
	 * 
	 * @mbggenerated
	 */
	public String getZjgzYxdj()
	{
		return zjgzYxdj;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column ZJGZ.ZJGZ_YXDJ
	 * 
	 * @param zjgzYxdj
	 *            the value for ZJGZ.ZJGZ_YXDJ
	 * 
	 * @mbggenerated
	 */
	public void setZjgzYxdj(String zjgzYxdj)
	{
		this.zjgzYxdj = zjgzYxdj;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column ZJGZ.ZJGZ_SYKSLX
	 * 
	 * @return the value of ZJGZ.ZJGZ_SYKSLX
	 * 
	 * @mbggenerated
	 */
	public String getZjgzSykslx()
	{
		return zjgzSykslx;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column ZJGZ.ZJGZ_SYKSLX
	 * 
	 * @param zjgzSykslx
	 *            the value for ZJGZ.ZJGZ_SYKSLX
	 * 
	 * @mbggenerated
	 */
	public void setZjgzSykslx(String zjgzSykslx)
	{
		this.zjgzSykslx = zjgzSykslx;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column ZJGZ.ZJGZ_GZNR
	 * 
	 * @return the value of ZJGZ.ZJGZ_GZNR
	 * 
	 * @mbggenerated
	 */
	public String getZjgzGznr()
	{
		return zjgzGznr;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column ZJGZ.ZJGZ_GZNR
	 * 
	 * @param zjgzGznr
	 *            the value for ZJGZ.ZJGZ_GZNR
	 * 
	 * @mbggenerated
	 */
	public void setZjgzGznr(String zjgzGznr)
	{
		this.zjgzGznr = zjgzGznr;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column ZJGZ.ZJGZ_ADDTIME
	 * 
	 * @return the value of ZJGZ.ZJGZ_ADDTIME
	 * 
	 * @mbggenerated
	 */
	public Date getZjgzAddtime()
	{
		return zjgzAddtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column ZJGZ.ZJGZ_ADDTIME
	 * 
	 * @param zjgzAddtime
	 *            the value for ZJGZ.ZJGZ_ADDTIME
	 * 
	 * @mbggenerated
	 */
	public void setZjgzAddtime(Date zjgzAddtime)
	{
		this.zjgzAddtime = zjgzAddtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column ZJGZ.ZJGZ_DELFLAG
	 * 
	 * @return the value of ZJGZ.ZJGZ_DELFLAG
	 * 
	 * @mbggenerated
	 */
	public Long getZjgzDelflag()
	{
		return zjgzDelflag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column ZJGZ.ZJGZ_DELFLAG
	 * 
	 * @param zjgzDelflag
	 *            the value for ZJGZ.ZJGZ_DELFLAG
	 * 
	 * @mbggenerated
	 */
	public void setZjgzDelflag(Long zjgzDelflag)
	{
		this.zjgzDelflag = zjgzDelflag;
	}
}