package com.ttgis.recruit.domain;

import java.io.Serializable;
import java.util.Date;

public class Zpxw implements Serializable
{
	private static final long serialVersionUID = -1704449420319844280L;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column ZPXW.ZPXW_ID
	 * 
	 * @mbggenerated
	 */
	private String zpxwId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column ZPXW.ZZJG_ID
	 * 
	 * @mbggenerated
	 */
	private String zzjgId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column ZPXW.ZPXW_TITLE
	 * 
	 * @mbggenerated
	 */
	private String zpxwTitle;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column ZPXW.ZPXW_FBSJ
	 * 
	 * @mbggenerated
	 */
	private String zpxwFbsj;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column ZPXW.ZPXW_KQZT
	 * 
	 * @mbggenerated
	 */
	private String zpxwKqzt;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column ZPXW.ZPXW_ADDUSER
	 * 
	 * @mbggenerated
	 */
	private String zpxwSfzprc;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column ZPXW.ZPXW_ADDTIME
	 * 
	 * @mbggenerated
	 */
	private Date zpxwAddtime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column ZPXW.ZPXW_ADDCOMPANY
	 * 
	 * @mbggenerated
	 */
	private String zpxwAddcompany;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column ZPXW.ZPXW_DELFLAG
	 * 
	 * @mbggenerated
	 */
	private Integer zpxwDelflag;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column ZPXW.ZPXW_CONTENT
	 * 
	 * @mbggenerated
	 */
	private String zpxwContent;

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column ZPXW.ZPXW_ID
	 * 
	 * @return the value of ZPXW.ZPXW_ID
	 * 
	 * @mbggenerated
	 */
	
	private String zpxwTop;
	
	public String getZpxwTop()
	{
		return zpxwTop;
	}

	public void setZpxwTop(String zpxwTop)
	{
		this.zpxwTop = zpxwTop;
	}
	
	public String getZpxwId()
	{
		return zpxwId;
	}
	
	private Date topRtime;
	
	private Date topLtime;

	public Date getTopRtime() {
		return topRtime;
	}

	public void setTopRtime(Date topRtime) {
		this.topRtime = topRtime;
	}

	public Date getTopLtime() {
		return topLtime;
	}

	public void setTopLtime(Date topLtime) {
		this.topLtime = topLtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column ZPXW.ZPXW_ID
	 * 
	 * @param zpxwId
	 *            the value for ZPXW.ZPXW_ID
	 * 
	 * @mbggenerated
	 */
	public void setZpxwId(String zpxwId)
	{
		this.zpxwId = zpxwId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column ZPXW.ZZJG_ID
	 * 
	 * @return the value of ZPXW.ZZJG_ID
	 * 
	 * @mbggenerated
	 */
	public String getZzjgId()
	{
		return zzjgId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column ZPXW.ZZJG_ID
	 * 
	 * @param zzjgId
	 *            the value for ZPXW.ZZJG_ID
	 * 
	 * @mbggenerated
	 */
	public void setZzjgId(String zzjgId)
	{
		this.zzjgId = zzjgId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column ZPXW.ZPXW_TITLE
	 * 
	 * @return the value of ZPXW.ZPXW_TITLE
	 * 
	 * @mbggenerated
	 */
	public String getZpxwTitle()
	{
		return zpxwTitle;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column ZPXW.ZPXW_TITLE
	 * 
	 * @param zpxwTitle
	 *            the value for ZPXW.ZPXW_TITLE
	 * 
	 * @mbggenerated
	 */
	public void setZpxwTitle(String zpxwTitle)
	{
		this.zpxwTitle = zpxwTitle;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column ZPXW.ZPXW_FBSJ
	 * 
	 * @return the value of ZPXW.ZPXW_FBSJ
	 * 
	 * @mbggenerated
	 */
	public String getZpxwFbsj()
	{
		return zpxwFbsj;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column ZPXW.ZPXW_FBSJ
	 * 
	 * @param zpxwFbsj
	 *            the value for ZPXW.ZPXW_FBSJ
	 * 
	 * @mbggenerated
	 */
	public void setZpxwFbsj(String zpxwFbsj)
	{
		this.zpxwFbsj = zpxwFbsj;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column ZPXW.ZPXW_KQZT
	 * 
	 * @return the value of ZPXW.ZPXW_KQZT
	 * 
	 * @mbggenerated
	 */
	public String getZpxwKqzt()
	{
		return zpxwKqzt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column ZPXW.ZPXW_KQZT
	 * 
	 * @param zpxwKqzt
	 *            the value for ZPXW.ZPXW_KQZT
	 * 
	 * @mbggenerated
	 */
	public void setZpxwKqzt(String zpxwKqzt)
	{
		this.zpxwKqzt = zpxwKqzt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column ZPXW.ZPXW_ADDUSER
	 * 
	 * @return the value of ZPXW.ZPXW_ADDUSER
	 * 
	 * @mbggenerated
	 */
	public String getZpxwSfzprc()
	{
		return zpxwSfzprc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column ZPXW.ZPXW_ADDUSER
	 * 
	 * @param zpxwAdduser
	 *            the value for ZPXW.ZPXW_ADDUSER
	 * 
	 * @mbggenerated
	 */
	public void setZpxwSfzprc(String zpxwSfzprc)
	{
		this.zpxwSfzprc = zpxwSfzprc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column ZPXW.ZPXW_ADDTIME
	 * 
	 * @return the value of ZPXW.ZPXW_ADDTIME
	 * 
	 * @mbggenerated
	 */
	public Date getZpxwAddtime()
	{
		return zpxwAddtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column ZPXW.ZPXW_ADDTIME
	 * 
	 * @param zpxwAddtime
	 *            the value for ZPXW.ZPXW_ADDTIME
	 * 
	 * @mbggenerated
	 */
	public void setZpxwAddtime(Date zpxwAddtime)
	{
		this.zpxwAddtime = zpxwAddtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column ZPXW.ZPXW_ADDCOMPANY
	 * 
	 * @return the value of ZPXW.ZPXW_ADDCOMPANY
	 * 
	 * @mbggenerated
	 */
	public String getZpxwAddcompany()
	{
		return zpxwAddcompany;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column ZPXW.ZPXW_ADDCOMPANY
	 * 
	 * @param zpxwAddcompany
	 *            the value for ZPXW.ZPXW_ADDCOMPANY
	 * 
	 * @mbggenerated
	 */
	public void setZpxwAddcompany(String zpxwAddcompany)
	{
		this.zpxwAddcompany = zpxwAddcompany;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column ZPXW.ZPXW_DELFLAG
	 * 
	 * @return the value of ZPXW.ZPXW_DELFLAG
	 * 
	 * @mbggenerated
	 */
	public Integer getZpxwDelflag()
	{
		return zpxwDelflag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column ZPXW.ZPXW_DELFLAG
	 * 
	 * @param zpxwDelflag
	 *            the value for ZPXW.ZPXW_DELFLAG
	 * 
	 * @mbggenerated
	 */
	public void setZpxwDelflag(Integer zpxwDelflag)
	{
		this.zpxwDelflag = zpxwDelflag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column ZPXW.ZPXW_CONTENT
	 * 
	 * @return the value of ZPXW.ZPXW_CONTENT
	 * 
	 * @mbggenerated
	 */
	public String getZpxwContent()
	{
		return zpxwContent;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column ZPXW.ZPXW_CONTENT
	 * 
	 * @param zpxwContent
	 *            the value for ZPXW.ZPXW_CONTENT
	 * 
	 * @mbggenerated
	 */
	public void setZpxwContent(String zpxwContent)
	{
		this.zpxwContent = zpxwContent;
	}
}