package com.ttgis.recruit.domain;

import java.io.Serializable;
import java.util.Date;

public class Zzjg implements Serializable
{
	private static final long serialVersionUID = -8610060438909092632L;
	private String yjnfy;
	private String yffy;
	private String cpcs;
	private String yfkye;
	private String sycs;
	private String sqfy;
	private String zzjgEjmm;
	private String zzjgDwjc;
	private String zzjgGzdh;
	private String zzjgOrder;
	private int zzjgLevel;

	public String getZzjgOrder()
	{
		return zzjgOrder;
	}

	public void setZzjgOrder(String zzjgOrder)
	{
		this.zzjgOrder = zzjgOrder;
	}

	public String getZzjgGzdh()
	{
		return zzjgGzdh;
	}

	public void setZzjgGzdh(String zzjgGzdh)
	{
		this.zzjgGzdh = zzjgGzdh;
	}

	public String getZzjgDwjc()
	{
		return zzjgDwjc;
	}

	public void setZzjgDwjc(String zzjgDwjc)
	{
		this.zzjgDwjc = zzjgDwjc;
	}

	public String getZzjgEjmm()
	{
		return zzjgEjmm;
	}

	public void setZzjgEjmm(String zzjgEjmm)
	{
		this.zzjgEjmm = zzjgEjmm;
	}

	public String getSycs()
	{
		return sycs;
	}

	public void setSycs(String sycs)
	{
		this.sycs = sycs;
	}

	public String getSqfy()
	{
		return sqfy;
	}

	public void setSqfy(String sqfy)
	{
		this.sqfy = sqfy;
	}

	public String getYfkye()
	{
		return yfkye;
	}

	public void setYfkye(String yfkye)
	{
		this.yfkye = yfkye;
	}

	public String getYjnfy()
	{
		return yjnfy;
	}

	public void setYjnfy(String yjnfy)
	{
		this.yjnfy = yjnfy;
	}

	public String getYffy()
	{
		return yffy;
	}

	public void setYffy(String yffy)
	{
		this.yffy = yffy;
	}

	public String getCpcs()
	{
		return cpcs;
	}

	public void setCpcs(String cpcs)
	{
		this.cpcs = cpcs;
	}

	private String sfjy;

	public String getSfjy()
	{
		return sfjy;
	}

	public void setSfjy(String sfjy)
	{
		this.sfjy = sfjy;
	}

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column ZZJG.ZZJG_ID
	 * 
	 * @mbggenerated
	 */
	private String zzjgId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column ZZJG.ZZJG_DWMC
	 * 
	 * @mbggenerated
	 */
	private String zzjgDwmc;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column ZZJG.ZZJG_DWDM
	 * 
	 * @mbggenerated
	 */
	private String zzjgDwdm;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column ZZJG.ZZJG_DWZH
	 * 
	 * @mbggenerated
	 */
	private String zzjgDwzh;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column ZZJG.ZZJG_ZHMM
	 * 
	 * @mbggenerated
	 */
	private String zzjgZhmm;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column ZZJG.ZZJG_SJDW
	 * 
	 * @mbggenerated
	 */
	private String zzjgSjdw;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column ZZJG.ZZJG_FWQX
	 * 
	 * @mbggenerated
	 */
	private String zzjgFwqx;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column ZZJG.ZZJG_DWFZR
	 * 
	 * @mbggenerated
	 */
	private String zzjgDwfzr;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column ZZJG.ZZJG_ZPLXR
	 * 
	 * @mbggenerated
	 */
	private String zzjgZplxr;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column ZZJG.ZZJG_LXRDH
	 * 
	 * @mbggenerated
	 */
	private String zzjgLxrdh;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column ZZJG.ZZJG_LXREMAIL
	 * 
	 * @mbggenerated
	 */
	private String zzjgLxremail;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column ZZJG.ZZJG_DWJJ
	 * 
	 * @mbggenerated
	 */
	private String zzjgDwjj;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column ZZJG.ZZJG_ADDTIME
	 * 
	 * @mbggenerated
	 */
	private Date zzjgAddtime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column ZZJG.ZZJG_DELFLAG
	 * 
	 * @mbggenerated
	 */
	private Long zzjgDelflag;

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column ZZJG.ZZJG_ID
	 * 
	 * @return the value of ZZJG.ZZJG_ID
	 * 
	 * @mbggenerated
	 */
	public String getZzjgId()
	{
		return zzjgId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column ZZJG.ZZJG_ID
	 * 
	 * @param zzjgId
	 *            the value for ZZJG.ZZJG_ID
	 * 
	 * @mbggenerated
	 */
	public void setZzjgId(String zzjgId)
	{
		this.zzjgId = zzjgId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column ZZJG.ZZJG_DWMC
	 * 
	 * @return the value of ZZJG.ZZJG_DWMC
	 * 
	 * @mbggenerated
	 */
	public String getZzjgDwmc()
	{
		return zzjgDwmc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column ZZJG.ZZJG_DWMC
	 * 
	 * @param zzjgDwmc
	 *            the value for ZZJG.ZZJG_DWMC
	 * 
	 * @mbggenerated
	 */
	public void setZzjgDwmc(String zzjgDwmc)
	{
		this.zzjgDwmc = zzjgDwmc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column ZZJG.ZZJG_DWDM
	 * 
	 * @return the value of ZZJG.ZZJG_DWDM
	 * 
	 * @mbggenerated
	 */
	public String getZzjgDwdm()
	{
		return zzjgDwdm;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column ZZJG.ZZJG_DWDM
	 * 
	 * @param zzjgDwdm
	 *            the value for ZZJG.ZZJG_DWDM
	 * 
	 * @mbggenerated
	 */
	public void setZzjgDwdm(String zzjgDwdm)
	{
		this.zzjgDwdm = zzjgDwdm;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column ZZJG.ZZJG_DWZH
	 * 
	 * @return the value of ZZJG.ZZJG_DWZH
	 * 
	 * @mbggenerated
	 */
	public String getZzjgDwzh()
	{
		return zzjgDwzh;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column ZZJG.ZZJG_DWZH
	 * 
	 * @param zzjgDwzh
	 *            the value for ZZJG.ZZJG_DWZH
	 * 
	 * @mbggenerated
	 */
	public void setZzjgDwzh(String zzjgDwzh)
	{
		this.zzjgDwzh = zzjgDwzh;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column ZZJG.ZZJG_ZHMM
	 * 
	 * @return the value of ZZJG.ZZJG_ZHMM
	 * 
	 * @mbggenerated
	 */
	public String getZzjgZhmm()
	{
		return zzjgZhmm;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column ZZJG.ZZJG_ZHMM
	 * 
	 * @param zzjgZhmm
	 *            the value for ZZJG.ZZJG_ZHMM
	 * 
	 * @mbggenerated
	 */
	public void setZzjgZhmm(String zzjgZhmm)
	{
		this.zzjgZhmm = zzjgZhmm;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column ZZJG.ZZJG_SJDW
	 * 
	 * @return the value of ZZJG.ZZJG_SJDW
	 * 
	 * @mbggenerated
	 */
	public String getZzjgSjdw()
	{
		return zzjgSjdw;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column ZZJG.ZZJG_SJDW
	 * 
	 * @param zzjgSjdw
	 *            the value for ZZJG.ZZJG_SJDW
	 * 
	 * @mbggenerated
	 */
	public void setZzjgSjdw(String zzjgSjdw)
	{
		this.zzjgSjdw = zzjgSjdw;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column ZZJG.ZZJG_FWQX
	 * 
	 * @return the value of ZZJG.ZZJG_FWQX
	 * 
	 * @mbggenerated
	 */
	public String getZzjgFwqx()
	{
		return zzjgFwqx;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column ZZJG.ZZJG_FWQX
	 * 
	 * @param zzjgFwqx
	 *            the value for ZZJG.ZZJG_FWQX
	 * 
	 * @mbggenerated
	 */
	public void setZzjgFwqx(String zzjgFwqx)
	{
		this.zzjgFwqx = zzjgFwqx;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column ZZJG.ZZJG_DWFZR
	 * 
	 * @return the value of ZZJG.ZZJG_DWFZR
	 * 
	 * @mbggenerated
	 */
	public String getZzjgDwfzr()
	{
		return zzjgDwfzr;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column ZZJG.ZZJG_DWFZR
	 * 
	 * @param zzjgDwfzr
	 *            the value for ZZJG.ZZJG_DWFZR
	 * 
	 * @mbggenerated
	 */
	public void setZzjgDwfzr(String zzjgDwfzr)
	{
		this.zzjgDwfzr = zzjgDwfzr;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column ZZJG.ZZJG_ZPLXR
	 * 
	 * @return the value of ZZJG.ZZJG_ZPLXR
	 * 
	 * @mbggenerated
	 */
	public String getZzjgZplxr()
	{
		return zzjgZplxr;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column ZZJG.ZZJG_ZPLXR
	 * 
	 * @param zzjgZplxr
	 *            the value for ZZJG.ZZJG_ZPLXR
	 * 
	 * @mbggenerated
	 */
	public void setZzjgZplxr(String zzjgZplxr)
	{
		this.zzjgZplxr = zzjgZplxr;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column ZZJG.ZZJG_LXRDH
	 * 
	 * @return the value of ZZJG.ZZJG_LXRDH
	 * 
	 * @mbggenerated
	 */
	public String getZzjgLxrdh()
	{
		return zzjgLxrdh;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column ZZJG.ZZJG_LXRDH
	 * 
	 * @param zzjgLxrdh
	 *            the value for ZZJG.ZZJG_LXRDH
	 * 
	 * @mbggenerated
	 */
	public void setZzjgLxrdh(String zzjgLxrdh)
	{
		this.zzjgLxrdh = zzjgLxrdh;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column ZZJG.ZZJG_LXREMAIL
	 * 
	 * @return the value of ZZJG.ZZJG_LXREMAIL
	 * 
	 * @mbggenerated
	 */
	public String getZzjgLxremail()
	{
		return zzjgLxremail;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column ZZJG.ZZJG_LXREMAIL
	 * 
	 * @param zzjgLxremail
	 *            the value for ZZJG.ZZJG_LXREMAIL
	 * 
	 * @mbggenerated
	 */
	public void setZzjgLxremail(String zzjgLxremail)
	{
		this.zzjgLxremail = zzjgLxremail;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column ZZJG.ZZJG_DWJJ
	 * 
	 * @return the value of ZZJG.ZZJG_DWJJ
	 * 
	 * @mbggenerated
	 */
	public String getZzjgDwjj()
	{
		return zzjgDwjj;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column ZZJG.ZZJG_DWJJ
	 * 
	 * @param zzjgDwjj
	 *            the value for ZZJG.ZZJG_DWJJ
	 * 
	 * @mbggenerated
	 */
	public void setZzjgDwjj(String zzjgDwjj)
	{
		this.zzjgDwjj = zzjgDwjj;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column ZZJG.ZZJG_ADDTIME
	 * 
	 * @return the value of ZZJG.ZZJG_ADDTIME
	 * 
	 * @mbggenerated
	 */
	public Date getZzjgAddtime()
	{
		return zzjgAddtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column ZZJG.ZZJG_ADDTIME
	 * 
	 * @param zzjgAddtime
	 *            the value for ZZJG.ZZJG_ADDTIME
	 * 
	 * @mbggenerated
	 */
	public void setZzjgAddtime(Date zzjgAddtime)
	{
		this.zzjgAddtime = zzjgAddtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column ZZJG.ZZJG_DELFLAG
	 * 
	 * @return the value of ZZJG.ZZJG_DELFLAG
	 * 
	 * @mbggenerated
	 */
	public Long getZzjgDelflag()
	{
		return zzjgDelflag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column ZZJG.ZZJG_DELFLAG
	 * 
	 * @param zzjgDelflag
	 *            the value for ZZJG.ZZJG_DELFLAG
	 * 
	 * @mbggenerated
	 */
	public void setZzjgDelflag(Long zzjgDelflag)
	{
		this.zzjgDelflag = zzjgDelflag;
	}

	public int getZzjgLevel()
	{
		return zzjgLevel;
	}

	public void setZzjgLevel(int zzjgLevel)
	{
		this.zzjgLevel = zzjgLevel;
	}
}