package com.ttgis.recruit.Mapper;

import java.util.List;

import com.ttgis.recruit.domain.Article;
import com.ttgis.recruit.domain.QueryArticle;

public interface ArticleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ARTICLE
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String articleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ARTICLE
     *
     * @mbggenerated
     */
    int insert(Article record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ARTICLE
     *
     * @mbggenerated
     */
    int insertSelective(Article record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ARTICLE
     *
     * @mbggenerated
     */
    Article selectByPrimaryKey(String articleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ARTICLE
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Article record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ARTICLE
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(Article record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ARTICLE
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Article record);
    
    List<Article> selectByWhere(QueryArticle qa);

	int selectCount(QueryArticle qa);
	
	 List<Article> selectByWhere1(QueryArticle qa);

	int selectCount1(QueryArticle qa);
	List<Article> queryArticleMark(String articleFbr);
	
	List<Article> LoadZytyData(QueryArticle qa);

	int LoadZytyDataCount(QueryArticle qa);
	
	List<Article> LoadRmbwData(QueryArticle qa);

	int LoadRmbwDataCount(QueryArticle qa);
	int articleDshCount();
	List<Article> queryarticleYgfxList();
	List<Article> queryarticleXrfxList();
}