package com.ttgis.recruit.Mapper;

import java.util.List;

import com.ttgis.recruit.domain.Bbs;
import com.ttgis.recruit.domain.Ltbq;
import com.ttgis.recruit.domain.QueryBbs;

public interface BbsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BBS
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String bbsId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BBS
     *
     * @mbggenerated
     */
    int insert(Bbs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BBS
     *
     * @mbggenerated
     */
    int insertSelective(Bbs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BBS
     *
     * @mbggenerated
     */
    Bbs selectByPrimaryKey(String bbsId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BBS
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Bbs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BBS
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Bbs record);
    
    List<Bbs> selectByWhere(QueryBbs p);

	int selectCount(QueryBbs p);
	
	List<Bbs> queryBbsMark(String bbsFbr);
	List<Bbs> queryBbs();
	List<Bbs> queryBbsByLtbq(Ltbq ltbq);
	
	 List<Bbs> selectqtBbsByWhere(QueryBbs p);

	int selectqtBbsCount(QueryBbs p);
	
	List<Bbs> selectByLtbqWhere(QueryBbs p);

	int selectByLtbqCount(QueryBbs p);
	
	List<Bbs> queryBbsByLtbkId(String ltbkId);
	
	List<Bbs> BbsByLtbkIdData(QueryBbs p);

	int BbsByLtbkIdDataCount(QueryBbs p);
	
	
	List<Bbs> queryLtbkByLtbkId(String ltbkId);
	
	int updZan(Bbs bbs);
	
	List<Bbs> htBbsData(QueryBbs qb);
	int htBbsCount(QueryBbs qb);
//===========================================================	
}