package com.ttgis.recruit.Mapper;

import java.util.List;
import java.util.Map;

import com.ttgis.recruit.domain.Collect_position;

public interface Collect_positionMapper
{
	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table COLLECT_POSITION
	 * 
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(Map<String, String> params);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table COLLECT_POSITION
	 * 
	 * @mbggenerated
	 */
	int insert(Collect_position record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table COLLECT_POSITION
	 * 
	 * @mbggenerated
	 */
	int insertSelective(Collect_position record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table COLLECT_POSITION
	 * 
	 * @mbggenerated
	 */
	Collect_position selectByPrimaryKey(String collectPositionId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table COLLECT_POSITION
	 * 
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(Collect_position record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table COLLECT_POSITION
	 * 
	 * @mbggenerated
	 */
	int updateByPrimaryKey(Collect_position record);

	List<Collect_position> selectByWhere(Collect_position collect_position);

}