package com.ttgis.recruit.Mapper;

import java.util.List;

import com.ttgis.recruit.domain.Cpfygl;
import com.ttgis.recruit.domain.PageCondition;

public interface CpfyglMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CPFYGL
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String cpfyglId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CPFYGL
     *
     * @mbggenerated
     */
    int insert(Cpfygl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CPFYGL
     *
     * @mbggenerated
     */
    int insertSelective(Cpfygl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CPFYGL
     *
     * @mbggenerated
     */
    Cpfygl selectByPrimaryKey(String cpfyglId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CPFYGL
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Cpfygl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CPFYGL
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Cpfygl record);
    List<Cpfygl> quary();
    List<Cpfygl> selectByWhere(PageCondition p);

	int selectCount(PageCondition p);
}