package com.ttgis.recruit.Mapper;

import java.util.List;

import com.ttgis.recruit.domain.Hycpdj;
import com.ttgis.recruit.domain.Hydj;
import com.ttgis.recruit.domain.QueryHydj;

public interface HydjMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HYDJ
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String hydjId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HYDJ
     *
     * @mbggenerated
     */
    int insert(Hydj record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HYDJ
     *
     * @mbggenerated
     */
    int insertSelective(Hydj record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HYDJ
     *
     * @mbggenerated
     */
    Hydj selectByPrimaryKey(String hydjId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HYDJ
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Hydj record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HYDJ
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Hydj record);
    
    List<Hydj> selectByWhere(QueryHydj qh);

   	int selectCount(QueryHydj qh);
   	List<Hydj> queryHydj();
   	Hycpdj queryHycpdj();
   	void UpdHycpdj(String hycpdj);
}