package com.ttgis.recruit.Mapper;



import java.util.List;
import java.util.Map;

import com.ttgis.recruit.domain.Jkgl;
import com.ttgis.recruit.domain.JkglWithBLOBs;

public interface JkglMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JKGL
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String jkglId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JKGL
     *
     * @mbggenerated
     */
    int insert(JkglWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JKGL
     *
     * @mbggenerated
     */
    int insertSelective(JkglWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JKGL
     *
     * @mbggenerated
     */
    JkglWithBLOBs selectByPrimaryKey(String jkglId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JKGL
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(JkglWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JKGL
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(JkglWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JKGL
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Jkgl record);
    
    int queryJkglSJbh(String jkglSjbh);
    
    List<JkglWithBLOBs> queryJkglBySJbh(Map<String, String> param);
    List<JkglWithBLOBs> queryRandomJk(String jkglStlx);
    
    int deleteByJkId(String jkglSjbh);
}