package com.ttgis.recruit.Mapper;

import java.util.List;
import java.util.Map;

import com.ttgis.recruit.domain.JkglFxtWithBLOBs;

public interface JkglFxtMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JKGL_FXT
     *
     * @mbggenerated
     */
    int insert(JkglFxtWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JKGL_FXT
     *
     * @mbggenerated
     */
    int insertSelective(JkglFxtWithBLOBs record);
    List<JkglFxtWithBLOBs> queryJkglFxt(Map<String, String> param);
    List<JkglFxtWithBLOBs> jkqueryJkglFxt(String stlx);
    int deleteJkglFxtByJkId(String sjbh);
}