package com.ttgis.recruit.Mapper;

import java.util.List;
 
import com.ttgis.recruit.domain.Ksxtkbgl;
import com.ttgis.recruit.domain.PageCondition;

public interface KsxtkbglMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table KSXTKBGL
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String ksxtkbglId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table KSXTKBGL
     *
     * @mbggenerated
     */
    int insert(Ksxtkbgl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table KSXTKBGL
     *
     * @mbggenerated
     */
    int insertSelective(Ksxtkbgl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table KSXTKBGL
     *
     * @mbggenerated
     */
    Ksxtkbgl selectByPrimaryKey(String ksxtkbglId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table KSXTKBGL
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Ksxtkbgl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table KSXTKBGL
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Ksxtkbgl record);
    List<Ksxtkbgl> quary();
    List<Ksxtkbgl> selectByWhere(PageCondition p);

	int selectCount(PageCondition p);
	List<Ksxtkbgl> queryKssj();
    
}