package com.ttgis.recruit.Mapper;

import java.util.List;

import com.ttgis.recruit.domain.Ltbq;
import com.ttgis.recruit.domain.LtbqArticle;
import com.ttgis.recruit.domain.LtbqBbs;
import com.ttgis.recruit.domain.LtbqXqqz;
import com.ttgis.recruit.domain.QueryLtbq;

public interface LtbqMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LTBQ
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String ltbqId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LTBQ
     *
     * @mbggenerated
     */
    int insert(Ltbq record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LTBQ
     *
     * @mbggenerated
     */
    int insertSelective(Ltbq record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LTBQ
     *
     * @mbggenerated
     */
    Ltbq selectByPrimaryKey(String ltbqId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LTBQ
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Ltbq record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LTBQ
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Ltbq record);
    /**
     * 查询标签
     * @return
     */
    List<Ltbq> queryLtbq();
    List<Ltbq> checkLtbq();
    List<Ltbq> checkLtbqArticle();
    List<Ltbq> checkLtbqXqqz();
    List<Ltbq> queryLtbqByBW();
    List<Ltbq> queryLtbqByQZ();
    
    Ltbq getLtbqByltbqName(String ltbqName);
    
    int deleteByltbqName(String ltbqName);
    
    List<Ltbq> selectByWhere(QueryLtbq ql);

	int selectCount(QueryLtbq ql);
	
	int addLtbqBbs(LtbqBbs lb);
	int addLtbqArticle(LtbqArticle la);
	int addLtbqXqqz(LtbqXqqz lx);
	
	int delLtbqBbs(String ltbqId);
	int delLtbqArticle(String ltbqId);
	int delLtbqXqqz(String ltbqId);
}