package com.ttgis.recruit.Mapper;

import java.util.List;

import com.ttgis.recruit.domain.Member;
import com.ttgis.recruit.domain.QueryMember;

public interface MemberMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MEMBER
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String memberId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MEMBER
     *
     * @mbggenerated
     */
    int insert(Member record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MEMBER
     *
     * @mbggenerated
     */
    int insertSelective(Member record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MEMBER
     *
     * @mbggenerated
     */
    Member selectByPrimaryKey(String memberId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MEMBER
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Member record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MEMBER
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Member record);
    
    List<Member> selectByWhere(QueryMember qm);

	int selectCount(QueryMember qm);
	int hyCount();
	
	List<Member> bzselectByWhere(QueryMember qm);

	int bzselectCount(QueryMember qm);
	
	List<Member> CpfyData(QueryMember qm);

	int CpfyDataCount(QueryMember qm);
	
	List<Member> queryCpfygl();
}