package com.ttgis.recruit.Mapper;

import java.util.List;
import java.util.Map;

import com.ttgis.recruit.domain.Msqgl_detailed;
import com.ttgis.recruit.domain.PageCondition;

public interface Msqgl_detailedMapper
{
	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table MSQGL_DETAILED
	 * 
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(String msqglDetailedId);

	int deleteByForeignKey(String jtjlkId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table MSQGL_DETAILED
	 * 
	 * @mbggenerated
	 */
	int insert(Msqgl_detailed record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table MSQGL_DETAILED
	 * 
	 * @mbggenerated
	 */
	int insertSelective(Msqgl_detailed record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table MSQGL_DETAILED
	 * 
	 * @mbggenerated
	 */
	Msqgl_detailed selectByPrimaryKey(String msqglDetailedId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table MSQGL_DETAILED
	 * 
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(Msqgl_detailed record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table MSQGL_DETAILED
	 * 
	 * @mbggenerated
	 */
	int updateByPrimaryKey(Msqgl_detailed record);

	List<Msqgl_detailed> selectByWhere(PageCondition p);

	int selectCount(PageCondition p);

	List<Msqgl_detailed> selectByForeignKey(String jlId);

	List<Msqgl_detailed> selectCountByForeignKey(String jlId);

	List<Msqgl_detailed> selectByJlId(String jlId);

	List<Msqgl_detailed> selectByMsg(Map<String, String> params);

	List<Msqgl_detailed> selectMsInfoByMsq(String msqId);

	int deleteByWhere(Map<String, String> params);
}