package com.ttgis.recruit.Mapper;

import java.util.List;
import java.util.Map;

import com.ttgis.recruit.domain.Msq; 
import com.ttgis.recruit.domain.QueryMsq;

public interface MsqMapper
{

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table MSQ
	 * 
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(String msqId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table MSQ
	 * 
	 * @mbggenerated
	 */
	int insert(Msq record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table MSQ
	 * 
	 * @mbggenerated
	 */
	int insertSelective(Msq record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table MSQ
	 * 
	 * @mbggenerated
	 */
	Msq selectByPrimaryKey(String msqId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table MSQ
	 * 
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(Msq record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table MSQ
	 * 
	 * @mbggenerated
	 */
	int updateByPrimaryKey(Msq record);

	List<Msq> selectByWhere(QueryMsq p);

	List<Msq> selectByType(Map<String, String> map);

	int selectCount(QueryMsq p);
}