package com.ttgis.recruit.Mapper;

import java.util.List;
import java.util.Map;

import com.ttgis.recruit.domain.PageCondition;
import com.ttgis.recruit.domain.Position;
import com.ttgis.recruit.domain.PositionWithBLOBs;

public interface PositionMapper
{
	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table POSITION
	 * 
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(String positionId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table POSITION
	 * 
	 * @mbggenerated
	 */
	int insert(PositionWithBLOBs record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table POSITION
	 * 
	 * @mbggenerated
	 */
	int insertSelective(PositionWithBLOBs record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table POSITION
	 * 
	 * @mbggenerated
	 */
	List<Position> selectByCompany(String zzjgId);

	PositionWithBLOBs selectByPrimaryKey(String positionId);

	List<PositionWithBLOBs> selectByPrimaryKeys(Map<String, Object> params);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table POSITION
	 * 
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(PositionWithBLOBs record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table POSITION
	 * 
	 * @mbggenerated
	 */
	int updateByPrimaryKeyWithBLOBs(PositionWithBLOBs record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table POSITION
	 * 
	 * @mbggenerated
	 */
	int updateByPrimaryKey(Position record);

	List<PositionWithBLOBs> selectByWhere(PageCondition p);

	int selectCount(PageCondition p);
	
	List<PositionWithBLOBs> selectByWhere1(PageCondition p);

	int selectCount1(PageCondition p);
}