package com.ttgis.recruit.Mapper;

import java.util.List;

import com.ttgis.recruit.domain.QueryReply;
import com.ttgis.recruit.domain.Reply;

public interface ReplyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table REPLY
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String replyId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table REPLY
     *
     * @mbggenerated
     */
    int insert(Reply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table REPLY
     *
     * @mbggenerated
     */
    int insertSelective(Reply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table REPLY
     *
     * @mbggenerated
     */
    Reply selectByPrimaryKey(String replyId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table REPLY
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Reply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table REPLY
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(Reply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table REPLY
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Reply record);
    
    int htBbsReviewReplyCount(QueryReply qr);
    List<Reply> htBbsReviewReplyData(QueryReply qr);
    List<Reply> qtGetReplyByReviewId(String reviewId);
    void delhtBbsReviewReplyByReviewId(String reviewId);
    
}