package com.ttgis.recruit.Mapper;

import java.util.List;

import com.ttgis.recruit.domain.QueryReview;
import com.ttgis.recruit.domain.Review;

public interface ReviewMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table REVIEW
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(String reviewId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table REVIEW
	 * @mbggenerated
	 */
	int insert(Review record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table REVIEW
	 * @mbggenerated
	 */
	int insertSelective(Review record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table REVIEW
	 * @mbggenerated
	 */
	Review selectByPrimaryKey(String reviewId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table REVIEW
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(Review record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table REVIEW
	 * @mbggenerated
	 */
	int updateByPrimaryKey(Review record);
	int delReviewByBbsId(String bbsId);
	
	List<Review> selectByBbsId(String BbsId);
	List<Review> queryReviewMark(String reviewFbr);
	List<Review> queryReview();
	List<Review> selectByWhere(QueryReview qr);
	int selectCount(QueryReview qr);
	
	List<Review>  queryByZzjgDwmc(String zzjgDwmc);
	List<Review>  queryreviewList(String bbsId);
	
	List<Review> htBbsReviewData(QueryReview qr);
	int htBbsReviewCount(QueryReview qr);
	
}