package com.ttgis.recruit.Mapper;

import com.ttgis.recruit.domain.Sqzt;

public interface SqztMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SQZT
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String sqztId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SQZT
     *
     * @mbggenerated
     */
    int insert(Sqzt record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SQZT
     *
     * @mbggenerated
     */
    int insertSelective(Sqzt record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SQZT
     *
     * @mbggenerated
     */
    Sqzt selectByPrimaryKey(String sqztId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SQZT
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Sqzt record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SQZT
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Sqzt record);
}