package com.ttgis.recruit.Mapper;

import java.util.List;

import com.ttgis.recruit.domain.QueryTkglFxt;
import com.ttgis.recruit.domain.tkglFxt;

public interface tkglFxtMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TKGL_FXT
     *
     * @mbggenerated
     */
    int insert(tkglFxt record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TKGL_FXT
     *
     * @mbggenerated
     */
    int insertSelective(tkglFxt record);
    
    List<tkglFxt> selectByWhere(QueryTkglFxt qt);
    int selectCount(QueryTkglFxt qt);
    
    tkglFxt selectByPrimaryKey(String id);
    int updateByPrimaryKeySelective(tkglFxt tkgl);
    int deleteByPrimaryKey(String id);
    List<tkglFxt> queryTkglFxt(String s);
}