package com.ttgis.recruit.Mapper;

import java.util.List;
import java.util.Map;

import com.ttgis.recruit.domain.PageCondition;
import com.ttgis.recruit.domain.Txl;

public interface TxlMapper
{
	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table TXL
	 * 
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(String txlId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table TXL
	 * 
	 * @mbggenerated
	 */
	int insert(Txl record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table TXL
	 * 
	 * @mbggenerated
	 */
	int insertSelective(Txl record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table TXL
	 * 
	 * @mbggenerated
	 */
	Txl selectByPrimaryKey(String txlId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table TXL
	 * 
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(Txl record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table TXL
	 * 
	 * @mbggenerated
	 */
	int updateByPrimaryKeyWithBLOBs(Txl record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table TXL
	 * 
	 * @mbggenerated
	 */
	int updateByPrimaryKey(Txl record);

	List<Txl> selectByWhere(PageCondition p);

	int selectCount(PageCondition p);

	List<Txl> loadMsg(Map<String, String> params);

	List<Txl> loadZw(String zzjg);

	List<Txl> loadBm(String zzjg);

	Txl selectByName(Map<String, String> params);

}