package com.ttgis.recruit.Mapper;

import java.util.List;
import java.util.Map;

import com.ttgis.recruit.domain.QueryUser;
import com.ttgis.recruit.domain.Userinfo;

public interface UserinfoMapper
{
	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table USERINFO
	 * 
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(String userId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table USERINFO
	 * 
	 * @mbggenerated
	 */
	int insert(Userinfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table USERINFO
	 * 
	 * @mbggenerated
	 */
	int insertSelective(Userinfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table USERINFO
	 * 
	 * @mbggenerated
	 */
	Userinfo selectByPrimaryKey(String userId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table USERINFO
	 * 
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(Userinfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table USERINFO
	 * 
	 * @mbggenerated
	 */
	int updateByPrimaryKey(Userinfo record);

	Userinfo CheckLogin(Userinfo user);

	List<Userinfo> selectLsyh(Map<String, String> params);

	List<Userinfo> queryUserFO();

	List<Userinfo> queryUserSun();

	List<Userinfo> selectByWhere(QueryUser qu);

	int selectCount(QueryUser qu);

	int userHfjy(String userId);

	int userJygl(String reviewPlr);

	List<Userinfo> selectWaitDelete(String currentdatetime);

	List<Userinfo> selectByMsqId(String msqId);

	int delLsUser(Map<String, String> map);

	List<Userinfo> hyselectByWhere(QueryUser qu);

	int hyselectCount(QueryUser qu);

	int checkUserIdcard(String userIdcard);

	int checkUserSfzh(String userSfzh);

	int checkUserName(String userEmail);

	int checkUserTelephone(Long userTelephone);

	Userinfo checkUserIsCZ(Userinfo user);

	int checkPlrSFinUser(String reviewPlr);

}