package com.ttgis.recruit.Mapper;

import java.util.List;

import com.ttgis.recruit.domain.Xcxx_attach;

public interface Xcxx_attachMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table XCXX_ATTACH
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String xcxxAttachId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table XCXX_ATTACH
     *
     * @mbggenerated
     */
    int insert(Xcxx_attach record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table XCXX_ATTACH
     *
     * @mbggenerated
     */
    int insertSelective(Xcxx_attach record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table XCXX_ATTACH
     *
     * @mbggenerated
     */
    Xcxx_attach selectByPrimaryKey(String xcxxAttachId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table XCXX_ATTACH
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Xcxx_attach record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table XCXX_ATTACH
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(Xcxx_attach record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table XCXX_ATTACH
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Xcxx_attach record);
    
    List<Xcxx_attach> selectByWhere(String strWhere);
}