package com.ttgis.recruit.Mapper;

import java.util.List;
import java.util.Map;

import com.ttgis.recruit.domain.QueryXcxx;
import com.ttgis.recruit.domain.Xcxx;

public interface XcxxMapper
{
	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table XCXX
	 * 
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(String xcxxId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table XCXX
	 * 
	 * @mbggenerated
	 */
	int insert(Xcxx record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table XCXX
	 * 
	 * @mbggenerated
	 */
	int insertSelective(Xcxx record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table XCXX
	 * 
	 * @mbggenerated
	 */
	Xcxx selectByPrimaryKey(String xcxxId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table XCXX
	 * 
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(Xcxx record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table XCXX
	 * 
	 * @mbggenerated
	 */
	int updateByPrimaryKeyWithBLOBs(Xcxx record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table XCXX
	 * 
	 * @mbggenerated
	 */
	int updateByPrimaryKey(Xcxx record);

	List<Xcxx> selectByWhere(QueryXcxx p);

	List<Xcxx> selectByType(Map<String, String> map);

	int selectCount(QueryXcxx p);
	
	/**
	 * 集团用户审核查询
	 * @param p
	 * @return
	 */
	int selectCount1(QueryXcxx p);
	
	/**
	 * 集团用户审核查询
	 * @param p
	 * @return
	 */
	List<Xcxx> selectByWhere1(QueryXcxx p);

}