package com.ttgis.recruit.Mapper;

import java.util.List;

import com.ttgis.recruit.domain.QueryXqqzLxgl;
import com.ttgis.recruit.domain.XqqzLxgl;

public interface XqqzLxglMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table XQQZLXGL
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String xqqzlxglId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table XQQZLXGL
     *
     * @mbggenerated
     */
    int insert(XqqzLxgl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table XQQZLXGL
     *
     * @mbggenerated
     */
    int insertSelective(XqqzLxgl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table XQQZLXGL
     *
     * @mbggenerated
     */
    XqqzLxgl selectByPrimaryKey(String xqqzlxglId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table XQQZLXGL
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(XqqzLxgl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table XQQZLXGL
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(XqqzLxgl record);
    
    List<XqqzLxgl> XqqzLxglData(QueryXqqzLxgl qxl);
    int XqqzLxglCount(QueryXqqzLxgl qxl);
    
    List<XqqzLxgl> queryXqqzLxgl();
    
    int XqqzCount(String xqqzLxglId);
}