package com.ttgis.recruit.Mapper;

import java.util.List;

import com.ttgis.recruit.domain.QueryXqqz;
import com.ttgis.recruit.domain.Xqqz;

public interface XqqzMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table XQQZ
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String xqqzId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table XQQZ
     *
     * @mbggenerated
     */
    int insert(Xqqz record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table XQQZ
     *
     * @mbggenerated
     */
    int insertSelective(Xqqz record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table XQQZ
     *
     * @mbggenerated
     */
    Xqqz selectByPrimaryKey(String xqqzId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table XQQZ
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Xqqz record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table XQQZ
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Xqqz record);
    
    List<Xqqz> selectByWhere(QueryXqqz p);

	int selectCount(QueryXqqz p);
	
	List<Xqqz> queryXqqzMark(String xqqzFbr);
	
	
	List<Xqqz> qtselectByWhere(QueryXqqz p);

	int qtselectCount(QueryXqqz p);
	List<Xqqz> queryxqqzList();
}