package com.ttgis.recruit.Mapper;

import java.util.List;

import com.ttgis.recruit.domain.QueryXxtz;
import com.ttgis.recruit.domain.Xxtz;

public interface XxtzMapper
{
	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table XXTZ
	 * 
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(String xxtzId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table XXTZ
	 * 
	 * @mbggenerated
	 */
	int insert(Xxtz record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table XXTZ
	 * 
	 * @mbggenerated
	 */
	int insertSelective(Xxtz record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table XXTZ
	 * 
	 * @mbggenerated
	 */
	Xxtz selectByPrimaryKey(String xxtzId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table XXTZ
	 * 
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(Xxtz record);

	int updateByWhereSelective(Xxtz xxtz);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table XXTZ
	 * 
	 * @mbggenerated
	 */
	int updateByPrimaryKey(Xxtz record);

	List<Xxtz> quary();

	List<Xxtz> selectCjtsEmail();

	List<Xxtz> selectByWhere(QueryXxtz p);

	int selectCount(QueryXxtz p);

	int selectFailedMsg(String strZzjgId);
}