package com.ttgis.recruit.Mapper;

import java.util.List;
 
import com.ttgis.recruit.domain.QueryZjgz;
import com.ttgis.recruit.domain.Zjgz;

public interface ZjgzMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZJGZ
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String zjgzId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZJGZ
     *
     * @mbggenerated
     */
    int insert(Zjgz record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZJGZ
     *
     * @mbggenerated
     */
    int insertSelective(Zjgz record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZJGZ
     *
     * @mbggenerated
     */
    Zjgz selectByPrimaryKey(String zjgzId);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZJGZ
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Zjgz record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZJGZ
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Zjgz record);
    List<Zjgz> quary();
    List<Zjgz> selectByWhere(QueryZjgz qz);
	int selectCount(QueryZjgz qz);
}