package com.ttgis.recruit.Mapper;

import java.util.List;

import com.ttgis.recruit.domain.Zpxw;
import com.ttgis.recruit.domain.ZzjgCondition;

public interface ZpxwMapper
{
	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table ZPXW
	 * 
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(String zpxwId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table ZPXW
	 * 
	 * @mbggenerated
	 */
	int insert(Zpxw record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table ZPXW
	 * 
	 * @mbggenerated
	 */
	int insertSelective(Zpxw record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table ZPXW
	 * 
	 * @mbggenerated
	 */
	Zpxw selectByPrimaryKey(String zpxwId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table ZPXW
	 * 
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(Zpxw record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table ZPXW
	 * 
	 * @mbggenerated
	 */
	int updateByPrimaryKeyWithBLOBs(Zpxw record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table ZPXW
	 * 
	 * @mbggenerated
	 */
	int updateByPrimaryKey(Zpxw record);

	List<Zpxw> selectByWhere(ZzjgCondition p);

	List<Zpxw> selectZpxwByWhere(ZzjgCondition p);

	List<Zpxw> selectInformationCenterByWhere(ZzjgCondition p);

	int selectCount(ZzjgCondition p);

	Zpxw selectZprc(String strZzjgId);

	List<Zpxw> select();
	
	void setTop(Zpxw zpxw);
	
	void updateTopTime(Zpxw zpxw);
	
	/**
	 * 置顶新闻不分页
	 * @param p
	 * @return
	 */
	List<Zpxw> selectZpxwByWhereTop(ZzjgCondition p);
	
	/**
	 * 非置顶新闻数
	 * @param p
	 * @return
	 */
	int selectCountNoTop(ZzjgCondition p);
	
	/**
	 * 非置顶新闻查询
	 * @param p
	 * @return
	 */
	List<Zpxw> selectZpxwByWhereNoTop(ZzjgCondition p);
	
}