package com.ttgis.recruit.Mapper;

import java.util.List;

import com.ttgis.recruit.domain.Zpzy;

public interface ZpzyMapper
{
	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table ZPZY
	 * 
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(String zpzyId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table ZPZY
	 * 
	 * @mbggenerated
	 */
	int insert(Zpzy record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table ZPZY
	 * 
	 * @mbggenerated
	 */
	int insertSelective(Zpzy record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table ZPZY
	 * 
	 * @mbggenerated
	 */
	Zpzy selectByPrimaryKey(String zpzyId);

	List<Zpzy> selectByType(String type);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table ZPZY
	 * 
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(Zpzy record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table ZPZY
	 * 
	 * @mbggenerated
	 */
	int updateByPrimaryKey(Zpzy record);
}