package com.ttgis.recruit.Mapper;

import java.util.List;

import com.ttgis.recruit.domain.Zylb;

public interface ZylbMapper
{
	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table ZYLB
	 * 
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(String zylbId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table ZYLB
	 * 
	 * @mbggenerated
	 */
	int insert(Zylb record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table ZYLB
	 * 
	 * @mbggenerated
	 */
	int insertSelective(Zylb record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table ZYLB
	 * 
	 * @mbggenerated
	 */
	Zylb selectByPrimaryKey(String zylbId);

	List<Zylb> selectAll();

	List<Zylb> selectAllOfMain();

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table ZYLB
	 * 
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(Zylb record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table ZYLB
	 * 
	 * @mbggenerated
	 */
	int updateByPrimaryKey(Zylb record);
}